# Derived 8.3 Feature Selection 2.1 — Stability and Error Analysis

**Purpose.** This notebook presents the saved feature-stability, year, month, and station diagnostics for the 2.1 development period.

**Method.** Every table is loaded from artifacts generated by the version-local scripts; no feature selection, metric fitting, or post-hoc filtering occurs here.

**Result.** Executing the notebook before the canonical run is safe and reports pending artifacts. Afterward it provides a reproducible view of all diagnostic evidence.

**Interpretation.** Year-dependent utility is treated as a stability question, and all nine Washington stations remain in scope regardless of performance.

In [1]:
from pathlib import Path
import json

import pandas as pd
from IPython.display import display


def locate_experiment() -> Path:
    for base in (Path.cwd(), *Path.cwd().parents):
        direct = base / "experiment" / "derived_8.3-feature-selection-2.1"
        nested = base / "notebooks" / "experiment" / "derived_8.3-feature-selection-2.1"
        if direct.is_dir():
            return direct.resolve()
        if nested.is_dir():
            return nested.resolve()
    raise FileNotFoundError("Cannot locate derived_8.3-feature-selection-2.1")


def show_csv(exp_dir: Path, relative_path: str, rows: int = 40) -> None:
    path = exp_dir / relative_path
    if path.exists():
        display(pd.read_csv(path).head(rows))
    else:
        print(f"Pending artifact: {path.relative_to(exp_dir)}")


def show_json(exp_dir: Path, relative_path: str) -> None:
    path = exp_dir / relative_path
    if path.exists():
        display(json.loads(path.read_text(encoding="utf-8")))
    else:
        print(f"Pending artifact: {path.relative_to(exp_dir)}")


EXP_DIR = locate_experiment()
print(f"Experiment: {EXP_DIR}")

Experiment: /scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.1

## Feature identity and cross-origin stability

**Purpose.** Inspect which predictors survive the frozen pruning method and whether support changes across 2020, 2021, and 2022.

**Method.** The saved rank summaries, direct/progressive overlap, exact-count consensus support, origin lists, and stability table are displayed without recomputation.

**Result.** The full run records selection frequency, percentile ranks, Jaccard overlap, rank correlation, V0 overlap, and late-year gains or losses.

**Interpretation.** Stable consensus—not any single year's list—defines the final feature identity, so 2021–2022 evidence informs the model without creating year-specific models.

In [2]:
show_csv(
    EXP_DIR,
    "artifacts/development/stages/05_robust_candidate_generation/feature_rank_summary.csv",
)
show_csv(
    EXP_DIR,
    "artifacts/development/stages/04_path_screen/direct_progressive_overlap.csv",
)
show_csv(
    EXP_DIR,
    "artifacts/development/stages/09_consensus/consensus_support.csv",
)
show_csv(
    EXP_DIR,
    "artifacts/development/stages/09_consensus/stability_summary.csv",
)
show_json(
    EXP_DIR,
    "artifacts/development/stages/09_consensus/origin_lists.json",
)

,fold_id,fold_family,outer_origin,path_source,method,reduction_size,is_endpoint,feature,original_position,importance_mean,importance_standard_error,importance_lcb,importance_observations,rank
0,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,V_rollmax_LST_modis_kobs30,215,0.002099,0.000842,0.000449,15,1
1,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,V_rollmin_G_API_kobs30,100,0.001634,0.000634,0.000391,15,2
2,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,V_ema_G_API_kobs30,102,0.000824,0.000236,0.000361,15,3
3,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,V_rollmax_F_NDVI_kobs30,253,0.000634,0.000193,0.000255,15,4
4,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,V_rollmax_G_API_kobs14,94,0.000282,0.000074,0.000137,15,5
5,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,C_lag_G_API_kobs1,103,0.000185,0.000027,0.000132,15,6
6,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,G_rain_sum_3d,25,0.000230,0.000056,0.000120,15,7
7,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,V_rollmax_G_API_kobs7,87,0.000155,0.000029,0.000098,15,8
8,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,V_ema_LST_modis_kobs30,216,0.000215,0.000060,0.000096,15,9
9,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,V_ema_G_API_kobs14,95,0.000184,0.000045,0.000095,15,10
10,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,C_smm_G_API_alpha0.85_n5,109,0.000140,0.000027,0.000087,15,11
11,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,V_ema_G_API_kobs7,88,0.000185,0.000052,0.000084,15,12
12,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,A_d_G_API_kobs14,76,0.000122,0.000025,0.000073,15,13
13,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,V_rollmin_LST_modis_kobs30,214,0.000252,0.000100,0.000056,15,14
14,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,G_rain_sum_7d,26,0.000089,0.000019,0.000051,15,15
15,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,G_API,23,0.000126,0.000039,0.000050,15,16
16,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,SMAP_sm_am_interp_lag30,32,0.000092,0.000022,0.000050,15,17
17,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,SMAP_sm_pm_interp_rollrange30,55,0.000075,0.000017,0.000041,15,18
18,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,V_rollstd_F_NDVI_kobs30,248,0.000062,0.000012,0.000039,15,19
19,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,C_lag_s2_b11_kobs30,336,0.000160,0.000064,0.000034,15,20
20,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,API_x_year,481,0.000068,0.000020,0.000029,15,21
21,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,V_rollmean_s2_b12_kobs14,358,0.000049,0.000012,0.000025,15,22
22,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,V_rollmin_s2_b11_kobs14,321,0.000091,0.000034,0.000025,15,23
23,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,V_rollmean_G_API_kobs7,85,0.000051,0.000014,0.000024,15,24
24,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,V_rollmin_G_API_kobs14,93,0.000055,0.000017,0.000020,15,25
25,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,V_rollmin_G_API_kobs7,86,0.000053,0.000018,0.000017,15,26
26,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,V_rollmean_s2_b11_kobs30,327,0.000057,0.000021,0.000017,15,27
27,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,precip_mm,2,0.000039,0.000013,0.000014,15,28
28,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,V_rollmin_E_SAR_diff_kobs14,283,0.000055,0.000021,0.000014,15,29
29,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,V_rollmax_s2_b12_kobs30,367,0.000305,0.000149,0.000013,15,30
30,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,SMAP_sm_am_interp_rollrange30,41,0.000062,0.000025,0.000012,15,31
31,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,V_rollmin_LST_modis_kobs14,207,0.000865,0.000435,0.000012,15,32
32,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,A_d_G_API_kobs1,72,0.000046,0.000018,0.000012,15,33
33,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,V_ema_F_NDMI_kobs7,126,0.000030,0.000010,0.000011,15,34
34,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,C_lag_F_NDVI_kobs1,255,0.000027,0.000008,0.000011,15,35
35,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,C_lag_s2_b12_kobs5,371,0.000022,0.000006,0.000010,15,36
36,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,V_ema_F_NDVI_kobs7,240,0.000033,0.000011,0.000010,15,37
37,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,F_NDVI,18,0.000024,0.000007,0.000010,15,38
38,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,V_ema_F_NDMI_kobs14,133,0.000033,0.000012,0.000009,15,39
39,forward_2020_l42,forward_time,2020,station_time,progressive,346,False,F_NDMI,19,0.000029,0.000010,0.000009,15,40

,fold_id,outer_origin,outer_family,path_source,endpoint,jaccard
0,forward_2020_l42,2020,forward_time,station_time,100,0.408451
1,forward_2020_l42,2020,forward_time,station_time,125,0.388889
2,forward_2020_l42,2020,forward_time,station_time,150,0.388889
3,forward_2020_l42,2020,forward_time,station_time,40,0.403509
4,forward_2020_l42,2020,forward_time,station_time,50,0.408451
5,forward_2020_l42,2020,forward_time,station_time,65,0.444444
6,forward_2020_l42,2020,forward_time,station_time,80,0.428571
7,forward_2020_l42,2020,forward_time,forward_time,100,0.574803
8,forward_2020_l42,2020,forward_time,forward_time,125,0.543210
9,forward_2020_l42,2020,forward_time,forward_time,150,0.522843
10,forward_2020_l42,2020,forward_time,forward_time,40,0.666667
11,forward_2020_l42,2020,forward_time,forward_time,50,0.639344
12,forward_2020_l42,2020,forward_time,forward_time,65,0.625000
13,forward_2020_l42,2020,forward_time,forward_time,80,0.584158
14,station_2020_g0_p42_l42,2020,station_time,station_time,100,0.754386
15,station_2020_g0_p42_l42,2020,station_time,station_time,125,0.633987
16,station_2020_g0_p42_l42,2020,station_time,station_time,150,0.554404
17,station_2020_g0_p42_l42,2020,station_time,station_time,40,0.818182
18,station_2020_g0_p42_l42,2020,station_time,station_time,50,0.785714
19,station_2020_g0_p42_l42,2020,station_time,station_time,65,0.884058
20,station_2020_g0_p42_l42,2020,station_time,station_time,80,0.777778
21,station_2020_g0_p42_l42,2020,station_time,forward_time,100,0.574803
22,station_2020_g0_p42_l42,2020,station_time,forward_time,125,0.592357
23,station_2020_g0_p42_l42,2020,station_time,forward_time,150,0.546392
24,station_2020_g0_p42_l42,2020,station_time,forward_time,40,0.777778
25,station_2020_g0_p42_l42,2020,station_time,forward_time,50,0.754386
26,station_2020_g0_p42_l42,2020,station_time,forward_time,65,0.688312
27,station_2020_g0_p42_l42,2020,station_time,forward_time,80,0.649485
28,station_2020_g1_p42_l42,2020,station_time,station_time,100,0.639344
29,station_2020_g1_p42_l42,2020,station_time,station_time,125,0.543210
30,station_2020_g1_p42_l42,2020,station_time,station_time,150,0.463415
31,station_2020_g1_p42_l42,2020,station_time,station_time,40,0.568627
32,station_2020_g1_p42_l42,2020,station_time,station_time,50,0.639344
33,station_2020_g1_p42_l42,2020,station_time,station_time,65,0.666667
34,station_2020_g1_p42_l42,2020,station_time,station_time,80,0.632653
35,station_2020_g1_p42_l42,2020,station_time,forward_time,100,0.612903
36,station_2020_g1_p42_l42,2020,station_time,forward_time,125,0.506024
37,station_2020_g1_p42_l42,2020,station_time,forward_time,150,0.492537
38,station_2020_g1_p42_l42,2020,station_time,forward_time,40,0.702128
39,station_2020_g1_p42_l42,2020,station_time,forward_time,50,0.639344

,feature,selection_frequency,median_percentile_rank,mean_percentile_rank,original_position,support_years,support_2020,support_2021,support_2022,selection_rate,late_year_support_count,late_support_change_vs_2020,support_trend
0,V_rollmin_G_API_kobs30,3,0.002016,0.002688,100,2020|2021|2022,True,True,True,1.000000,2,0.0,sustained
1,latitude,3,0.004032,0.005376,1,2020|2021|2022,True,True,True,1.000000,2,0.0,sustained
2,elev,3,0.006048,0.005376,10,2020|2021|2022,True,True,True,1.000000,2,0.0,sustained
3,V_rollmax_F_NDVI_kobs30,3,0.008065,0.008737,253,2020|2021|2022,True,True,True,1.000000,2,0.0,sustained
4,V_ema_LST_modis_kobs30,3,0.014113,0.013441,216,2020|2021|2022,True,True,True,1.000000,2,0.0,sustained
5,D_sin_DOY,3,0.014113,0.014113,16,2020|2021|2022,True,True,True,1.000000,2,0.0,sustained
6,V_rollmean_LST_modis_kobs30,3,0.022177,0.028226,213,2020|2021|2022,True,True,True,1.000000,2,0.0,sustained
7,G_rain_sum_3d,3,0.024194,0.031586,25,2020|2021|2022,True,True,True,1.000000,2,0.0,sustained
8,D_cos_DOY,3,0.030242,0.031586,17,2020|2021|2022,True,True,True,1.000000,2,0.0,sustained
9,C_lag_G_API_kobs1,3,0.036290,0.034274,103,2020|2021|2022,True,True,True,1.000000,2,0.0,sustained
10,precip_mm,3,0.038306,0.045699,2,2020|2021|2022,True,True,True,1.000000,2,0.0,sustained
11,G_API,3,0.044355,0.048387,23,2020|2021|2022,True,True,True,1.000000,2,0.0,sustained
12,API_x_year,3,0.056452,0.045699,481,2020|2021|2022,True,True,True,1.000000,2,0.0,sustained
13,V_rollmax_LST_modis_kobs30,2,0.014113,0.338038,215,2020|2021,True,True,False,0.666667,1,-0.5,lost_in_2021_2022
14,C_lag_LST_modis_kobs30,2,0.020161,0.045027,222,2020|2021,True,True,False,0.666667,1,-0.5,lost_in_2021_2022
15,V_rollmin_LST_modis_kobs30,2,0.020161,0.330645,214,2021|2022,False,True,True,0.666667,2,1.0,gained_in_2021_2022
16,aspect,2,0.026210,0.039651,12,2020|2021,True,True,False,0.666667,1,-0.5,lost_in_2021_2022
17,longitude,2,0.026210,0.108871,0,2020|2022,True,False,True,0.666667,1,-0.5,lost_in_2021_2022
18,SMAP_x_year,2,0.034274,0.053763,482,2021|2022,False,True,True,0.666667,2,1.0,gained_in_2021_2022
19,J_aspect_deg,2,0.040323,0.056452,428,2021|2022,False,True,True,0.666667,2,1.0,gained_in_2021_2022
20,V_rollmax_G_API_kobs30,2,0.042339,0.351478,101,2020|2022,True,False,True,0.666667,1,-0.5,lost_in_2021_2022
21,DOY,2,0.046371,0.249328,13,2021|2022,False,True,True,0.666667,2,1.0,gained_in_2021_2022
22,V_ema_G_API_kobs30,2,0.048387,0.126344,102,2020|2022,True,False,True,0.666667,1,-0.5,lost_in_2021_2022
23,V_ema_G_API_kobs14,2,0.050403,0.317204,95,2021|2022,False,True,True,0.666667,2,1.0,gained_in_2021_2022
24,V_rollmean_G_API_kobs30,2,0.050403,0.363575,99,2020|2022,True,False,True,0.666667,1,-0.5,lost_in_2021_2022
25,SMAP_sm_pm_interp_rollrange30,2,0.064516,0.360215,55,2020|2022,True,False,True,0.666667,1,-0.5,lost_in_2021_2022
26,V_rollmean_E_SAR_diff_kobs30,2,0.066532,0.341398,289,2020|2021,True,True,False,0.666667,1,-0.5,lost_in_2021_2022
27,V_ema_G_API_kobs7,2,0.070565,0.081989,88,2020|2022,True,False,True,0.666667,1,-0.5,lost_in_2021_2022
28,V_ema_SMAP_sm_interp_kobs30,2,0.072581,0.260753,406,2021|2022,False,True,True,0.666667,2,1.0,gained_in_2021_2022
29,V_rollmean_G_API_kobs14,2,0.076613,0.325941,92,2020|2022,True,False,True,0.666667,1,-0.5,lost_in_2021_2022
30,G_rain_sum_7d,1,0.086694,0.084005,26,2020,True,False,False,0.333333,0,-1.0,lost_in_2021_2022
31,V_rollmax_G_API_kobs14,1,0.090726,0.074597,94,2022,False,False,True,0.333333,1,0.5,gained_in_2021_2022
32,SMAP_sm_interp_rollstd30,1,0.090726,0.170027,68,2021,False,True,False,0.333333,1,0.5,gained_in_2021_2022
33,lia_mean_asc_deg,1,0.090726,0.267473,424,2022,False,False,True,0.333333,1,0.5,gained_in_2021_2022
34,V_rollmin_SMAP_sm_interp_kobs7,1,0.092742,0.379704,390,2022,False,False,True,0.333333,1,0.5,gained_in_2021_2022
35,SMAP_sm_pm_interp_rollmean30,1,0.094758,0.348790,53,2021,False,True,False,0.333333,1,0.5,gained_in_2021_2022
36,V_rollmax_G_API_kobs7,1,0.096774,0.087366,87,2021,False,True,False,0.333333,1,0.5,gained_in_2021_2022
37,D_z_E_SAR_ratio,1,0.098790,0.245968,486,2020,True,False,False,0.333333,0,-1.0,lost_in_2021_2022
38,V_rollmin_F_NDVI_kobs7,1,0.098790,0.372312,238,2020,True,False,False,0.333333,0,-1.0,lost_in_2021_2022
39,V_rollmin_E_SAR_diff_kobs30,1,0.100806,0.120296,290,2020,True,False,False,0.333333,0,-1.0,lost_in_2021_2022

,left_year,right_year,jaccard,rank_correlation,left_v0_overlap,right_v0_overlap
0,2020,2021,0.269841,0.090063,12,11
1,2020,2022,0.333333,0.331143,12,12
2,2021,2022,0.311475,0.162853,11,12

{'origins': [{'year': 2020,
   'selected': ['latitude',
    'V_rollmin_G_API_kobs30',
    'elev',
    'V_rollmax_LST_modis_kobs30',
    'aspect',
    'V_rollmax_F_NDVI_kobs30',
    'D_sin_DOY',
    'V_ema_LST_modis_kobs30',
    'V_rollmin_E_SAR_diff_kobs30',
    'C_lag_LST_modis_kobs30',
    'V_rollmax_G_API_kobs30',
    'G_rain_sum_3d',
    'longitude',
    'D_cos_DOY',
    'precip_mm',
    'V_rollmean_E_SAR_ratio_kobs30',
    'D_sa_E_SAR_ratio',
    'C_lag_G_API_kobs1',
    'lia_std_asc_deg',
    'V_rollmin_F_NDVI_kobs7',
    'V_rollmean_LST_modis_kobs30',
    'G_API',
    'G_rain_sum_7d',
    'V_ema_G_API_kobs30',
    'V_rollmean_G_API_kobs30',
    'V_rollmean_G_API_kobs14',
    's2_b11',
    'V_rollmean_E_SAR_diff_kobs30',
    'API_x_year',
    'K_aspect_cos',
    'C_lag_E_SAR_ratio_kobs30',
    'SMAP_sm_pm_interp_rollrange30',
    'V_rollrng_F_NDVI_kobs30',
    'V_rollmax_E_SAR_diff_kobs30',
    'V_ema_G_API_kobs7',
    'slope',
    'V_rollmin_G_API_kobs7',
    'D_z_E_SAR_ratio',
    'V_rollmax_s2_b11_kobs7',
    'V_rollstd_SMAP_sm_interp_kobs14'],
   'ordered': ['latitude',
    'V_rollmin_G_API_kobs30',
    'elev',
    'V_rollmax_LST_modis_kobs30',
    'aspect',
    'V_rollmax_F_NDVI_kobs30',
    'D_sin_DOY',
    'V_ema_LST_modis_kobs30',
    'V_rollmin_E_SAR_diff_kobs30',
    'C_lag_LST_modis_kobs30',
    'V_rollmax_G_API_kobs30',
    'G_rain_sum_3d',
    'longitude',
    'D_cos_DOY',
    'precip_mm',
    'V_rollmean_E_SAR_ratio_kobs30',
    'D_sa_E_SAR_ratio',
    'C_lag_G_API_kobs1',
    'lia_std_asc_deg',
    'V_rollmin_F_NDVI_kobs7',
    'V_rollmean_LST_modis_kobs30',
    'G_API',
    'G_rain_sum_7d',
    'V_ema_G_API_kobs30',
    'V_rollmean_G_API_kobs30',
    'V_rollmean_G_API_kobs14',
    's2_b11',
    'V_rollmean_E_SAR_diff_kobs30',
    'API_x_year',
    'K_aspect_cos',
    'C_lag_E_SAR_ratio_kobs30',
    'SMAP_sm_pm_interp_rollrange30',
    'V_rollrng_F_NDVI_kobs30',
    'V_rollmax_E_SAR_diff_kobs30',
    'V_ema_G_API_kobs7',
    'slope',
    'V_rollmin_G_API_kobs7',
    'D_z_E_SAR_ratio',
    'V_rollmax_s2_b11_kobs7',
    'V_rollstd_SMAP_sm_interp_kobs14',
    'G_DSLR',
    'V_rollmin_F_NDMI_kobs30',
    'V_rollmax_F_NDVI_kobs14',
    'J_bio_bio02',
    'lia_mean_asc_deg',
    'A_d_G_API_kobs30',
    'V_rollmax_G_API_kobs14',
    'V_rollmax_G_API_kobs7',
    'V_ema_s2_b12_kobs30',
    'SMAP_x_year',
    'V_rollmax_E_SAR_ratio_kobs14',
    'J_aspect_deg',
    'A_d_G_API_kobs5',
    'V_ema_LST_modis_kobs14',
    'V_rollcv_G_API_kobs7',
    'V_rollrng_LST_modis_kobs30',
    'A_d_LST_modis_kobs14',
    'C_smm_F_NDVI_alpha0.85_n5',
    'lia_std_desc_deg',
    'A_d_F_NDMI_kobs7',
    'D_z_F_NDMI',
    'E_SAR_ratio',
    'V_rollmin_G_API_kobs14',
    'C_smm_G_API_alpha0.85_n5',
    'C_lag_s2_b11_kobs1',
    'V_rollrng_SMAP_sm_interp_kobs14',
    'V_rollstd_LST_modis_kobs30',
    'A_d_G_API_kobs2',
    'C_smm_F_NDMI_alpha0.85_n5',
    'A_grad_E_SAR_diff_kobs30',
    'C_lag_G_API_kobs6',
    'C_lag_G_API_kobs5',
    'A_d_G_API_kobs1',
    'A_grad_G_API_kobs30',
    'V_rollcv_E_SAR_ratio_kobs14',
    'A_d_G_API_kobs7',
    'V_rollcv_s2_b12_kobs7',
    'V_rollcv_E_SAR_ratio_kobs30',
    'SMAP_sm_am_interp_rollstd30',
    'A_d_E_SAR_diff_kobs30',
    'A_d_LST_modis_kobs2',
    'J_bio_bio10',
    'J_sand_wfrac_b10',
    'V_rollrng_s2_b12_kobs7',
    'J_clay_wfrac_b60',
    'A_pct_F_NDMI',
    'SMAP_sm_am_interp_mask',
    'SMAP_sm_pm_interp_mask',
    'SMAP_sm_interp_mask',
    'C_lag_G_API_kobs30',
    'J_clay_wfrac_b30',
    'A_d_F_NDMI_kobs14',
    'SMAP_sm_am_interp_rollstd7',
    'H_corr_E_SAR_ratio__F_NDMI_kobs7',
    'C_lag_s2_b11_kobs2',
    'V_rollmax_s2_b12_kobs7',
    'lia_mean_desc_deg',
    'A_d_LST_modis_kobs7',
    'C_lag_s2_b11_kobs6',
    'V_ema_E_SAR_ratio_kobs14',
    'J_lc_code',
    'J_sand_wfrac_b60',
    'J_soil_texture_usda_b0',
    'J_soil_texture_usda_b100',
    'J_soil_texture_usda_b200',
    'J_soil_texture_usda_b30',
    'J_soil_texture_usda_b60',
    'K_sand_clay_ratio_b0',
    'year',
    'year_frac',
    'J_sand_clay_ratio_b0',
    'J_clay_wfrac_b100',
    'J_clay_wfrac_b200',
    'J_clay_wfrac_b10',
    'J_sand_wfrac_b30',
    'A_grad_F_NDMI_kobs7',
    'J_bio_bio14',
    'A_grad_E_SAR_ratio_kobs7',
    'V_rollcv_s2_b11_kobs7',
    'V_rollcv_LST_modis_kobs30',
    'V_rollmax_LST_modis_kobs14',
    'E_rough_s1_vv_kobs14',
    'J_bio_bio05',
    'V_ema_s2_b11_kobs30',
    'C_lag_E_SAR_diff_kobs30',
    'sin_year',
    'cos_year',
    'G_DSLR_isnan',
    'J_sand_wfrac_b100',
    'J_soil_texture_usda_b10',
    'J_clay_wfrac_b0',
    'D_fft_dom_LST_modis_kobs30',
    'H_corr_LST_modis__F_NDMI_kobs7',
    's2_b8',
    'V_rollcv_F_NDMI_kobs7',
    'A_grad_LST_modis_kobs7',
    'V_rollmean_s2_b11_kobs7',
    'J_bio_bio11',
    'C_lag_s2_b11_kobs5',
    'C_lag_F_NDMI_kobs1',
    'J_elev_m',
    'V_rollmin_s2_b11_kobs30',
    'V_rollmin_F_NDMI_kobs14',
    'V_ema_s2_b11_kobs14',
    'D_fft_ent_E_SAR_ratio_kobs30',
    'V_rollcv_F_NDMI_kobs14',
    'V_rollmax_s2_b11_kobs14',
    'V_rollmean_s2_b11_kobs14',
    'SMAP_sm_interp_rollrange30',
    'V_rollmean_G_API_kobs7',
    'J_bio_bio08',
    'J_bio_bio07',
    'A_d_F_NDMI_kobs5',
    'C_lag_s2_b12_kobs1',
    'V_rollcv_LST_modis_kobs7',
    'J_sand_wfrac_b200',
    'SMAP_sm_interp_rollstd7',
    'C_lag_E_SAR_ratio_kobs1',
    'A_grad_E_SAR_ratio_kobs30',
    'C_lag_s2_b12_kobs12',
    'V_rollrng_s2_b11_kobs7',
    'A_grad_SMAP_sm_interp_kobs14',
    'A_pct_s2_b11',
    'A_pct_E_SAR_ratio',
    'K_clay_plus_sand_b0',
    'SMAP_sm_am_interp_pctchg',
    'A_d_s2_b12_kobs14',
    'J_bio_bio01',
    'SMAP_sm_interp_rollstd30',
    'A_d_E_SAR_ratio_kobs2',
    'D_fft_ent_LST_modis_kobs30',
    'V_rollstd_E_SAR_diff_kobs7',
    'SMAP_sm_pm_interp_rollstd7',
    'V_rollstd_s2_b12_kobs7',
    'A_d_SMAP_sm_interp_kobs14',
    'V_rollstd_E_SAR_ratio_kobs14',
    'V_rollcv_F_NDVI_kobs14',
    'C_lag_F_NDVI_kobs30',
    'V_rollmax_s2_b12_kobs30',
    'V_rollstd_G_API_kobs30',
    'V_rollrng_s2_b11_kobs14',
    'V_ema_s2_b11_kobs7',
    'V_rollstd_E_SAR_diff_kobs14',
    'V_rollcv_F_NDMI_kobs30',
    'V_rollrng_E_SAR_diff_kobs30',
    'V_rollstd_F_NDVI_kobs14',
    'J_bio_bio16',
    'V_rollmax_s2_b11_kobs30',
    'V_rollcv_E_SAR_diff_kobs30',
    'C_lag_F_NDVI_kobs5',
    'V_rollmean_F_NDMI_kobs14',
    'C_lag_E_SAR_diff_kobs12',
    'V_rollstd_E_SAR_ratio_kobs30',
    'SMAP_sm_interp_lag1',
    'C_lag_SMAP_sm_interp_kobs30',
    'SMAP_sm_am_interp_lag1',
    'D_fft_dom_F_NDMI_kobs30',
    'SMAP_sm_interp_diff1',
    'E_dVV_1',
    'SMAP_sm_pm_interp_pctchg',
    'J_bio_bio18',
    'SMAP_sm_am_interp_diff1',
    'A_d_E_SAR_ratio_kobs1',
    'A_pct_LST_modis',
    'J_bio_bio06',
    'J_sand_wfrac_b0',
    'SMAP_sm_interp_pctchg',
    'A_grad_s2_b12_kobs30',
    'A_d_E_SAR_ratio_kobs30',
    'A_d_SMAP_sm_interp_kobs1',
    'A_pct_SMAP_sm_interp',
    'A_d_F_NDMI_kobs2',
    'A_d_F_NDMI_kobs1',
    'J_slope_deg',
    'V_rollrng_SMAP_sm_interp_kobs7',
    'V_rollcv_F_NDVI_kobs7',
    'V_rollstd_F_NDMI_kobs7',
    'J_bio_bio09',
    'A_pct_E_SAR_diff',
    'SMAP_sm_am_interp_rollrange7',
    'H_corr_LST_modis__F_NDMI_kobs14',
    'V_rollcv_G_API_kobs30',
    'A_d_LST_modis_kobs1',
    'E_rough_s1_vv_kobs7',
    'C_lag_G_API_kobs2',
    'A_d_F_NDVI_kobs1',
    'A_grad_SMAP_sm_interp_kobs7',
    'V_rollstd_SMAP_sm_interp_kobs30',
    's2_b12',
    'A_d_s2_b11_kobs1',
    'A_d_s2_b11_kobs2',
    'D_fft_ent_F_NDMI_kobs30',
    'SMAP_sm_pm_interp_diff1',
    'V_ema_s2_b12_kobs7',
    'V_rollstd_s2_b11_kobs7',
    'V_rollstd_G_API_kobs7',
    'A_grad_s2_b12_kobs7',
    'A_pct_F_NDVI',
    'V_rollcv_LST_modis_kobs14',
    'A_d_SMAP_sm_interp_kobs7',
    'V_rollcv_E_SAR_diff_kobs7',
    'J_bio_bio17',
    'A_d_E_SAR_ratio_kobs5',
    'SMAP_sm_interp_rollrange7',
    'A_d_F_NDVI_kobs2',
    'A_d_SMAP_sm_interp_kobs2',
    'K_aspect_sin',
    'SMAP_sm_pm_interp_rollrange7',
    'V_rollstd_SMAP_sm_interp_kobs7',
    'V_rollrng_F_NDMI_kobs7',
    'A_d_E_SAR_diff_kobs1',
    'V_rollmean_s2_b12_kobs7',
    'A_d_s2_b12_kobs5',
    'V_rollmax_E_SAR_ratio_kobs7',
    'A_d_E_SAR_ratio_kobs7',
    'V_rollcv_E_SAR_ratio_kobs7',
    'A_d_s2_b12_kobs2',
    'A_d_s2_b11_kobs7',
    'A_d_LST_modis_kobs5',
    'V_rollstd_F_NDVI_kobs7',
    'C_smm_LST_modis_alpha0.85_n5',
    'A_d_E_SAR_diff_kobs2',
    'A_grad_F_NDMI_kobs14',
    'A_d_s2_b12_kobs7',
    'C_smm_s2_b12_alpha0.85_n5',
    'D_fft_dom_E_SAR_ratio_kobs30',
    'V_rollstd_LST_modis_kobs7',
    'A_grad_s2_b12_kobs14',
    'A_d_s2_b12_kobs1',
    'V_rollrng_SMAP_sm_interp_kobs30',
    'J_bio_bio03',
    'A_d_SMAP_sm_interp_kobs5',
    'V_rollcv_G_API_kobs14',
    'A_d_s2_b11_kobs5',
    'A_grad_s2_b11_kobs7',
    'V_ema_s2_b12_kobs14',
    's2_b4',
    'V_rollrng_LST_modis_kobs7',
    'A_d_F_NDVI_kobs5',
    'D_sa_F_NDMI',
    'A_grad_F_NDVI_kobs30',
    'SMAP_sm_interp_grad7',
    'V_rollrng_s2_b12_kobs14',
    'V_rollstd_s2_b12_kobs14',
    'E_rough_s1_vh_kobs7',
    'V_ema_E_SAR_diff_kobs14',
    'A_grad_s2_b11_kobs30',
    'C_lag_SMAP_sm_interp_kobs1',
    'V_rollrng_F_NDMI_kobs30',
    'V_rollrng_E_SAR_diff_kobs7',
    'V_rollstd_LST_modis_kobs14',
    'A_grad_G_API_kobs7',
    'C_lag_F_NDVI_kobs6',
    'A_grad_F_NDVI_kobs7',
    'V_rollmin_s2_b12_kobs30',
    'F_NDVI',
    'A_grad_E_SAR_diff_kobs14',
    'V_rollrng_F_NDVI_kobs7',
    'C_smm_s2_b11_alpha0.85_n5',
    'H_corr_E_SAR_ratio__F_NDMI_kobs14',
    'V_rollmin_E_SAR_ratio_kobs7',
    'V_rollstd_E_SAR_diff_kobs30',
    'V_rollrng_E_SAR_ratio_kobs7',
    'SMAP_sm_interp_rollmean7',
    'A_d_G_API_kobs14',
    'C_lag_E_SAR_ratio_kobs6',
    'J_bio_bio19',
    'V_rollmin_s2_b12_kobs14',
    'A_grad_G_API_kobs14',
    'V_rollrng_G_API_kobs7',
    'V_rollmin_F_NDVI_kobs14',
    'A_d_s2_b12_kobs30',
    'SMAP_sm_interp',
    'SMAP_sm_am_interp_lag30',
    'V_rollcv_s2_b11_kobs14',
    'V_rollmean_E_SAR_ratio_kobs14',
    'A_grad_F_NDMI_kobs30',
    'V_rollmin_s2_b11_kobs7',
    'F_MSI',
    'V_rollmin_E_SAR_diff_kobs14',
    'V_ema_SMAP_sm_interp_kobs30',
    'C_lag_s2_b11_kobs12',
    'C_lag_E_SAR_diff_kobs2',
    'C_smm_SMAP_sm_interp_alpha0.85_n5',
    'C_lag_E_SAR_ratio_kobs12',
    'V_rollmean_E_SAR_ratio_kobs7',
    'V_rollmin_F_NDVI_kobs30',
    'V_rollmean_E_SAR_diff_kobs7',
    'C_lag_F_NDMI_kobs6',
    'SMAP_sm_interp_lag30',
    'C_lag_E_SAR_diff_kobs5',
    'V_rollrng_s2_b12_kobs30',
    'A_d_F_NDMI_kobs30',
    'C_lag_s2_b12_kobs30',
    'V_rollstd_F_NDMI_kobs30',
    'V_ema_F_NDVI_kobs14',
    'V_rollmean_SMAP_sm_interp_kobs7',
    'C_lag_F_NDMI_kobs30',
    'SMAP_sm_interp_lag7',
    'V_rollcv_s2_b11_kobs30',
    'C_lag_LST_modis_kobs1',
    'C_lag_SMAP_sm_interp_kobs6',
    'C_lag_F_NDMI_kobs12',
    'DOY',
    'SMAP_sm_interp_ema02',
    'SMAP_sm_interp_rollmean30',
    'A_grad_F_NDVI_kobs14',
    'E_SAR_diff',
    'A_d_E_SAR_diff_kobs7',
    'A_pct_G_API',
    'V_rollcv_s2_b12_kobs14',
    'A_grad_E_SAR_diff_kobs7',
    'V_rollmean_s2_b12_kobs14',
    'A_d_LST_modis_kobs30',
    'A_grad_s2_b11_kobs14',
    'A_pct_s2_b12',
    'J_clay_plus_sand_b0',
    'V_rollstd_s2_b11_kobs30',
    'V_rollmin_E_SAR_diff_kobs7',
    'A_d_E_SAR_diff_kobs5',
    'V_rollmean_SMAP_sm_interp_kobs14',
    'A_d_s2_b11_kobs14',
    'SMAP_sm_am_interp_lag7',
    'V_rollcv_E_SAR_diff_kobs14',
    'V_rollstd_E_SAR_ratio_kobs7',
    'C_lag_s2_b12_kobs5',
    'A_d_F_NDVI_kobs30',
    'V_rollrng_E_SAR_diff_kobs14',
    'A_grad_E_SAR_ratio_kobs14',
    'C_lag_F_NDMI_kobs2',
    'A_grad_LST_modis_kobs14',
    'SMAP_sm_am_interp_rollmean7',
    'A_grad_SMAP_sm_interp_kobs30',
    'A_d_s2_b11_kobs30',
    'C_lag_SMAP_sm_interp_kobs5',
    'C_lag_F_NDVI_kobs1',
    'F_NDMI',
    'V_ema_F_NDMI_kobs7',
    'V_rollrng_E_SAR_ratio_kobs14',
    'V_rollcv_SMAP_sm_interp_kobs7',
    'V_rollmean_F_NDVI_kobs7',
    'V_rollrng_LST_modis_kobs14',
    'V_rollrng_s2_b11_kobs30',
    'V_ema_SMAP_sm_interp_kobs14',
    'V_rollrng_F_NDMI_kobs14',
    'V_rollmin_F_NDMI_kobs7',
    'V_rollrng_E_SAR_ratio_kobs30',
    'V_rollstd_F_NDMI_kobs14',
    'C_smm_E_SAR_diff_alpha0.85_n5',
    'V_rollmax_F_NDVI_kobs7',
    'C_lag_E_SAR_diff_kobs1',
    'V_rollcv_SMAP_sm_interp_kobs14',
    'A_d_F_NDVI_kobs7',
    'C_lag_LST_modis_kobs2',
    'SMAP_sm_pm_interp',
    'V_rollmean_SMAP_sm_interp_kobs30',
    'C_lag_F_NDVI_kobs2',
    'V_rollmean_F_NDVI_kobs14',
    'V_rollstd_s2_b11_kobs14',
    'A_grad_LST_modis_kobs30',
    'V_rollmin_s2_b12_kobs7',
    'SMAP_sm_am_interp',
    'SMAP_sm_am_interp_rollrange30',
    'V_rollstd_F_NDVI_kobs30',
    'C_lag_F_NDMI_kobs5',
    'J_bio_bio12',
    'V_rollmax_E_SAR_diff_kobs7',
    'A_d_E_SAR_diff_kobs14',
    'C_lag_s2_b12_kobs2',
    'J_bio_bio13',
    'A_d_E_SAR_ratio_kobs14',
    'C_lag_s2_b12_kobs6',
    'V_rollmean_s2_b12_kobs30',
    'V_rollmean_s2_b11_kobs30',
    'V_rollmean_E_SAR_diff_kobs14',
    'C_smm_E_SAR_ratio_alpha0.85_n5',
    'J_bio_bio15',
    'C_lag_E_SAR_ratio_kobs2',
    'V_rollmin_LST_modis_kobs14',
    'V_ema_LST_modis_kobs7',
    'V_rollmean_LST_modis_kobs7',
    'D_z_LST_modis',
    'V_rollcv_F_NDVI_kobs30',
    'V_rollmax_s2_b12_kobs14',
    'V_ema_F_NDMI_kobs14',
    'C_lag_E_SAR_ratio_kobs5',
    'SMAP_sm_pm_interp_rollstd30',
    'V_ema_E_SAR_diff_kobs7',
    'V_ema_SMAP_sm_interp_kobs7',
    'V_rollrng_G_API_kobs30',
    'A_d_F_NDVI_kobs14',
    'C_lag_G_API_kobs12',
    'V_ema_G_API_kobs14',
    'SMAP_sm_pm_interp_grad7',
    'K_slope_sin',
    'G_rain_sum_30d',
    'V_rollmax_SMAP_sm_interp_kobs7',
    'K_slope_cos',
    'V_rollmean_F_NDMI_kobs30',
    'E_rough_s1_vh_kobs14',
    'V_rollmin_LST_modis_kobs7',
    'V_rollmean_F_NDMI_kobs7',
    'SMAP_sm_am_interp_grad7',
    'V_rollmean_LST_modis_kobs14',
    'V_rollcv_s2_b12_kobs30',
    'LST_modis',
    'V_ema_E_SAR_ratio_kobs7',
    'SMAP_sm_pm_interp_rollmean30',
    'C_lag_SMAP_sm_interp_kobs12',
    'SMAP_sm_am_interp_ema02',
    'V_rollmax_F_NDMI_kobs7',
    'C_lag_LST_modis_kobs6',
    'C_lag_F_NDVI_kobs12',
    'V_rollstd_s2_b12_kobs30',
    'V_ema_F_NDVI_kobs30',
    'V_rollstd_G_API_kobs14',
    'I_ts_spike_s1_vv',
    'SMAP_sm_pm_interp_rollmean7',
    'C_lag_E_SAR_diff_kobs6',
    'V_rollmin_s2_b11_kobs14',
    'C_lag_SMAP_sm_interp_kobs2',
    'V_rollmax_F_NDMI_kobs14',
    'V_rollmax_SMAP_sm_interp_kobs14',
    'SMAP_sm_pm_interp_lag1',
    'J_bio_bio04',
    'SMAP_sm_pm_interp_lag7',
    'V_rollmax_E_SAR_ratio_kobs30',
    'V_rollmax_E_SAR_diff_kobs14',
    'C_lag_LST_modis_kobs5',
    'V_ema_E_SAR_ratio_kobs30',
    'D_sa_LST_modis',
    'V_rollrng_F_NDVI_kobs14',
    's1_vv',
    'V_rollrng_G_API_kobs14',
    'A_d_SMAP_sm_interp_kobs30',
    'V_rollmin_LST_modis_kobs30',
    'SMAP_ampm_diff_interp',
    'C_lag_LST_modis_kobs12',
    'V_rollmin_SMAP_sm_interp_kobs7',
    'V_rollmax_LST_modis_kobs7',
    'V_ema_E_SAR_diff_kobs30',
    'V_rollmax_F_NDMI_kobs30',
    'V_ema_F_NDVI_kobs7',
    'V_rollmin_E_SAR_ratio_kobs14',
    'SMAP_sm_pm_interp_ema02',
    'V_rollmin_E_SAR_ratio_kobs30',
    'SMAP_sm_pm_interp_lag30',
    's1_vh',
    'V_ema_F_NDMI_kobs30',
    'V_rollcv_SMAP_sm_interp_kobs30',
    'V_rollmax_SMAP_sm_interp_kobs30',
    'SMAP_sm_am_interp_rollmean30',
    'C_lag_s2_b11_kobs30',
    'V_rollmin_SMAP_sm_interp_kobs14',
    'V_rollmean_F_NDVI_kobs30',
    'V_rollmin_SMAP_sm_interp_kobs30'],
   'selected_ordered_feature_hash': '3b3eb6c2b164e3b5f47b846b468251c48fb4eb79f4f697288cc1fa2d30d8c527',
   'complete_ranking_hash': '61667abec308ba6409ddf43486498c72aa700bd2f06add8c36c76be9c3468e7f',
   'path': {'method': 'progressive',
    'start_size': 496,
    'endpoints': {'150': ['latitude',
      'V_rollmin_G_API_kobs30',
      'elev',
      'aspect',
      'V_rollmax_LST_modis_kobs30',
      'V_rollmax_F_NDVI_kobs30',
      'V_rollmin_E_SAR_diff_kobs30',
      'C_lag_LST_modis_kobs30',
      'D_sin_DOY',
      'D_cos_DOY',
      'lia_std_asc_deg',
      'V_ema_G_API_kobs30',
      'G_rain_sum_3d',
      'longitude',
      'V_rollmax_G_API_kobs30',
      'C_lag_G_API_kobs1',
      'V_rollmean_G_API_kobs30',
      'V_ema_LST_modis_kobs30',
      'G_API',
      'G_rain_sum_7d',
      'V_rollmax_G_API_kobs7',
      'V_rollmax_F_NDVI_kobs14',
      'precip_mm',
      'V_ema_LST_modis_kobs14',
      's2_b11',
      'API_x_year',
      'V_rollmax_E_SAR_diff_kobs30',
      'slope',
      'D_sa_E_SAR_ratio',
      'V_rollmean_G_API_kobs14',
      'V_rollmax_LST_modis_kobs14',
      'V_ema_G_API_kobs7',
      'D_z_E_SAR_ratio',
      'V_rollmax_E_SAR_ratio_kobs14',
      'V_rollmin_F_NDVI_kobs7',
      'V_rollmax_G_API_kobs14',
      'V_rollmin_F_NDMI_kobs30',
      'V_rollmean_LST_modis_kobs30',
      'SMAP_x_year',
      'C_smm_F_NDMI_alpha0.85_n5',
      'V_rollmean_E_SAR_ratio_kobs30',
      'C_lag_s2_b11_kobs6',
      'V_rollmin_G_API_kobs7',
      'J_bio_bio02',
      'K_aspect_cos',
      'SMAP_sm_pm_interp_rollrange30',
      'V_rollrng_LST_modis_kobs30',
      'C_lag_E_SAR_ratio_kobs30',
      'V_rollmin_G_API_kobs14',
      'lia_mean_asc_deg',
      'J_aspect_deg',
      'A_d_G_API_kobs1',
      's2_b8',
      'E_rough_s1_vv_kobs14',
      'A_d_LST_modis_kobs14',
      'A_d_G_API_kobs30',
      'V_rollrng_F_NDVI_kobs30',
      'V_rollmean_E_SAR_diff_kobs30',
      'C_smm_F_NDVI_alpha0.85_n5',
      'G_DSLR',
      'A_d_G_API_kobs5',
      'V_ema_s2_b11_kobs30',
      'C_smm_G_API_alpha0.85_n5',
      'D_z_F_NDMI',
      'V_rollcv_G_API_kobs7',
      'A_grad_E_SAR_diff_kobs30',
      'V_rollstd_SMAP_sm_interp_kobs14',
      'V_rollrng_SMAP_sm_interp_kobs14',
      'A_d_F_NDMI_kobs14',
      'lia_mean_desc_deg',
      'A_d_G_API_kobs2',
      'C_lag_F_NDMI_kobs1',
      'V_ema_E_SAR_ratio_kobs14',
      'V_rollmin_s2_b11_kobs30',
      'E_SAR_ratio',
      'A_grad_E_SAR_ratio_kobs7',
      'A_d_G_API_kobs7',
      'V_rollstd_LST_modis_kobs30',
      'C_lag_s2_b11_kobs2',
      'V_rollmean_s2_b11_kobs14',
      'V_rollmin_F_NDMI_kobs14',
      'A_d_LST_modis_kobs7',
      'J_bio_bio14',
      'V_rollmax_s2_b11_kobs14',
      'C_lag_G_API_kobs6',
      'C_lag_G_API_kobs30',
      'C_lag_s2_b11_kobs1',
      'V_rollcv_F_NDMI_kobs14',
      'V_rollmax_s2_b12_kobs7',
      'V_rollcv_E_SAR_ratio_kobs14',
      'V_rollcv_E_SAR_ratio_kobs30',
      'A_d_E_SAR_diff_kobs30',
      'J_bio_bio05',
      'SMAP_sm_am_interp_rollstd30',
      'V_ema_s2_b12_kobs30',
      'A_d_F_NDMI_kobs7',
      'V_rollcv_s2_b12_kobs7',
      'A_grad_LST_modis_kobs7',
      'V_rollmean_s2_b11_kobs7',
      'V_rollcv_LST_modis_kobs30',
      'H_corr_LST_modis__F_NDMI_kobs7',
      'V_ema_s2_b11_kobs14',
      'lia_std_desc_deg',
      'C_lag_s2_b11_kobs5',
      'SMAP_sm_interp_rollrange30',
      'J_bio_bio10',
      'A_grad_G_API_kobs30',
      'V_rollmean_G_API_kobs7',
      'SMAP_sm_am_interp_rollstd7',
      'V_rollrng_s2_b12_kobs7',
      'C_lag_E_SAR_diff_kobs30',
      'J_sand_wfrac_b10',
      'V_rollmax_s2_b11_kobs7',
      'D_fft_ent_E_SAR_ratio_kobs30',
      'A_d_LST_modis_kobs2',
      'A_grad_F_NDMI_kobs7',
      'C_lag_G_API_kobs5',
      'A_pct_F_NDMI',
      'J_elev_m',
      'V_rollcv_F_NDMI_kobs7',
      'J_clay_wfrac_b10',
      'J_lc_code',
      'SMAP_sm_am_interp_mask',
      'SMAP_sm_pm_interp_mask',
      'SMAP_sm_interp_mask',
      'J_bio_bio11',
      'J_clay_wfrac_b0',
      'J_clay_wfrac_b100',
      'J_clay_wfrac_b200',
      'J_clay_wfrac_b30',
      'J_clay_wfrac_b60',
      'J_sand_clay_ratio_b0',
      'J_sand_wfrac_b100',
      'J_sand_wfrac_b30',
      'J_sand_wfrac_b60',
      'J_soil_texture_usda_b10',
      'J_soil_texture_usda_b100',
      'J_soil_texture_usda_b200',
      'J_soil_texture_usda_b30',
      'J_soil_texture_usda_b60',
      'K_sand_clay_ratio_b0',
      'year',
      'year_frac',
      'sin_year',
      'cos_year',
      'G_DSLR_isnan',
      'J_soil_texture_usda_b0',
      'H_corr_E_SAR_ratio__F_NDMI_kobs7',
      'V_rollcv_s2_b11_kobs7',
      'D_fft_dom_LST_modis_kobs30'],
     '125': ['latitude',
      'V_rollmin_G_API_kobs30',
      'elev',
      'V_rollmax_LST_modis_kobs30',
      'aspect',
      'V_rollmax_F_NDVI_kobs30',

## Station, month, and fit-window behavior

**Purpose.** Diagnose whether weak performance reflects compact-list selection failure, current-input limitations, low target variance, or uncertainty.

**Method.** The cell displays all-station classifications, station and month metrics, paired selected-versus-all intervals, transition-month highlights, and the fixed-2017–2019 versus expanding-window diagnostic.

**Result.** Each subgroup includes target dispersion beside prediction metrics, with zero-variance R² recorded as `NaN` and an explicit reason.

**Interpretation.** These diagnostics identify follow-up experiments but cannot prune stations, alter the selected list, or promote a different fit window.

In [3]:
stage_10 = "artifacts/development/stages/10_station_temporal_diagnostics"
show_csv(EXP_DIR, f"{stage_10}/station_sufficiency_classification.csv")
show_csv(EXP_DIR, f"{stage_10}/selected_vs_all_station_intervals.csv")
show_csv(EXP_DIR, f"{stage_10}/metrics_by_station.csv")
show_csv(EXP_DIR, f"{stage_10}/metrics_by_month.csv")
show_csv(EXP_DIR, f"{stage_10}/metrics_by_station_year.csv")
show_csv(EXP_DIR, f"{stage_10}/transition_month_highlights.csv")
show_csv(EXP_DIR, f"{stage_10}/fit_window_metrics.csv")

,station,classification,compact_R2,compact_R2_reason,best_global_R2,best_global_R2_reason,compact_RMSE,compact_MAE,all_predictor_RMSE,union_RMSE,v0_RMSE,target_count,target_range,target_variance,target_standard_deviation,classification_thresholds_data_derived
0,BeaverPass_WA_990,uncertain,0.314928,defined,0.541680,defined,0.083428,0.064552,0.055731,0.056921,0.068238,2182,0.376,0.010160,0.100796,True
1,CayusePass_WA,global_features_sufficient,0.709113,defined,0.709113,defined,0.063370,0.045527,0.065145,0.060803,0.066849,1978,0.400,0.013805,0.117496,True
2,Darrington,global_features_sufficient,0.754075,defined,0.754075,defined,0.053125,0.043572,0.055668,0.057110,0.056759,2068,0.404,0.011476,0.107126,True
3,MartenRidge_WA_999,current_input_limitation,0.400162,defined,0.400162,defined,0.094758,0.069813,0.091809,0.089453,0.097345,2144,0.343,0.014969,0.122349,True
4,Paradise_WA,global_features_sufficient,0.561742,defined,0.614105,defined,0.073891,0.053034,0.074234,0.065129,0.069336,2192,0.396,0.012458,0.111616,True
5,Quinault,uncertain,0.558195,defined,0.681330,defined,0.047690,0.038369,0.037102,0.034413,0.040503,2158,0.358,0.005148,0.071749,True
6,RainyPass_WA_711,uncertain,-2.704797,defined,-1.476884,defined,0.094620,0.070630,0.078009,0.070078,0.077367,2106,0.324,0.002417,0.049159,True
7,SourdoughGulch_WA_985,global_features_sufficient,0.512802,defined,0.512802,defined,0.070492,0.056135,0.081584,0.070709,0.076620,2192,0.321,0.010199,0.100992,True
8,Spokane,global_features_sufficient,0.754243,defined,0.832148,defined,0.052120,0.040148,0.049980,0.045049,0.043074,1878,0.336,0.011053,0.105135,True

,station,comparison,delta_rmse,ci_lower,ci_upper,bootstrap_standard_error
0,BeaverPass_WA_990,all_minus_selected,-0.027697,-0.040090,-0.018022,0.005885
1,BeaverPass_WA_990,all_minus_union,-0.001190,-0.004855,0.003117,0.001979
2,BeaverPass_WA_990,all_minus_v0,-0.012507,-0.019362,-0.003238,0.004121
3,CayusePass_WA,all_minus_selected,0.001775,0.000346,0.003331,0.000765
4,CayusePass_WA,all_minus_union,0.004342,-0.000687,0.010548,0.002959
5,CayusePass_WA,all_minus_v0,-0.001704,-0.011385,0.005720,0.004477
6,Darrington,all_minus_selected,0.002544,-0.006554,0.008628,0.003957
7,Darrington,all_minus_union,-0.001442,-0.009383,0.004378,0.003669
8,Darrington,all_minus_v0,-0.001091,-0.009076,0.005159,0.003733
9,MartenRidge_WA_999,all_minus_selected,-0.002949,-0.013357,0.010758,0.005618
10,MartenRidge_WA_999,all_minus_union,0.002355,-0.004148,0.011798,0.003800
11,MartenRidge_WA_999,all_minus_v0,-0.005536,-0.012192,0.000501,0.003456
12,Paradise_WA,all_minus_selected,0.000343,-0.001774,0.004691,0.001678
13,Paradise_WA,all_minus_union,0.009104,0.006054,0.012281,0.001660
14,Paradise_WA,all_minus_v0,0.004898,-0.003057,0.009692,0.003122
15,Quinault,all_minus_selected,-0.010588,-0.015733,-0.005618,0.002574
16,Quinault,all_minus_union,0.002689,0.001114,0.005209,0.001049
17,Quinault,all_minus_v0,-0.003400,-0.006926,0.000914,0.002029
18,RainyPass_WA_711,all_minus_selected,-0.016611,-0.023403,-0.010411,0.003261
19,RainyPass_WA_711,all_minus_union,0.007932,0.004744,0.010173,0.001437
20,RainyPass_WA_711,all_minus_v0,0.000643,-0.004810,0.004283,0.002455
21,SourdoughGulch_WA_985,all_minus_selected,0.011092,0.007828,0.015380,0.001829
22,SourdoughGulch_WA_985,all_minus_union,0.010876,0.009389,0.012493,0.000768
23,SourdoughGulch_WA_985,all_minus_v0,0.004964,-0.004465,0.015839,0.005481
24,Spokane,all_minus_selected,-0.002139,-0.005684,0.005449,0.002592
25,Spokane,all_minus_union,0.004932,0.003013,0.006877,0.001013
26,Spokane,all_minus_v0,0.006907,0.002526,0.012327,0.002485

,model,candidate,station,target_count,target_min,target_max,target_range,target_variance,target_standard_deviation,target_iqr,RMSE,R2,R2_reason,MAE,Pearson,Bias
0,V0,V0,BeaverPass_WA_990,2182,0.019,0.395,0.376,0.010160,0.100796,0.09050,0.068238,0.541680,defined,0.049094,0.759505,0.015944
1,V0,V0,CayusePass_WA,1978,0.001,0.401,0.400,0.013805,0.117496,0.18000,0.066849,0.676301,defined,0.047660,0.830248,-0.003351
2,V0,V0,Darrington,2068,0.040,0.444,0.404,0.011476,0.107126,0.15000,0.056759,0.719278,defined,0.042343,0.849375,-0.000570
3,V0,V0,MartenRidge_WA_999,2144,0.041,0.384,0.343,0.014969,0.122349,0.24650,0.097345,0.366966,defined,0.072981,0.612105,0.005995
4,V0,V0,Paradise_WA,2192,0.005,0.401,0.396,0.012458,0.111616,0.21525,0.069336,0.614105,defined,0.048817,0.819468,-0.026658
5,V0,V0,Quinault,2158,0.073,0.431,0.358,0.005148,0.071749,0.09975,0.040503,0.681330,defined,0.032274,0.882970,0.018997
6,V0,V0,RainyPass_WA_711,2106,0.001,0.325,0.324,0.002417,0.049159,0.03600,0.077367,-1.476884,defined,0.059627,0.507338,-0.047351
7,V0,V0,SourdoughGulch_WA_985,2192,0.052,0.373,0.321,0.010199,0.100992,0.18200,0.076620,0.424412,defined,0.063647,0.756387,0.037774
8,V0,V0,Spokane,1878,0.023,0.359,0.336,0.011053,0.105135,0.21450,0.043074,0.832148,defined,0.032646,0.913235,-0.000087
9,selected_2_1,selected_k__forward_time__k40,BeaverPass_WA_990,2182,0.019,0.395,0.376,0.010160,0.100796,0.09050,0.083428,0.314928,defined,0.064552,0.726951,0.044188
10,selected_2_1,selected_k__forward_time__k40,CayusePass_WA,1978,0.001,0.401,0.400,0.013805,0.117496,0.18000,0.063370,0.709113,defined,0.045527,0.845604,-0.003025
11,selected_2_1,selected_k__forward_time__k40,Darrington,2068,0.040,0.444,0.404,0.011476,0.107126,0.15000,0.053125,0.754075,defined,0.043572,0.889104,0.017375
12,selected_2_1,selected_k__forward_time__k40,MartenRidge_WA_999,2144,0.041,0.384,0.343,0.014969,0.122349,0.24650,0.094758,0.400162,defined,0.069813,0.642126,0.009388
13,selected_2_1,selected_k__forward_time__k40,Paradise_WA,2192,0.005,0.401,0.396,0.012458,0.111616,0.21525,0.073891,0.561742,defined,0.053034,0.767142,-0.017949
14,selected_2_1,selected_k__forward_time__k40,Quinault,2158,0.073,0.431,0.358,0.005148,0.071749,0.09975,0.047690,0.558195,defined,0.038369,0.895602,0.034221
15,selected_2_1,selected_k__forward_time__k40,RainyPass_WA_711,2106,0.001,0.325,0.324,0.002417,0.049159,0.03600,0.094620,-2.704797,defined,0.070630,0.484744,-0.059453
16,selected_2_1,selected_k__forward_time__k40,SourdoughGulch_WA_985,2192,0.052,0.373,0.321,0.010199,0.100992,0.18200,0.070492,0.512802,defined,0.056135,0.821164,0.040280
17,selected_2_1,selected_k__forward_time__k40,Spokane,1878,0.023,0.359,0.336,0.011053,0.105135,0.21450,0.052120,0.754243,defined,0.040148,0.886812,0.013422
18,union_2_1_v0,v0_union_selected_k__forward_time__k40,BeaverPass_WA_990,2182,0.019,0.395,0.376,0.010160,0.100796,0.09050,0.056921,0.681098,defined,0.042796,0.849628,0.020229
19,union_2_1_v0,v0_union_selected_k__forward_time__k40,CayusePass_WA,1978,0.001,0.401,0.400,0.013805,0.117496,0.18000,0.060803,0.732203,defined,0.043253,0.864550,-0.000139
20,union_2_1_v0,v0_union_selected_k__forward_time__k40,Darrington,2068,0.040,0.444,0.404,0.011476,0.107126,0.15000,0.057110,0.715793,defined,0.042985,0.846596,-0.002980
21,union_2_1_v0,v0_union_selected_k__forward_time__k40,MartenRidge_WA_999,2144,0.041,0.384,0.343,0.014969,0.122349,0.24650,0.089453,0.465445,defined,0.067761,0.684200,0.006339
22,union_2_1_v0,v0_union_selected_k__forward_time__k40,Paradise_WA,2192,0.005,0.401,0.396,0.012458,0.111616,0.21525,0.065129,0.659510,defined,0.046726,0.836849,-0.022412
23,union_2_1_v0,v0_union_selected_k__forward_time__k40,Quinault,2158,0.073,0.431,0.358,0.005148,0.071749,0.09975,0.034413,0.769949,defined,0.027502,0.928792,0.018088
24,union_2_1_v0,v0_union_selected_k__forward_time__k40,RainyPass_WA_711,2106,0.001,0.325,0.324,0.002417,0.049159,0.03600,0.070078,-1.032157,defined,0.054461,0.536632,-0.039542
25,union_2_1_v0,v0_union_selected_k__forward_time__k40,SourdoughGulch_WA_985,2192,0.052,0.373,0.321,0.010199,0.100992,0.18200,0.070709,0.509801,defined,0.057049,0.807878,0.037604
26,union_2_1_v0,v0_union_selected_k__forward_time__k40,Spokane,1878,0.023,0.359,0.336,0.011053,0.105135,0.21450,0.045049,0.816402,defined,0.034487,0.912613,0.007358
27,all_predictors,all_predictors,BeaverPass_WA_990,2182,0.019,0.395,0.376,0.010160,0.100796,0.09050,0.055731,0.694290,defined,0.042091,0.860016,0.021302
28,all_predictors,all_predictors,CayusePass_WA,1978,0.001,0.401,0.400,0.013805,0.117496,0.18000,0.065145,0.692590,defined,0.046597,0.840383,-0.012017
29,all_predictors,all_predictors,Darrington,2068,0.040,0.444,0.404,0.011476,0.107126,0.15000,0.055668,0.729963,defined,0.045872,0.894026,0.021936
30,all_predictors,all_predictors,MartenRidge_WA_999,2144,0.041,0.384,0.343,0.014969,0.122349,0.24650,0.091809,0.436923,defined,0.070910,0.665044,0.008958
31,all_predictors,all_predictors,Paradise_WA,2192,0.005,0.401,0.396,0.012458,0.111616,0.21525,0.074234,0.557665,defined,0.052522,0.787401,-0.027857
32,all_predictors,all_predictors,Quinault,2158,0.073,0.431,0.358,0.005148,0.071749,0.09975,0.037102,0.732589,defined,0.030525,0.920788,0.022043
33,all_predictors,all_predictors,RainyPass_WA_711,2106,0.001,0.325,0.324,0.002417,0.049159,0.03600,0.078009,-1.518207,defined,0.059905,0.539357,-0.047833
34,all_predictors,all_predictors,SourdoughGulch_WA_985,2192,0.052,0.373,0.321,0.010199,0.100992,0.18200,0.081584,0.347409,defined,0.064430,0.764779,0.049176
35,all_predictors,all_predictors,Spokane,1878,0.023,0.359,0.336,0.011053,0.105135,0.21450,0.049980,0.774004,defined,0.039478,0.899703,0.011491

,model,candidate,month,target_count,target_min,target_max,target_range,target_variance,target_standard_deviation,target_iqr,RMSE,R2,R2_reason,MAE,Pearson,Bias
0,V0,V0,1,1558,0.044,0.444,0.400,0.005061,0.071139,0.09775,0.059578,0.298607,defined,0.043993,0.600445,0.016300
1,V0,V0,2,1348,0.088,0.429,0.341,0.004388,0.066244,0.10100,0.056714,0.267035,defined,0.042401,0.592886,0.014920
2,V0,V0,3,1666,0.130,0.397,0.267,0.004096,0.063999,0.09500,0.053002,0.314127,defined,0.039730,0.622689,0.014934
3,V0,V0,4,1620,0.130,0.396,0.266,0.004172,0.064593,0.09800,0.060233,0.130442,defined,0.045338,0.533098,0.018137
4,V0,V0,5,1674,0.117,0.395,0.278,0.005353,0.073162,0.11600,0.068959,0.111618,defined,0.052160,0.579316,0.026529
5,V0,V0,6,1596,0.049,0.401,0.352,0.007412,0.086094,0.13700,0.066799,0.398003,defined,0.050356,0.689837,0.021257
6,V0,V0,7,1670,0.024,0.399,0.375,0.009283,0.096349,0.14350,0.063028,0.572074,defined,0.048668,0.760023,-0.003945
7,V0,V0,8,1610,0.003,0.232,0.229,0.001994,0.044651,0.06700,0.051981,-0.355241,defined,0.038142,0.513202,-0.017342
8,V0,V0,9,1482,0.001,0.334,0.333,0.006093,0.078059,0.07400,0.059406,0.420821,defined,0.045126,0.723979,-0.021777
9,V0,V0,10,1554,0.001,0.370,0.369,0.011309,0.106345,0.19500,0.084767,0.364634,defined,0.061853,0.637515,-0.019196
10,V0,V0,11,1556,0.001,0.392,0.391,0.009915,0.099575,0.15100,0.090915,0.166378,defined,0.068016,0.483418,-0.025359
11,V0,V0,12,1564,0.011,0.392,0.381,0.009577,0.097864,0.14400,0.092103,0.114276,defined,0.066464,0.422674,-0.023478
12,selected_2_1,selected_k__forward_time__k40,1,1558,0.044,0.444,0.400,0.005061,0.071139,0.09775,0.074929,-0.109381,defined,0.056095,0.383464,0.023914
13,selected_2_1,selected_k__forward_time__k40,2,1348,0.088,0.429,0.341,0.004388,0.066244,0.10100,0.070903,-0.145597,defined,0.053120,0.385048,0.021127
14,selected_2_1,selected_k__forward_time__k40,3,1666,0.130,0.397,0.267,0.004096,0.063999,0.09500,0.067872,-0.124706,defined,0.050578,0.421835,0.023352
15,selected_2_1,selected_k__forward_time__k40,4,1620,0.130,0.396,0.266,0.004172,0.064593,0.09800,0.067930,-0.105982,defined,0.049802,0.445205,0.019922
16,selected_2_1,selected_k__forward_time__k40,5,1674,0.117,0.395,0.278,0.005353,0.073162,0.11600,0.070470,0.072235,defined,0.053203,0.564082,0.025148
17,selected_2_1,selected_k__forward_time__k40,6,1596,0.049,0.401,0.352,0.007412,0.086094,0.13700,0.070327,0.332735,defined,0.053605,0.668465,0.025980
18,selected_2_1,selected_k__forward_time__k40,7,1670,0.024,0.399,0.375,0.009283,0.096349,0.14350,0.059262,0.621681,defined,0.043238,0.791467,0.005671
19,selected_2_1,selected_k__forward_time__k40,8,1610,0.003,0.232,0.229,0.001994,0.044651,0.06700,0.044939,-0.012917,defined,0.034861,0.490155,-0.008800
20,selected_2_1,selected_k__forward_time__k40,9,1482,0.001,0.334,0.333,0.006093,0.078059,0.07400,0.050918,0.574503,defined,0.040593,0.784607,-0.015788
21,selected_2_1,selected_k__forward_time__k40,10,1554,0.001,0.370,0.369,0.011309,0.106345,0.19500,0.079120,0.446473,defined,0.061792,0.668367,-0.001110
22,selected_2_1,selected_k__forward_time__k40,11,1556,0.001,0.392,0.391,0.009915,0.099575,0.15100,0.094518,0.099001,defined,0.072311,0.368504,-0.007017
23,selected_2_1,selected_k__forward_time__k40,12,1564,0.011,0.392,0.381,0.009577,0.097864,0.14400,0.102633,-0.099823,defined,0.077583,0.202820,-0.006679
24,union_2_1_v0,v0_union_selected_k__forward_time__k40,1,1558,0.044,0.444,0.400,0.005061,0.071139,0.09775,0.056756,0.363478,defined,0.042367,0.650106,0.016683
25,union_2_1_v0,v0_union_selected_k__forward_time__k40,2,1348,0.088,0.429,0.341,0.004388,0.066244,0.10100,0.050131,0.427305,defined,0.038396,0.698231,0.015065
26,union_2_1_v0,v0_union_selected_k__forward_time__k40,3,1666,0.130,0.397,0.267,0.004096,0.063999,0.09500,0.048694,0.421096,defined,0.037161,0.699222,0.015848
27,union_2_1_v0,v0_union_selected_k__forward_time__k40,4,1620,0.130,0.396,0.266,0.004172,0.064593,0.09800,0.055129,0.271583,defined,0.041691,0.610709,0.013270
28,union_2_1_v0,v0_union_selected_k__forward_time__k40,5,1674,0.117,0.395,0.278,0.005353,0.073162,0.11600,0.061763,0.287355,defined,0.047899,0.644456,0.018111
29,union_2_1_v0,v0_union_selected_k__forward_time__k40,6,1596,0.049,0.401,0.352,0.007412,0.086094,0.13700,0.064948,0.430907,defined,0.049404,0.700885,0.018966
30,union_2_1_v0,v0_union_selected_k__forward_time__k40,7,1670,0.024,0.399,0.375,0.009283,0.096349,0.14350,0.061855,0.587855,defined,0.046063,0.769205,0.001936
31,union_2_1_v0,v0_union_selected_k__forward_time__k40,8,1610,0.003,0.232,0.229,0.001994,0.044651,0.06700,0.049145,-0.211415,defined,0.036843,0.473339,-0.011663
32,union_2_1_v0,v0_union_selected_k__forward_time__k40,9,1482,0.001,0.334,0.333,0.006093,0.078059,0.07400,0.053789,0.525173,defined,0.041846,0.764693,-0.018352
33,union_2_1_v0,v0_union_selected_k__forward_time__k40,10,1554,0.001,0.370,0.369,0.011309,0.106345,0.19500,0.071630,0.546316,defined,0.054253,0.741428,-0.004444
34,union_2_1_v0,v0_union_selected_k__forward_time__k40,11,1556,0.001,0.392,0.391,0.009915,0.099575,0.15100,0.081074,0.337079,defined,0.059321,0.605271,-0.015067
35,union_2_1_v0,v0_union_selected_k__forward_time__k40,12,1564,0.011,0.392,0.381,0.009577,0.097864,0.14400,0.087903,0.193212,defined,0.062838,0.477169,-0.017598
36,all_predictors,all_predictors,1,1558,0.044,0.444,0.400,0.005061,0.071139,0.09775,0.066057,0.137776,defined,0.050213,0.519160,0.021043
37,all_predictors,all_predictors,2,1348,0.088,0.429,0.341,0.004388,0.066244,0.10100,0.061850,0.128266,defined,0.046538,0.526714,0.017985
38,all_predictors,all_predictors,3,1666,0.130,0.397,0.267,0.004096,0.063999,0.09500,0.058887,0.153367,defined,0.044203,0.548202,0.019836
39,all_predictors,all_predictors,4,1620,0.130,0.396,0.266,0.004172,0.064593,0.09800,0.060508,0.122501,defined,0.045688,0.536238,0.016522

,model,candidate,station,outer_origin,target_count,target_min,target_max,target_range,target_variance,target_standard_deviation,target_iqr,RMSE,R2,R2_reason,MAE,Pearson,Bias
0,V0,V0,BeaverPass_WA_990,2020,730,0.039,0.395,0.356,0.009338,0.096631,0.05300,0.065182,0.544985,defined,0.047796,0.839535,0.038378
1,V0,V0,BeaverPass_WA_990,2021,722,0.079,0.387,0.308,0.004534,0.067339,0.03600,0.061143,0.175537,defined,0.046805,0.813116,0.041706
2,V0,V0,BeaverPass_WA_990,2022,730,0.019,0.367,0.348,0.014338,0.119740,0.15100,0.077279,0.583476,defined,0.052655,0.809210,-0.031971
3,V0,V0,CayusePass_WA,2020,722,0.001,0.392,0.391,0.012386,0.111293,0.19500,0.061172,0.697890,defined,0.042199,0.844705,-0.010594
4,V0,V0,CayusePass_WA,2021,728,0.006,0.401,0.395,0.013806,0.117500,0.16875,0.052891,0.797375,defined,0.040229,0.903003,0.008325
5,V0,V0,CayusePass_WA,2022,528,0.001,0.399,0.398,0.014303,0.119593,0.13225,0.088130,0.456962,defined,0.065373,0.713264,-0.009545
6,V0,V0,Darrington,2020,726,0.050,0.364,0.314,0.007883,0.088785,0.09500,0.058722,0.562558,defined,0.042302,0.752353,-0.004426
7,V0,V0,Darrington,2021,670,0.051,0.381,0.330,0.010521,0.102572,0.17525,0.055482,0.707411,defined,0.039773,0.843302,0.004020
8,V0,V0,Darrington,2022,672,0.040,0.444,0.404,0.016208,0.127312,0.27000,0.055852,0.807539,defined,0.044948,0.902725,-0.000978
9,V0,V0,MartenRidge_WA_999,2020,718,0.044,0.384,0.340,0.010076,0.100380,0.12300,0.082861,0.318589,defined,0.068224,0.581569,0.000768
10,V0,V0,MartenRidge_WA_999,2021,718,0.068,0.370,0.302,0.011434,0.106928,0.03950,0.085709,0.357505,defined,0.069276,0.757201,0.049506
11,V0,V0,MartenRidge_WA_999,2022,708,0.041,0.373,0.332,0.020895,0.144551,0.29700,0.119512,0.316440,defined,0.081563,0.610341,-0.032829
12,V0,V0,Paradise_WA,2020,732,0.013,0.401,0.388,0.014664,0.121095,0.21200,0.071459,0.651777,defined,0.053553,0.819598,-0.002675
13,V0,V0,Paradise_WA,2021,730,0.010,0.388,0.378,0.009813,0.099061,0.15400,0.053913,0.703808,defined,0.042060,0.898296,-0.031642
14,V0,V0,Paradise_WA,2022,730,0.005,0.364,0.359,0.011365,0.106606,0.20600,0.080055,0.436088,defined,0.050823,0.797032,-0.045723
15,V0,V0,Quinault,2020,732,0.098,0.361,0.263,0.003486,0.059041,0.08100,0.045821,0.397682,defined,0.037314,0.810207,0.029626
16,V0,V0,Quinault,2021,702,0.089,0.431,0.342,0.005812,0.076238,0.10375,0.036154,0.775111,defined,0.027548,0.903203,0.013112
17,V0,V0,Quinault,2022,724,0.073,0.380,0.307,0.006133,0.078312,0.14600,0.038724,0.755489,defined,0.031761,0.920968,0.013956
18,V0,V0,RainyPass_WA_711,2020,704,0.001,0.267,0.266,0.002018,0.044924,0.02650,0.070107,-1.435367,defined,0.054493,0.656757,-0.048185
19,V0,V0,RainyPass_WA_711,2021,730,0.021,0.267,0.246,0.001234,0.035133,0.02800,0.072817,-3.295790,defined,0.054574,0.344713,-0.039270
20,V0,V0,RainyPass_WA_711,2022,672,0.001,0.325,0.324,0.004077,0.063852,0.08825,0.088597,-0.925256,defined,0.070494,0.518144,-0.055255
21,V0,V0,SourdoughGulch_WA_985,2020,732,0.067,0.369,0.302,0.007614,0.087259,0.10900,0.084550,0.061140,defined,0.071998,0.836239,0.069706
22,V0,V0,SourdoughGulch_WA_985,2021,730,0.052,0.361,0.309,0.012042,0.109734,0.23400,0.073553,0.550713,defined,0.062835,0.785721,0.008035
23,V0,V0,SourdoughGulch_WA_985,2022,730,0.059,0.373,0.314,0.009263,0.096242,0.16700,0.071060,0.454846,defined,0.056085,0.773872,0.035495
24,V0,V0,Spokane,2020,664,0.023,0.342,0.319,0.010314,0.101558,0.20000,0.050431,0.753412,defined,0.039126,0.874120,0.010482
25,V0,V0,Spokane,2021,660,0.025,0.336,0.311,0.010437,0.102162,0.19600,0.043026,0.822631,defined,0.033137,0.912345,-0.002672
26,V0,V0,Spokane,2022,554,0.028,0.359,0.331,0.012303,0.110920,0.22200,0.032182,0.915821,defined,0.024295,0.962379,-0.009675
27,selected_2_1,selected_k__forward_time__k40,BeaverPass_WA_990,2020,730,0.039,0.395,0.356,0.009338,0.096631,0.05300,0.074103,0.411912,defined,0.056884,0.801953,0.046214
28,selected_2_1,selected_k__forward_time__k40,BeaverPass_WA_990,2021,722,0.079,0.387,0.308,0.004534,0.067339,0.03600,0.098480,-1.138790,defined,0.077417,0.675434,0.074782
29,selected_2_1,selected_k__forward_time__k40,BeaverPass_WA_990,2022,730,0.019,0.367,0.348,0.014338,0.119740,0.15100,0.075637,0.600983,defined,0.059495,0.781594,0.011904
30,selected_2_1,selected_k__forward_time__k40,CayusePass_WA,2020,722,0.001,0.392,0.391,0.012386,0.111293,0.19500,0.065873,0.649672,defined,0.048121,0.832479,-0.022966
31,selected_2_1,selected_k__forward_time__k40,CayusePass_WA,2021,728,0.006,0.401,0.395,0.013806,0.117500,0.16875,0.051896,0.804929,defined,0.038035,0.923108,0.019211
32,selected_2_1,selected_k__forward_time__k40,CayusePass_WA,2022,528,0.001,0.399,0.398,0.014303,0.119593,0.13225,0.073464,0.622652,defined,0.052311,0.816083,-0.006416
33,selected_2_1,selected_k__forward_time__k40,Darrington,2020,726,0.050,0.364,0.314,0.007883,0.088785,0.09500,0.055768,0.605455,defined,0.045628,0.857857,0.031355
34,selected_2_1,selected_k__forward_time__k40,Darrington,2021,670,0.051,0.381,0.330,0.010521,0.102572,0.17525,0.051507,0.747836,defined,0.042833,0.909640,0.021745
35,selected_2_1,selected_k__forward_time__k40,Darrington,2022,672,0.040,0.444,0.404,0.016208,0.127312,0.27000,0.051768,0.834657,defined,0.042088,0.919029,-0.002085
36,selected_2_1,selected_k__forward_time__k40,MartenRidge_WA_999,2020,718,0.044,0.384,0.340,0.010076,0.100380,0.12300,0.093857,0.125752,defined,0.075332,0.548733,0.029058
37,selected_2_1,selected_k__forward_time__k40,MartenRidge_WA_999,2021,718,0.068,0.370,0.302,0.011434,0.106928,0.03950,0.075369,0.503185,defined,0.060808,0.822497,0.043799
38,selected_2_1,selected_k__forward_time__k40,MartenRidge_WA_999,2022,708,0.041,0.373,0.332,0.020895,0.144551,0.29700,0.111789,0.401921,defined,0.073348,0.708830,-0.045457
39,selected_2_1,selected_k__forward_time__k40,Paradise_WA,2020,732,0.013,0.401,0.388,0.014664,0.121095,0.21200,0.077093,0.594706,defined,0.060034,0.784727,0.011457

,model,candidate,month,target_count,target_min,target_max,target_range,target_variance,target_standard_deviation,target_iqr,RMSE,R2,R2_reason,MAE,Pearson,Bias,transition_month,high_error_month
0,V0,V0,11,1556,0.001,0.392,0.391,0.009915,0.099575,0.151,0.090915,0.166378,defined,0.068016,0.483418,-0.025359,True,True
1,selected_2_1,selected_k__forward_time__k40,11,1556,0.001,0.392,0.391,0.009915,0.099575,0.151,0.094518,0.099001,defined,0.072311,0.368504,-0.007017,True,True
2,union_2_1_v0,v0_union_selected_k__forward_time__k40,11,1556,0.001,0.392,0.391,0.009915,0.099575,0.151,0.081074,0.337079,defined,0.059321,0.605271,-0.015067,True,True
3,all_predictors,all_predictors,11,1556,0.001,0.392,0.391,0.009915,0.099575,0.151,0.088593,0.208419,defined,0.067502,0.467675,-0.008619,True,True

,model,candidate,target_count,target_min,target_max,target_range,target_variance,target_standard_deviation,target_iqr,RMSE,R2,R2_reason,MAE,Pearson,Bias,station_macro_RMSE,worst_station_RMSE,p90_station_year_RMSE,p90_month_RMSE
0,V0__expanding,V0__expanding,9449,0.001,0.444,0.443,0.012126,0.110118,0.186,0.056341,0.738225,defined,0.037399,0.859278,-0.001048,0.053602,0.088255,0.071435,0.085585
1,V0__fixed_2017_2019,V0__fixed_2017_2019,9449,0.001,0.444,0.443,0.012126,0.110118,0.186,0.059697,0.706104,defined,0.040831,0.842220,0.004883,0.057504,0.090716,0.074750,0.087157
2,challenger__expanding,challenger__expanding,9449,0.001,0.444,0.443,0.012126,0.110118,0.186,0.050900,0.786346,defined,0.034145,0.886813,-0.000078,0.048168,0.081328,0.070285,0.077462
3,challenger__fixed_2017_2019,challenger__fixed_2017_2019,9449,0.001,0.444,0.443,0.012126,0.110118,0.186,0.054952,0.750969,defined,0.037595,0.868200,0.005613,0.053107,0.081074,0.072439,0.080748

## Input sufficiency and correlated substitutes

**Purpose.** Separate distribution and missingness problems from instability among highly correlated selected predictors.

**Method.** The saved station-input diagnostics, residual distributions, climatology, correlation components, joint component permutations, and post-selection family summary are displayed directly.

**Result.** The complete run exposes feature missingness, out-of-range rates, development-population distance, residual shape, and component-level importance at the configured Spearman threshold.

**Interpretation.** Correlation and family labels explain a frozen selection result; they never revise that result or silently add new sensor inputs.

In [4]:
show_csv(EXP_DIR, f"{stage_10}/station_input_diagnostics.csv")
show_csv(EXP_DIR, f"{stage_10}/station_month_residual_distribution.csv")
show_csv(EXP_DIR, f"{stage_10}/station_month_climatology.csv")
show_json(EXP_DIR, f"{stage_10}/correlation_components.json")
show_csv(EXP_DIR, f"{stage_10}/correlation_joint_permutation.csv")
show_csv(EXP_DIR, f"{stage_10}/feature_family_summary.csv")

,station,outer_origin,feature,missing_rate,out_of_training_range_rate,standardized_mean_distance,normalized_quantile_distance,training_range_lower_quantile,training_range_upper_quantile
0,BeaverPass_WA_990,2020,A_d_E_SAR_diff_kobs30,0.0,0.000000,0.027335,2.438620,0.01,0.99
1,BeaverPass_WA_990,2020,A_d_LST_modis_kobs30,0.0,0.030137,0.029099,0.512814,0.01,0.99
2,BeaverPass_WA_990,2020,A_d_SMAP_sm_interp_kobs30,0.0,0.043836,0.018942,0.495876,0.01,0.99
3,BeaverPass_WA_990,2020,A_d_s2_b11_kobs30,0.0,0.000000,0.034048,3.327275,0.01,0.99
4,BeaverPass_WA_990,2020,A_grad_E_SAR_diff_kobs30,0.0,0.000000,0.027335,2.438620,0.01,0.99
5,BeaverPass_WA_990,2020,A_grad_LST_modis_kobs30,0.0,0.030137,0.029099,0.512814,0.01,0.99
6,BeaverPass_WA_990,2020,A_grad_SMAP_sm_interp_kobs30,0.0,0.043836,0.018942,0.495876,0.01,0.99
7,BeaverPass_WA_990,2020,A_grad_s2_b11_kobs30,0.0,0.000000,0.034048,3.327275,0.01,0.99
8,BeaverPass_WA_990,2020,C_lag_F_NDVI_kobs30,0.0,0.095890,0.481395,0.199480,0.01,0.99
9,BeaverPass_WA_990,2020,D_sa_F_NDMI,0.0,0.002740,0.867275,0.691266,0.01,0.99
10,BeaverPass_WA_990,2020,D_sa_LST_modis,0.0,0.046575,0.787372,0.725789,0.01,0.99
11,BeaverPass_WA_990,2020,D_z_E_SAR_ratio,0.0,0.000000,0.032449,1.240928,0.01,0.99
12,BeaverPass_WA_990,2020,E_SAR_ratio,0.0,0.000000,0.036489,0.856357,0.01,0.99
13,BeaverPass_WA_990,2020,F_MSI,0.0,0.000000,0.767790,1.009552,0.01,0.99
14,BeaverPass_WA_990,2020,J_aspect_deg,0.0,0.000000,1.578683,1.263736,0.01,0.99
15,BeaverPass_WA_990,2020,J_bio_bio15,0.0,0.000000,0.175398,1.750000,0.01,0.99
16,BeaverPass_WA_990,2020,K_aspect_cos,0.0,0.000000,1.590784,1.261895,0.01,0.99
17,BeaverPass_WA_990,2020,K_aspect_sin,0.0,0.000000,1.162267,0.651832,0.01,0.99
18,BeaverPass_WA_990,2020,SMAP_sm_pm_interp_lag30,0.0,0.000000,0.194575,0.456450,0.01,0.99
19,BeaverPass_WA_990,2020,SMAP_sm_pm_interp_rollrange30,0.0,0.019178,0.176620,0.416031,0.01,0.99
20,BeaverPass_WA_990,2020,SMAP_x_year,0.0,0.241096,1.784316,0.858020,0.01,0.99
21,BeaverPass_WA_990,2020,V_ema_F_NDVI_kobs30,0.0,0.093151,0.474083,0.182598,0.01,0.99
22,BeaverPass_WA_990,2020,V_ema_LST_modis_kobs30,0.0,0.000000,0.459588,0.466081,0.01,0.99
23,BeaverPass_WA_990,2020,V_rollmax_G_API_kobs7,0.0,0.000000,0.083081,0.486335,0.01,0.99
24,BeaverPass_WA_990,2020,V_rollmean_F_NDMI_kobs30,0.0,0.000000,0.852938,0.893875,0.01,0.99
25,BeaverPass_WA_990,2020,V_rollmin_s2_b12_kobs30,0.0,0.000000,0.919104,1.436284,0.01,0.99
26,BeaverPass_WA_990,2020,V_rollrng_F_NDVI_kobs30,0.0,0.043836,0.303288,0.172815,0.01,0.99
27,BeaverPass_WA_990,2020,aspect,0.0,0.000000,0.834350,1.739007,0.01,0.99
28,BeaverPass_WA_990,2020,latitude,0.0,0.000000,1.230201,0.791997,0.01,0.99
29,BeaverPass_WA_990,2020,lia_std_asc_deg,0.0,0.000000,0.098318,4.018279,0.01,0.99
30,BeaverPass_WA_990,2020,s2_b8,0.0,0.000000,0.484971,1.344381,0.01,0.99
31,BeaverPass_WA_990,2020,slope,0.0,0.000000,0.271151,1.685950,0.01,0.99
32,BeaverPass_WA_990,2020,A_grad_LST_modis_kobs14,0.0,0.038356,0.019398,0.885853,0.01,0.99
33,BeaverPass_WA_990,2020,V_rollmax_E_SAR_ratio_kobs7,0.0,0.000000,0.001509,0.808997,0.01,0.99
34,BeaverPass_WA_990,2020,A_d_LST_modis_kobs14,0.0,0.038356,0.019398,0.885853,0.01,0.99
35,BeaverPass_WA_990,2020,J_clay_wfrac_b100,0.0,0.000000,1.177740,1.055556,0.01,0.99
36,BeaverPass_WA_990,2020,V_ema_G_API_kobs30,0.0,0.000000,0.088414,0.526269,0.01,0.99
37,BeaverPass_WA_990,2020,V_rollmin_G_API_kobs14,0.0,0.000000,0.102420,0.530989,0.01,0.99
38,BeaverPass_WA_990,2020,V_rollrng_LST_modis_kobs30,0.0,0.076712,0.037402,0.074782,0.01,0.99
39,BeaverPass_WA_990,2020,V_rollrng_G_API_kobs30,0.0,0.000000,0.035215,0.592946,0.01,0.99

,model,candidate,station,month,count,residual_mean,residual_std,residual_q05,residual_q25,residual_median,residual_q75,residual_q95
0,V0,V0,BeaverPass_WA_990,1,186,0.028324,0.036086,-0.014972,-0.000622,0.015364,0.062670,0.093508
1,V0,V0,BeaverPass_WA_990,2,170,0.021489,0.039491,-0.027783,-0.010346,0.006336,0.069500,0.080652
2,V0,V0,BeaverPass_WA_990,3,186,0.020296,0.036606,-0.024731,-0.006128,0.006927,0.046982,0.084306
3,V0,V0,BeaverPass_WA_990,4,180,0.036774,0.042732,-0.007713,0.005181,0.015951,0.079479,0.120077
4,V0,V0,BeaverPass_WA_990,5,186,0.046608,0.057067,-0.012162,0.001417,0.018792,0.109800,0.140988
5,V0,V0,BeaverPass_WA_990,6,180,0.048024,0.059030,-0.017749,-0.004559,0.024705,0.108154,0.144921
6,V0,V0,BeaverPass_WA_990,7,186,0.057550,0.056443,-0.018065,0.001529,0.054321,0.108041,0.149473
7,V0,V0,BeaverPass_WA_990,8,186,0.013435,0.056467,-0.072390,-0.027310,0.001701,0.055285,0.116061
8,V0,V0,BeaverPass_WA_990,9,172,-0.015079,0.054157,-0.116181,-0.034490,-0.016842,-0.000676,0.075590
9,V0,V0,BeaverPass_WA_990,10,186,-0.039377,0.106053,-0.223610,-0.160147,0.005048,0.044214,0.072422
10,V0,V0,BeaverPass_WA_990,11,178,-0.019210,0.073255,-0.135817,-0.094659,0.001231,0.034765,0.078454
11,V0,V0,BeaverPass_WA_990,12,186,-0.009173,0.062304,-0.100830,-0.088373,-0.001871,0.052148,0.073714
12,V0,V0,CayusePass_WA,1,186,0.020416,0.044516,-0.032946,-0.011282,0.004468,0.047292,0.103487
13,V0,V0,CayusePass_WA,2,170,0.011035,0.031976,-0.028652,-0.017070,0.002384,0.035708,0.067587
14,V0,V0,CayusePass_WA,3,186,0.011970,0.038838,-0.036256,-0.014851,0.004832,0.028244,0.086548
15,V0,V0,CayusePass_WA,4,180,0.029135,0.026338,-0.017452,0.009717,0.033445,0.049016,0.067741
16,V0,V0,CayusePass_WA,5,186,0.041850,0.029634,0.002243,0.021008,0.038784,0.054934,0.112934
17,V0,V0,CayusePass_WA,6,180,0.031532,0.035844,-0.020996,0.010536,0.030649,0.049275,0.098379
18,V0,V0,CayusePass_WA,7,186,0.003830,0.049792,-0.079968,-0.032072,0.002188,0.044097,0.077367
19,V0,V0,CayusePass_WA,8,128,-0.012397,0.017099,-0.035250,-0.024112,-0.016998,-0.000497,0.014072
20,V0,V0,CayusePass_WA,9,110,-0.039285,0.037475,-0.109958,-0.071698,-0.025417,-0.015506,0.003583
21,V0,V0,CayusePass_WA,10,124,-0.067743,0.103248,-0.195186,-0.146097,-0.110650,-0.002233,0.124274
22,V0,V0,CayusePass_WA,11,156,-0.056392,0.082119,-0.154027,-0.136926,-0.068566,-0.013717,0.096873
23,V0,V0,CayusePass_WA,12,186,-0.058274,0.099388,-0.223546,-0.141303,-0.027757,0.009112,0.074469
24,V0,V0,Darrington,1,134,0.013896,0.026803,-0.025947,-0.006056,0.012812,0.031674,0.061413
25,V0,V0,Darrington,2,102,0.010945,0.029442,-0.032007,-0.017686,0.010532,0.033960,0.059971
26,V0,V0,Darrington,3,186,0.014957,0.031755,-0.039004,-0.005613,0.016051,0.036549,0.062000
27,V0,V0,Darrington,4,180,0.009420,0.040701,-0.056223,-0.016072,0.009174,0.040547,0.072193
28,V0,V0,Darrington,5,186,0.041498,0.051546,-0.043327,0.001988,0.048139,0.077203,0.118914
29,V0,V0,Darrington,6,180,0.024213,0.059229,-0.093705,-0.007767,0.029145,0.064342,0.105300
30,V0,V0,Darrington,7,186,-0.041035,0.074006,-0.155647,-0.112995,-0.024118,0.010368,0.067648
31,V0,V0,Darrington,8,186,-0.049653,0.064939,-0.173492,-0.100966,-0.022308,-0.003543,0.024558
32,V0,V0,Darrington,9,180,-0.036630,0.060297,-0.163013,-0.064262,-0.029191,-0.002054,0.055112
33,V0,V0,Darrington,10,184,0.011083,0.040293,-0.048633,-0.014411,0.007423,0.034285,0.084088
34,V0,V0,Darrington,11,178,0.006364,0.041547,-0.063929,-0.027079,0.016699,0.038978,0.065831
35,V0,V0,Darrington,12,186,-0.002267,0.037788,-0.063354,-0.039257,0.005769,0.025686,0.049993
36,V0,V0,MartenRidge_WA_999,1,174,0.037042,0.085043,-0.152625,0.004096,0.027630,0.105962,0.122262
37,V0,V0,MartenRidge_WA_999,2,170,0.035003,0.072004,-0.085928,-0.002508,0.031567,0.095653,0.133741
38,V0,V0,MartenRidge_WA_999,3,186,0.039614,0.056966,-0.053797,-0.001922,0.040843,0.084245,0.117576
39,V0,V0,MartenRidge_WA_999,4,180,0.033247,0.067379,-0.078930,0.001184,0.028072,0.083528,0.137994

               station  month  count      mean       std    min  median    max
0    BeaverPass_WA_990      1    186  0.330672  0.019453  0.300  0.3250  0.375
1    BeaverPass_WA_990      2    169  0.334101  0.017563  0.311  0.3280  0.380
2    BeaverPass_WA_990      3    186  0.336108  0.021036  0.314  0.3290  0.397
3    BeaverPass_WA_990      4    180  0.359089  0.020250  0.329  0.3585  0.401
4    BeaverPass_WA_990      5    186  0.378559  0.017224  0.344  0.3800  0.404
5    BeaverPass_WA_990      6    180  0.361750  0.026131  0.285  0.3630  0.403
6    BeaverPass_WA_990      7    186  0.284790  0.057992  0.079  0.3015  0.374
7    BeaverPass_WA_990      8    186  0.119597  0.066651  0.019  0.1135  0.264
8    BeaverPass_WA_990      9    176  0.134892  0.113088  0.007  0.1025  0.336
9    BeaverPass_WA_990     10    185  0.254573  0.103566  0.019  0.3030  0.352
10   BeaverPass_WA_990     11    179  0.295620  0.046588  0.171  0.3080  0.387
11   BeaverPass_WA_990     12    186  0.284769  0.063435  0.045  0.3120  0.357
12       CayusePass_WA      1    186  0.233183  0.048289  0.169  0.2270  0.398
13       CayusePass_WA      2    169  0.239905  0.040105  0.185  0.2280  0.371
14       CayusePass_WA      3    186  0.237043  0.045310  0.183  0.2210  0.397
15       CayusePass_WA      4    180  0.272244  0.028989  0.195  0.2730  0.340
16       CayusePass_WA      5    186  0.313538  0.026843  0.240  0.3125  0.390
17       CayusePass_WA      6    180  0.331483  0.060136  0.146  0.3420  0.401
18       CayusePass_WA      7    186  0.145785  0.099058  0.014  0.1315  0.399
19       CayusePass_WA      8    150  0.023593  0.015184  0.001  0.0190  0.081
20       CayusePass_WA      9    120  0.030492  0.038992  0.001  0.0120  0.177
21       CayusePass_WA     10    145  0.117290  0.091793  0.001  0.0930  0.370
22       CayusePass_WA     11    168  0.163393  0.092347  0.001  0.1555  0.392
23       CayusePass_WA     12    186  0.184710  0.079318  0.011  0.1955  0.392
24          Darrington      1    154  0.323396  0.047862  0.244  0.3150  0.444
25          Darrington      2     84  0.320048  0.033170  0.252  0.3210  0.409
26          Darrington      3    165  0.316442  0.044122  0.229  0.3200  0.407
27          Darrington      4    180  0.297600  0.048705  0.192  0.3020  0.396
28          Darrington      5    186  0.245962  0.082221  0.078  0.2530  0.380
29          Darrington      6    180  0.188617  0.093394  0.069  0.1745  0.372
30          Darrington      7    186  0.103812  0.056525  0.034  0.0880  0.255
31          Darrington      8    186  0.062903  0.030680  0.023  0.0585  0.131
32          Darrington      9    180  0.116278  0.082448  0.022  0.0825  0.303
33          Darrington     10    182  0.230863  0.082934  0.040  0.2485  0.356
34          Darrington     11    179  0.290810  0.039043  0.227  0.2910  0.375
35          Darrington     12    186  0.299984  0.037184  0.236  0.2975  0.381
36  MartenRidge_WA_999      1    180  0.347350  0.050307  0.044  0.3585  0.389
37  MartenRidge_WA_999      2    169  0.342036  0.040473  0.088  0.3520  0.393
38  MartenRidge_WA_999      3    186  0.347720  0.025842  0.281  0.3500  0.393
39  MartenRidge_WA_999      4    180  0.353711  0.034305  0.267  0.3625  0.392

{'threshold': 0.95,
 'training_years': [2017, 2018, 2019, 2020, 2021],
 'components': [['A_d_E_SAR_diff_kobs30', 'A_grad_E_SAR_diff_kobs30'],
  ['A_d_LST_modis_kobs30', 'A_grad_LST_modis_kobs30'],
  ['A_d_SMAP_sm_interp_kobs30', 'A_grad_SMAP_sm_interp_kobs30'],
  ['A_d_s2_b11_kobs30', 'A_grad_s2_b11_kobs30'],
  ['E_SAR_ratio', 'V_rollmax_E_SAR_ratio_kobs7'],
  ['J_aspect_deg', 'K_aspect_sin'],
  ['V_ema_LST_modis_kobs30',
   'V_rollmean_LST_modis_kobs30',
   'V_rollmax_LST_modis_kobs30',
   'V_rollmin_LST_modis_kobs30'],
  ['V_rollmax_G_API_kobs7',
   'V_ema_G_API_kobs30',
   'V_rollmin_G_API_kobs14',
   'V_rollrng_G_API_kobs30',
   'V_rollmax_G_API_kobs30',
   'V_rollmin_G_API_kobs30',
   'C_lag_G_API_kobs1',
   'G_API',
   'V_ema_G_API_kobs14',
   'V_rollmean_G_API_kobs30',
   'V_ema_G_API_kobs7',
   'V_rollmean_G_API_kobs14',
   'V_rollmax_G_API_kobs14'],
  ['A_grad_LST_modis_kobs14', 'A_d_LST_modis_kobs14'],
  ['SMAP_sm_pm_interp_rollmean30',
   'V_ema_SMAP_sm_interp_kobs30',
   'V_rollmin_SMAP_sm_interp_kobs7']],
 'diagnostic_only': True}

,component_id,features,active_features,component_size,baseline_rmse,joint_permutation_rmse,importance_delta_rmse,diagnostic_only
0,0,A_d_E_SAR_diff_kobs30|A_grad_E_SAR_diff_kobs30,A_d_E_SAR_diff_kobs30|A_grad_E_SAR_diff_kobs30,2,0.062138,0.062095,-0.000043,True
1,1,A_d_LST_modis_kobs30|A_grad_LST_modis_kobs30,A_d_LST_modis_kobs30|A_grad_LST_modis_kobs30,2,0.062138,0.062440,0.000302,True
2,2,A_d_SMAP_sm_interp_kobs30|A_grad_SMAP_sm_inter...,A_d_SMAP_sm_interp_kobs30|A_grad_SMAP_sm_inter...,2,0.062138,0.062022,-0.000116,True
3,3,A_d_s2_b11_kobs30|A_grad_s2_b11_kobs30,A_d_s2_b11_kobs30|A_grad_s2_b11_kobs30,2,0.062138,0.062148,0.000010,True
4,4,E_SAR_ratio|V_rollmax_E_SAR_ratio_kobs7,E_SAR_ratio|V_rollmax_E_SAR_ratio_kobs7,2,0.062138,0.062400,0.000262,True
5,5,J_aspect_deg|K_aspect_sin,J_aspect_deg|K_aspect_sin,2,0.062138,0.074384,0.012246,True
6,6,V_ema_LST_modis_kobs30|V_rollmean_LST_modis_ko...,V_ema_LST_modis_kobs30|V_rollmean_LST_modis_ko...,4,0.062138,0.075243,0.013105,True
7,7,V_rollmax_G_API_kobs7|V_ema_G_API_kobs30|V_rol...,V_rollmax_G_API_kobs7|V_ema_G_API_kobs30|V_rol...,13,0.062138,0.088026,0.025888,True
8,8,A_grad_LST_modis_kobs14|A_d_LST_modis_kobs14,A_grad_LST_modis_kobs14|A_d_LST_modis_kobs14,2,0.062138,0.062124,-0.000014,True
9,9,SMAP_sm_pm_interp_rollmean30|V_ema_SMAP_sm_int...,SMAP_sm_pm_interp_rollmean30|V_ema_SMAP_sm_int...,3,0.062138,0.063710,0.001573,True

       family  feature_count  first_position
0           V             30              21
1           A             11               0
2           D              5               9
3        SMAP              5              18
4           C              4               8
5           J              4              14
6           G              3              55
7           K              2              16
8         lia              2              29
9          s2              2              30
10          E              1              12
11          F              1              13
12     aspect              1              27
13   latitude              1              28
14      slope              1              31
15       elev              1              51
16     precip              1              58
17        API              1              60
18  longitude              1              64
19        DOY              1              65