# Derived 8.3 Feature Selection 2.1 — Causal MoE Analysis

**Purpose.** This notebook presents the causal mixture-of-experts diagnostics required even when global feature selection fails.

**Method.** It displays the saved shared-backbone, historical-specialist, router, and regime-delta artifacts generated under the same OOF geometry as the global comparison.

**Result.** Before development execution, panels report pending files; after execution they show the complete ablation and machine-readable MoE verdict.

**Interpretation.** MoE can become the frozen benchmark challenger only after both the global gate and the stricter MoE promotion gate pass.

In [1]:
from pathlib import Path
import json

import pandas as pd
from IPython.display import display


def locate_experiment() -> Path:
    for base in (Path.cwd(), *Path.cwd().parents):
        direct = base / "experiment" / "derived_8.3-feature-selection-2.1"
        nested = base / "notebooks" / "experiment" / "derived_8.3-feature-selection-2.1"
        if direct.is_dir():
            return direct.resolve()
        if nested.is_dir():
            return nested.resolve()
    raise FileNotFoundError("Cannot locate derived_8.3-feature-selection-2.1")


def show_csv(exp_dir: Path, relative_path: str, rows: int = 50) -> None:
    path = exp_dir / relative_path
    if path.exists():
        display(pd.read_csv(path).head(rows))
    else:
        print(f"Pending artifact: {path.relative_to(exp_dir)}")


def show_json(exp_dir: Path, relative_path: str) -> None:
    path = exp_dir / relative_path
    if path.exists():
        display(json.loads(path.read_text(encoding="utf-8")))
    else:
        print(f"Pending artifact: {path.relative_to(exp_dir)}")


EXP_DIR = locate_experiment()
print(f"Experiment: {EXP_DIR}")

Experiment: /scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.1

## Shared-backbone causal matrix and router behavior

**Purpose.** Determine whether any MoE loss comes from missing global information, hard-routing/sample fragmentation, or the historical specialist-list collapse.

**Method.** The cell displays causal-ablation metrics plus target-free router population, centroid-drift, and manifest artifacts from stage 11.

**Result.** Each arm uses the same row-aligned OOF ledger, while router preprocessing is fitted only on outer-training rows and aligned only for reporting.

**Interpretation.** Comparisons among single-global and shared hard-expert arms isolate routing effects before any regime-specific features are considered.

In [2]:
stage_11 = "artifacts/development/stages/11_moe_causal_matrix"
show_csv(EXP_DIR, f"{stage_11}/causal_ablation_metrics.csv")
show_csv(EXP_DIR, f"{stage_11}/router_regime_populations.csv")
show_csv(EXP_DIR, f"{stage_11}/router_drift.csv")
show_json(EXP_DIR, f"{stage_11}/causal_matrix_manifest.json")

,candidate,beta,combined_primary_rmse,forward_time_rmse,station_time_rmse,R2,RMSE,MAE,Bias,worst_station_RMSE,p90_month_RMSE
0,eval_1_0_saved_specialists,0.0,0.067864,0.054648,0.081080,0.564215,0.072693,0.053281,-0.004181,0.102140,0.088794
1,selected_2_1_shared_hard_experts,0.0,0.067875,0.049990,0.085759,0.545195,0.074263,0.054673,0.009818,0.104288,0.095013
2,selected_2_1_single_global,0.0,0.065974,0.046312,0.085635,0.563866,0.072722,0.053812,0.008958,0.094758,0.092978
3,union_2_1_v0_shared_hard_experts,0.0,0.062356,0.049958,0.074753,0.616951,0.068153,0.049191,-0.003235,0.094872,0.086317
4,union_2_1_v0_single_global,0.0,0.058664,0.047270,0.070059,0.671622,0.063102,0.046534,0.002866,0.089453,0.080130
5,v0_shared_hard_experts,0.0,0.064573,0.052723,0.076422,0.594980,0.070080,0.051385,-0.002970,0.100151,0.091109
6,v0_single_global,0.0,0.063444,0.051871,0.075016,0.611554,0.068631,0.050190,0.000281,0.097345,0.090300

,outer_origin,year,month,station,router_regime,row_count,route_distance_mean,route_distance_std,target_standard_deviation
0,2020,2020,1,BeaverPass_WA_990,0,310,6.585168,0.269414,0.010682
1,2020,2020,1,CayusePass_WA,0,310,6.939585,0.267737,0.020039
2,2020,2020,1,Darrington,0,310,7.694122,0.586534,0.022278
3,2020,2020,1,MartenRidge_WA_999,0,250,8.692968,0.884833,0.101691
4,2020,2020,1,Paradise_WA,0,310,9.572354,0.800685,0.006776
5,2020,2020,1,Quinault,0,310,11.063427,1.539659,0.021959
6,2020,2020,1,RainyPass_WA_711,0,310,12.446369,3.081155,0.004562
7,2020,2020,1,SourdoughGulch_WA_985,0,217,9.454239,0.671531,0.015849
8,2020,2020,1,SourdoughGulch_WA_985,1,93,7.240880,1.142083,0.015899
9,2020,2020,1,Spokane,0,77,7.106920,0.272555,0.015776
10,2020,2020,1,Spokane,1,233,7.594850,0.833466,0.013575
11,2020,2020,2,BeaverPass_WA_990,0,290,6.457827,0.360269,0.011855
12,2020,2020,2,CayusePass_WA,0,290,7.289505,0.468341,0.020332
13,2020,2020,2,Darrington,0,260,7.622228,0.578425,0.016933
14,2020,2020,2,MartenRidge_WA_999,0,290,7.983929,1.233078,0.046820
15,2020,2020,2,Paradise_WA,0,290,10.307509,0.824386,0.010200
16,2020,2020,2,Quinault,0,290,11.753516,1.430185,0.022782
17,2020,2020,2,RainyPass_WA_711,0,290,12.321244,3.134396,0.002445
18,2020,2020,2,SourdoughGulch_WA_985,0,161,10.331772,0.383787,0.021814
19,2020,2020,2,SourdoughGulch_WA_985,1,129,7.791150,2.544194,0.018431
20,2020,2020,2,Spokane,1,180,6.885073,0.839619,0.014452
21,2020,2020,3,BeaverPass_WA_990,0,310,5.901336,0.283071,0.006951
22,2020,2020,3,CayusePass_WA,0,310,6.533593,0.706727,0.003171
23,2020,2020,3,Darrington,0,310,6.511792,1.174047,0.027022
24,2020,2020,3,MartenRidge_WA_999,0,310,5.248556,0.455246,0.005854
25,2020,2020,3,Paradise_WA,0,310,7.891829,0.843742,0.001502
26,2020,2020,3,Quinault,0,310,7.758104,0.884539,0.022765
27,2020,2020,3,RainyPass_WA_711,0,310,11.762272,3.307415,0.001187
28,2020,2020,3,SourdoughGulch_WA_985,1,310,8.781143,2.895789,0.011835
29,2020,2020,3,Spokane,1,310,5.928599,0.842867,0.004625
30,2020,2020,4,BeaverPass_WA_990,0,300,5.540931,0.288887,0.016431
31,2020,2020,4,CayusePass_WA,0,300,6.851825,0.742581,0.036027
32,2020,2020,4,Darrington,0,300,7.766309,1.368167,0.033316
33,2020,2020,4,MartenRidge_WA_999,0,300,5.049045,0.327879,0.007917
34,2020,2020,4,Paradise_WA,0,300,7.785545,0.670718,0.021049
35,2020,2020,4,Quinault,0,300,9.268678,2.352764,0.036433
36,2020,2020,4,RainyPass_WA_711,0,300,11.679872,3.353165,0.002736
37,2020,2020,4,SourdoughGulch_WA_985,1,300,7.940720,2.914264,0.014059
38,2020,2020,4,Spokane,1,300,5.398617,0.782271,0.019637
39,2020,2020,5,BeaverPass_WA_990,0,310,5.610048,0.326814,0.004712
40,2020,2020,5,CayusePass_WA,0,310,6.580659,0.274885,0.011770
41,2020,2020,5,Darrington,0,310,7.744557,1.137439,0.028768
42,2020,2020,5,MartenRidge_WA_999,0,310,7.246506,0.792294,0.017956
43,2020,2020,5,Paradise_WA,0,310,7.428897,0.927239,0.014818
44,2020,2020,5,Quinault,0,310,9.001768,1.127758,0.020568
45,2020,2020,5,RainyPass_WA_711,0,310,11.708310,3.381010,0.006014
46,2020,2020,5,SourdoughGulch_WA_985,1,310,7.143636,2.250388,0.028470
47,2020,2020,5,Spokane,1,310,4.902749,0.796674,0.040206
48,2020,2020,6,BeaverPass_WA_990,0,300,7.530708,0.849616,0.020772
49,2020,2020,6,CayusePass_WA,0,300,7.208229,0.810543,0.035672

,fold_id,aligned_regime,centroid_drift,train_route_distance_mean,validation_route_distance_mean
0,forward_2020_l42,0,2.643508e-15,6.163492,6.649552
1,forward_2020_l42,1,1.328882e-15,6.163492,6.649552
2,forward_2020_l43,0,2.643508e-15,6.163492,6.649552
3,forward_2020_l43,1,1.328882e-15,6.163492,6.649552
4,forward_2020_l44,0,2.643508e-15,6.163492,6.649552
5,forward_2020_l44,1,1.328882e-15,6.163492,6.649552
6,forward_2021_l42,0,5.904762e-01,6.157639,6.562399
7,forward_2021_l42,1,2.986877e-01,6.157639,6.562399
8,forward_2021_l43,0,5.904762e-01,6.157639,6.562399
9,forward_2021_l43,1,2.986877e-01,6.157639,6.562399
10,forward_2021_l44,0,5.904762e-01,6.157639,6.562399
11,forward_2021_l44,1,2.986877e-01,6.157639,6.562399
12,forward_2022_l42,0,1.163275e+00,6.132726,6.439147
13,forward_2022_l42,1,6.722202e-01,6.132726,6.439147
14,forward_2022_l43,0,1.163275e+00,6.132726,6.439147
15,forward_2022_l43,1,6.722202e-01,6.132726,6.439147
16,forward_2022_l44,0,1.163275e+00,6.132726,6.439147
17,forward_2022_l44,1,6.722202e-01,6.132726,6.439147
18,station_2020_g0_p42_l42,0,6.240619e-01,6.225404,7.335677
19,station_2020_g0_p42_l42,1,1.704111e+00,6.225404,7.335677
20,station_2020_g0_p42_l43,0,6.240619e-01,6.225404,7.335677
21,station_2020_g0_p42_l43,1,1.704111e+00,6.225404,7.335677
22,station_2020_g0_p42_l44,0,6.240619e-01,6.225404,7.335677
23,station_2020_g0_p42_l44,1,1.704111e+00,6.225404,7.335677
24,station_2020_g0_p43_l42,0,7.208890e-01,6.033287,11.396849
25,station_2020_g0_p43_l42,1,7.757655e-14,6.033287,11.396849
26,station_2020_g0_p44_l42,0,6.711384e-01,6.067883,6.960800
27,station_2020_g0_p44_l42,1,1.114642e-13,6.067883,6.960800
28,station_2020_g0_p45_l42,0,7.208890e-01,6.033287,11.396849
29,station_2020_g0_p45_l42,1,7.757655e-14,6.033287,11.396849
30,station_2020_g0_p46_l42,0,7.208890e-01,6.033287,11.396849
31,station_2020_g0_p46_l42,1,7.757655e-14,6.033287,11.396849
32,station_2020_g1_p42_l42,0,7.208890e-01,6.033287,11.396849
33,station_2020_g1_p42_l42,1,7.757655e-14,6.033287,11.396849
34,station_2020_g1_p42_l43,0,7.208890e-01,6.033287,11.396849
35,station_2020_g1_p42_l43,1,7.757655e-14,6.033287,11.396849
36,station_2020_g1_p42_l44,0,7.208890e-01,6.033287,11.396849
37,station_2020_g1_p42_l44,1,7.757655e-14,6.033287,11.396849
38,station_2020_g1_p43_l42,1,6.737768e+00,6.342373,10.007659
39,station_2020_g1_p43_l42,0,3.077162e+00,6.342373,10.007659
40,station_2020_g1_p44_l42,1,6.737768e+00,6.342373,10.007659
41,station_2020_g1_p44_l42,0,3.077162e+00,6.342373,10.007659
42,station_2020_g1_p45_l42,1,6.737768e+00,6.342373,10.007659
43,station_2020_g1_p45_l42,0,3.077162e+00,6.342373,10.007659
44,station_2020_g1_p46_l42,0,6.711384e-01,6.067883,6.960800
45,station_2020_g1_p46_l42,1,1.114642e-13,6.067883,6.960800
46,station_2020_g2_p42_l42,0,6.711384e-01,6.067883,6.960800
47,station_2020_g2_p42_l42,1,1.114642e-13,6.067883,6.960800
48,station_2020_g2_p42_l43,0,6.711384e-01,6.067883,6.960800
49,station_2020_g2_p42_l43,1,1.114642e-13,6.067883,6.960800

{'candidate_ids': {'selected': 'selected_k__forward_time__k40',
  'union': 'v0_union_selected_k__forward_time__k40'},
 'single_sources': {'v0_single_global': {'source': 'V0', 'beta': 0.0},
  'selected_2_1_single_global': {'source': 'selected_k__forward_time__k40',
   'beta': 0.0},
  'union_2_1_v0_single_global': {'source': 'v0_union_selected_k__forward_time__k40',
   'beta': 0.0}},
 'shared_sources': {'v0_shared_hard_experts': {'source': 'V0', 'beta': 0.0},
  'selected_2_1_shared_hard_experts': {'source': 'selected_k__forward_time__k40',
   'beta': 0.0},
  'union_2_1_v0_shared_hard_experts': {'source': 'v0_union_selected_k__forward_time__k40',
   'beta': 0.0}},
 'strongest_shared_control': 'union_2_1_v0_shared_hard_experts',
 'strongest_single_global': 'union_2_1_v0_single_global',
 'historical_specialist_counts': {'0': 4, '1': 47},
 'global_gate_passed': True,
 'moe_diagnostic_runs_even_after_global_failure': True,
 'router_reference': {'columns': ['A_d_E_SAR_diff_kobs30',
   'A_d_LST_modis_kobs30',
   'A_d_SMAP_sm_interp_kobs30',
   'A_d_s2_b11_kobs30',
   'A_grad_E_SAR_diff_kobs30',
   'A_grad_LST_modis_kobs30',
   'A_grad_SMAP_sm_interp_kobs30',
   'A_grad_s2_b11_kobs30',
   'C_lag_F_NDVI_kobs30',
   'D_sa_F_NDMI',
   'D_sa_LST_modis',
   'D_z_E_SAR_ratio',
   'E_SAR_ratio',
   'F_MSI',
   'J_aspect_deg',
   'J_bio_bio15',
   'K_aspect_cos',
   'K_aspect_sin',
   'SMAP_sm_pm_interp_lag30',
   'SMAP_sm_pm_interp_rollrange30',
   'SMAP_x_year',
   'V_ema_F_NDVI_kobs30',
   'V_ema_LST_modis_kobs30',
   'V_rollmax_G_API_kobs7',
   'V_rollmean_F_NDMI_kobs30',
   'V_rollmin_s2_b12_kobs30',
   'V_rollrng_F_NDVI_kobs30',
   'aspect',
   'latitude',
   'lia_std_asc_deg',
   's2_b8',
   'slope',
   'A_grad_LST_modis_kobs14',
   'V_rollmax_E_SAR_ratio_kobs7',
   'A_d_LST_modis_kobs14',
   'J_clay_wfrac_b100',
   'V_ema_G_API_kobs30',
   'V_rollmin_G_API_kobs14',
   'V_rollrng_LST_modis_kobs30',
   'V_rollrng_G_API_kobs30',
   'A_d_SMAP_sm_interp_kobs5',
   'C_lag_F_NDMI_kobs30',
   'V_rollrng_E_SAR_ratio_kobs30',
   'J_bio_bio02',
   'SMAP_sm_pm_interp_rollmean30',
   'V_rollmax_E_SAR_ratio_kobs30',
   'V_rollmax_G_API_kobs30',
   's2_b11',
   'V_rollrng_F_NDVI_kobs14',
   'V_ema_SMAP_sm_interp_kobs30'],
  'means': [-0.00018248930940231438,
   0.15419228483597952,
   -0.0014988967147509203,
   -0.0005363075608831018,
   -6.0829769800758365e-06,
   0.005139742827865985,
   -4.9963223825027884e-05,
   -1.787691869610004e-05,
   0.4327782066571924,
   -0.020280926293461024,
   0.43799397584445343,
   -0.0029030661485317986,
   4.8518905545369275,
   0.4929615193793608,
   175.52349703640982,
   53.29455969517358,
   -0.4478323872593073,
   0.0850348856763805,
   0.36779069720494495,
   0.0825370000637194,
   0.12428212764950408,
   0.43466369618383793,
   283.1795674755553,
   64.79710453116401,
   0.38449984318143104,
   0.060951872643912455,
   0.22971383968064094,
   173.90100229872033,
   47.72681330916596,
   3.931560552264885,
   0.27102358547903826,
   16.385718330115353,
   0.005198046199201094,
   4.960902726530496,
   0.07277264678881533,
   12.972163420829805,
   51.99983522715208,
   33.40146560055745,
   8.266119630267875,
   64.58661570646404,
   -0.00013676125268846748,
   0.38383389716063715,
   0.682870158329714,
   100.41754868755292,
   0.3672431209828674,
   5.202647143928865,
   89.72795362542004,
   0.12917148474025544,
   0.1366512357315656,
   0.34097625703117634],
  'scaler_mean': [-0.00018248930940231438,
   0.15419228483597952,
   -0.0014988967147509203,
   -0.0005363075608831018,
   -6.0829769800758365e-06,
   0.005139742827865985,
   -4.9963223825027884e-05,
   -1.787691869610004e-05,
   0.4327782066571924,
   -0.020280926293461024,
   0.43799397584445343,
   -0.0029030661485317986,
   4.8518905545369275,
   0.4929615193793608,
   175.52349703640982,
   53.29455969517358,
   -0.4478323872593073,
   0.0850348856763805,
   0.36779069720494495,
   0.0825370000637194,
   0.12428212764950408,
   0.43466369618383793,
   283.1795674755553,
   64.79710453116401,
   0.38449984318143104,
   0.060951872643912455,
   0.22971383968064094,
   173.90100229872033,
   47.72681330916596,
   3.931560552264885,
   0.27102358547903826,
   16.385718330115353,
   0.005198046199201094,
   4.960902726530496,
   0.07277264678881533,
   12.972163420829805,
   51.99983522715208,
   33.40146560055745,
   8.266119630267875,
   64.58661570646404,
   -0.00013676125268846748,
   0.38383389716063715,
   0.682870158329714,
   100.41754868755292,
   0.3672431209828674,
   5.202647143928865,
   89.72795362542004,
   0.12917148474025544,
   0.1366512357315656,
   0.34097625703117634],
  'scaler_scale': [0.02326885482560617,
   7.612871097049953,
   0.0746910772324952,
   0.07993598323137772,
   0.0007756284941868418,
   0.25376236990166506,
   0.002489702574416469,
   0.0026645327743792303,
   0.26758890945990405,
   0.21616564845371156,
   6.18655069427177,
   0.9900042320891802,
   0.8409431807624563,
   0.28377410206463055,
   68.10601107901591,
   9.7227399610699,
   0.5169747891279646,
   0.7245359034637314,
   0.15233097563658013,
   0.05606075538120559,
   0.12017978899835953,
   0.23969130077317644,
   11.12775688241287,
   62.78097155799741,
   0.23137382117273192,
   0.04433126407451016,
   0.18248007815367456,
   24.73172495841127,
   0.9367782284191121,
   1.4043744614301124,
   0.10331528227878137,
   6.504043206564494,
   0.40190437690025854,
   0.8803897132985115,
   5.6266612766036195,
   6.768674413894038,
   46.348758688085404,
   36.39677927643194,
   4.456090332775121,
   54.38564025852636,
   0.03006739593766508,
   0.2425750655212014,
   0.5936985833441236,
   16.321293066713803,
   0.1487378260261108,
   0.9431741299059468,
   75.56767926115242,
   0.08336788872167789,
   0.1499741364330467,
   0.13726708016595943],
  'centers': [[-0.0023417964792601526,
    0.005080089709733793,
    -0.000881222909100088,
    -0.0024303230871274293,
    -0.002341796479260094,
    0.005080089709733668,
    -0.0008812229090997728,
    -0.0024303230871267453,
    0.114313611772123,
    0.362206525247381,
    -0.2640393709563047,
    -0.3284221943311996,
    -0.29562702627956117,
    -0.3829267624816452,
    0.08929682153188581,
    0.4806295347774083,
    0.21918938228259768,
    -0.13719373488939157,
    0.30919518846446614,
    0.11713662643623672,
    0.13834362541273443,
    0.13178910044503034,
    -0.17339388754852728,
    0.17262552170191978,
    0.3545485147064265,
    -0.41760734859615445,
    0.07101310088475007,
    2.391545448799532e-05,
    0.27009345643974325,
    -0.13196730260742107,
    0.0022969768997798553,
    0.15060153986476352,
    0.003227981169321892,
    -0.29921973090497117,
    0.0032279811693218833,
    -0.38504555043833205,
    0.1879099624547378,
    0.1572023920701047,
    -0.030562730410208322,
    0.19412403930711786,
    -2.966665873500408e-05,
    0.33848827222293637,
    -0.10362675494395812,
    -0.42116002511511497,
    0.3167361989309293,
    -0.29356159881959165,
    0.19601903131615844,
    -0.2951687357926841,
    0.04797630116432606,
    0.298615096686899],
   [0.009010329296034892,
    -0.019546225106872005,
    0.0033906057441466775,
    0.009350945526099778,
    0.009010329296034708,
    -0.019546225106872112,
    0.0033906057441456137,
    0.009350945526097363,
    -0.4398346714618579,
    -1.3936309557876294,
    1.0159216227815875,
    1.2636418857309721,
    1.137458732719551,
    1.4733544339917064,
    -0.34357971506799884,
    -1.849277004256225,
    -0.8433561712351415,
    0.527868557175778,
    -1.1896637856824128,
    -0.4506965426605122,
    -0.5322928922370895,
    -0.5070736091520182,
    0.6671527771812972,
    -0.6641964018690025,
    -1.3641658859843495,
    1.606791948241445,
    -0.2732310125883755,
    -9.201744136203417e-05,
    -1.0392154078201556,
    0.5077592623155823,
    -0.008837880847333883,
    -0.5794566174684427,
    -0.012420026058873938,
    1.1512820739129548,
    -0.012420026058873945,
    1.4815067125382526,
    -0.723005032554173,
    -0.6048541498890289,
    0.11759359432845361,
    -0.7469144026495964,
    0.00011414585626152383,
    -1.3023722695740425,
    0.39871576979206624,
    1.620461276725452,
    -1.2186786843422408,
    1.1295117647758248,
    -0.7542056007387731,
    1.135695407752357,
    -0.18459429575745454,
    -1.148955674733223]],
  'label_mapping': {'0': 0, '1': 1},
  'n_init': 10,
  'random_state': 42,
  'target_free_alignment': True,
  'router_hash': '0c584ec1e4a79e3ba20c56f0d33f22ac3deb5ecd6c87ae2c0cca5e3e32fc725c'}}

## Regime-delta coverage and incremental signal

**Purpose.** Test whether unused predictors add stable regime-specific signal after preserving the complete strongest shared backbone.

**Method.** The cell displays saved conditional rankings, regime metrics, and the final frozen expert feature specification for delta counts 0, 5, 10, and 15.

**Result.** Each regime records population, station/origin coverage, target dispersion, rank stability, paired improvement, and the reason for a zero-delta fallback.

**Interpretation.** A nonzero delta represents incremental signal only when its paired interval and worst-station guard pass; insufficient coverage or unstable evidence leaves the shared backbone intact.

In [3]:
stage_12 = "artifacts/development/stages/12_regime_delta_moe_decision"
show_csv(EXP_DIR, f"{stage_12}/regime_delta_rankings.csv")
show_csv(EXP_DIR, f"{stage_12}/regime_metrics.csv")
show_json(EXP_DIR, f"{stage_12}/frozen_moe_features.json")

,fold_id,outer_origin,regime,usable_folds,feature,original_position,importance_mean,importance_standard_error,importance_lcb,importance_observations,rank
0,forward_2020_l42,2020,0,1,A_d_G_API_kobs5,74,0.000010,1.546044e-06,7.075069e-06,3,1
1,forward_2020_l42,2020,0,1,C_lag_F_NDVI_kobs2,256,0.000006,4.539141e-07,5.514047e-06,3,2
2,forward_2020_l42,2020,0,1,A_d_G_API_kobs30,77,0.000006,3.044434e-07,5.100099e-06,3,3
3,forward_2020_l42,2020,0,1,H_corr_E_SAR_ratio__F_NDMI_kobs7,420,0.000010,2.540056e-06,4.904888e-06,3,4
4,forward_2020_l42,2020,0,1,C_lag_G_API_kobs6,106,0.000005,4.474403e-07,4.429337e-06,3,5
5,forward_2020_l42,2020,0,1,G_DSLR,24,0.000005,7.377963e-07,3.937662e-06,3,6
6,forward_2020_l42,2020,0,1,C_lag_s2_b12_kobs5,371,0.000005,6.855356e-07,3.826235e-06,3,7
7,forward_2020_l42,2020,0,1,A_d_E_SAR_ratio_kobs5,150,0.000005,8.456393e-07,3.660148e-06,3,8
8,forward_2020_l42,2020,0,1,V_rollstd_s2_b11_kobs30,324,0.000003,8.500750e-08,2.889258e-06,3,9
9,forward_2020_l42,2020,0,1,C_lag_E_SAR_diff_kobs5,295,0.000004,4.381534e-07,2.864510e-06,3,10
10,forward_2020_l42,2020,0,1,A_d_F_NDVI_kobs2,225,0.000005,9.082063e-07,2.825503e-06,3,11
11,forward_2020_l42,2020,0,1,C_lag_LST_modis_kobs6,220,0.000003,1.172141e-07,2.492784e-06,3,12
12,forward_2020_l42,2020,0,1,V_rollmin_G_API_kobs7,86,0.000003,2.780208e-07,2.472512e-06,3,13
13,forward_2020_l42,2020,0,1,C_lag_SMAP_sm_interp_kobs12,411,0.000004,5.559016e-07,2.434243e-06,3,14
14,forward_2020_l42,2020,0,1,A_d_E_SAR_diff_kobs5,264,0.000004,7.827410e-07,2.166561e-06,3,15
15,forward_2020_l42,2020,0,1,V_rollstd_F_NDVI_kobs7,234,0.000003,5.145252e-07,2.155438e-06,3,16
16,forward_2020_l42,2020,0,1,V_rollcv_F_NDVI_kobs7,236,0.000002,1.357530e-07,2.149295e-06,3,17
17,forward_2020_l42,2020,0,1,V_rollmean_s2_b11_kobs30,327,0.000002,3.578470e-08,2.018376e-06,3,18
18,forward_2020_l42,2020,0,1,A_grad_SMAP_sm_interp_kobs14,383,0.000002,1.950957e-07,1.812110e-06,3,19
19,forward_2020_l42,2020,0,1,A_d_F_NDVI_kobs7,227,0.000002,5.955396e-08,1.745579e-06,3,20
20,forward_2020_l42,2020,0,1,V_rollcv_E_SAR_diff_kobs14,281,0.000003,7.825174e-07,1.724932e-06,3,21
21,forward_2020_l42,2020,0,1,C_smm_s2_b11_alpha0.85_n5,337,0.000002,5.271733e-08,1.683438e-06,3,22
22,forward_2020_l42,2020,0,1,V_rollrng_s2_b11_kobs14,318,0.000002,1.863709e-08,1.610465e-06,3,23
23,forward_2020_l42,2020,0,1,A_d_s2_b12_kobs1,338,0.000002,2.937388e-07,1.610184e-06,3,24
24,forward_2020_l42,2020,0,1,V_ema_SMAP_sm_interp_kobs7,392,0.000002,6.876070e-08,1.600039e-06,3,25
25,forward_2020_l42,2020,0,1,V_rollstd_F_NDVI_kobs30,248,0.000003,5.256709e-07,1.519943e-06,3,26
26,forward_2020_l42,2020,0,1,V_rollcv_s2_b11_kobs30,326,0.000002,8.997142e-08,1.492863e-06,3,27
27,forward_2020_l42,2020,0,1,SMAP_sm_am_interp_ema02,42,0.000002,2.667832e-07,1.450712e-06,3,28
28,forward_2020_l42,2020,0,1,C_lag_G_API_kobs5,105,0.000002,4.734941e-07,1.448517e-06,3,29
29,forward_2020_l42,2020,0,1,A_d_s2_b12_kobs5,340,0.000003,5.839476e-07,1.420679e-06,3,30
30,forward_2020_l42,2020,0,1,V_rollstd_G_API_kobs30,96,0.000001,6.927965e-08,1.357510e-06,3,31
31,forward_2020_l42,2020,0,1,C_lag_F_NDVI_kobs12,259,0.000002,1.691992e-07,1.291995e-06,3,32
32,forward_2020_l42,2020,0,1,A_d_E_SAR_diff_kobs2,263,0.000002,3.185480e-07,1.269818e-06,3,33
33,forward_2020_l42,2020,0,1,A_grad_G_API_kobs14,79,0.000003,6.857280e-07,1.264813e-06,3,34
34,forward_2020_l42,2020,0,1,E_rough_s1_vh_kobs7,416,0.000002,6.466226e-07,1.156281e-06,3,35
35,forward_2020_l42,2020,0,1,C_lag_s2_b12_kobs30,374,0.000003,7.274665e-07,1.135461e-06,3,36
36,forward_2020_l42,2020,0,1,SMAP_sm_am_interp_rollmean30,39,0.000001,5.569451e-08,1.134624e-06,3,37
37,forward_2020_l42,2020,0,1,SMAP_sm_pm_interp_pctchg,49,0.000002,3.760689e-07,1.129204e-06,3,38
38,forward_2020_l42,2020,0,1,A_d_SMAP_sm_interp_kobs14,380,0.000001,5.223076e-08,1.105622e-06,3,39
39,forward_2020_l42,2020,0,1,C_lag_E_SAR_ratio_kobs6,182,0.000001,7.387782e-08,1.100703e-06,3,40
40,forward_2020_l42,2020,0,1,V_rollcv_F_NDVI_kobs30,250,0.000002,5.177576e-07,1.086261e-06,3,41
41,forward_2020_l42,2020,0,1,V_rollstd_F_NDVI_kobs14,241,0.000002,3.305267e-07,1.073802e-06,3,42
42,forward_2020_l42,2020,0,1,V_rollstd_E_SAR_ratio_kobs7,158,0.000002,4.515295e-07,1.030659e-06,3,43
43,forward_2020_l42,2020,0,1,C_lag_s2_b12_kobs6,372,0.000001,2.309398e-07,1.023204e-06,3,44
44,forward_2020_l42,2020,0,1,C_lag_SMAP_sm_interp_kobs2,408,0.000002,4.899946e-07,1.000010e-06,3,45
45,forward_2020_l42,2020,0,1,C_smm_s2_b12_alpha0.85_n5,375,0.000002,4.687850e-07,9.878301e-07,3,46
46,forward_2020_l42,2020,0,1,C_smm_G_API_alpha0.85_n5,109,0.000002,2.728728e-07,9.765158e-07,3,47
47,forward_2020_l42,2020,0,1,V_rollmean_E_SAR_diff_kobs14,282,0.000001,6.988223e-08,9.707504e-07,3,48
48,forward_2020_l42,2020,0,1,V_rollrng_E_SAR_diff_kobs14,280,0.000001,2.360470e-07,9.296495e-07,3,49
49,forward_2020_l42,2020,0,1,C_lag_LST_modis_kobs5,219,0.000001,1.721521e-07,9.086132e-07,3,50

   regime  delta_count          candidate  combined_primary_rmse  eligible
0       0            5   regime_0_delta_5               0.061823     False
1       0           10  regime_0_delta_10               0.061773     False
2       0           15  regime_0_delta_15               0.061819     False

{'promoted': False,
 'candidate': 'moe_shared_plus_selected_deltas',
 'shared_source': 'v0_union_selected_k__forward_time__k40',
 'shared_features': ['A_d_E_SAR_diff_kobs30',
  'A_d_LST_modis_kobs30',
  'A_d_SMAP_sm_interp_kobs30',
  'A_d_s2_b11_kobs30',
  'A_grad_E_SAR_diff_kobs30',
  'A_grad_LST_modis_kobs30',
  'A_grad_SMAP_sm_interp_kobs30',
  'A_grad_s2_b11_kobs30',
  'C_lag_F_NDVI_kobs30',
  'D_sa_F_NDMI',
  'D_sa_LST_modis',
  'D_z_E_SAR_ratio',
  'E_SAR_ratio',
  'F_MSI',
  'J_aspect_deg',
  'J_bio_bio15',
  'K_aspect_cos',
  'K_aspect_sin',
  'SMAP_sm_pm_interp_lag30',
  'SMAP_sm_pm_interp_rollrange30',
  'SMAP_x_year',
  'V_ema_F_NDVI_kobs30',
  'V_ema_LST_modis_kobs30',
  'V_rollmax_G_API_kobs7',
  'V_rollmean_F_NDMI_kobs30',
  'V_rollmin_s2_b12_kobs30',
  'V_rollrng_F_NDVI_kobs30',
  'aspect',
  'latitude',
  'lia_std_asc_deg',
  's2_b8',
  'slope',
  'A_grad_LST_modis_kobs14',
  'V_rollmax_E_SAR_ratio_kobs7',
  'A_d_LST_modis_kobs14',
  'J_clay_wfrac_b100',
  'V_ema_G_API_kobs30',
  'V_rollmin_G_API_kobs14',
  'V_rollrng_LST_modis_kobs30',
  'V_rollrng_G_API_kobs30',
  'A_d_SMAP_sm_interp_kobs5',
  'C_lag_F_NDMI_kobs30',
  'V_rollrng_E_SAR_ratio_kobs30',
  'J_bio_bio02',
  'SMAP_sm_pm_interp_rollmean30',
  'V_rollmax_E_SAR_ratio_kobs30',
  'V_rollmax_G_API_kobs30',
  's2_b11',
  'V_rollrng_F_NDVI_kobs14',
  'V_ema_SMAP_sm_interp_kobs30',
  'V_rollmin_G_API_kobs30',
  'elev',
  'V_rollmax_F_NDVI_kobs30',
  'D_sin_DOY',
  'V_rollmean_LST_modis_kobs30',
  'G_rain_sum_3d',
  'D_cos_DOY',
  'C_lag_G_API_kobs1',
  'precip_mm',
  'G_API',
  'API_x_year',
  'V_rollmax_LST_modis_kobs30',
  'C_lag_LST_modis_kobs30',
  'V_rollmin_LST_modis_kobs30',
  'longitude',
  'DOY',
  'V_ema_G_API_kobs14',
  'V_rollmean_G_API_kobs30',
  'V_rollmean_E_SAR_diff_kobs30',
  'V_ema_G_API_kobs7',
  'V_rollmean_G_API_kobs14',
  'G_rain_sum_7d',
  'V_rollmax_G_API_kobs14',
  'SMAP_sm_interp_rollstd30',
  'lia_mean_asc_deg',
  'V_rollmin_SMAP_sm_interp_kobs7',
  'V_rollmin_F_NDVI_kobs7',
  'V_rollmin_E_SAR_diff_kobs30'],
 'shared_ordered_feature_hash': '7c9c26a9ba574d8c0d71b813afdc65783396063c3b98f234ec1531e9deb3fad3',
 'regime_deltas': {'0': [], '1': []},
 'expert_features': {'0': ['A_d_E_SAR_diff_kobs30',
   'A_d_LST_modis_kobs30',
   'A_d_SMAP_sm_interp_kobs30',
   'A_d_s2_b11_kobs30',
   'A_grad_E_SAR_diff_kobs30',
   'A_grad_LST_modis_kobs30',
   'A_grad_SMAP_sm_interp_kobs30',
   'A_grad_s2_b11_kobs30',
   'C_lag_F_NDVI_kobs30',
   'D_sa_F_NDMI',
   'D_sa_LST_modis',
   'D_z_E_SAR_ratio',
   'E_SAR_ratio',
   'F_MSI',
   'J_aspect_deg',
   'J_bio_bio15',
   'K_aspect_cos',
   'K_aspect_sin',
   'SMAP_sm_pm_interp_lag30',
   'SMAP_sm_pm_interp_rollrange30',
   'SMAP_x_year',
   'V_ema_F_NDVI_kobs30',
   'V_ema_LST_modis_kobs30',
   'V_rollmax_G_API_kobs7',
   'V_rollmean_F_NDMI_kobs30',
   'V_rollmin_s2_b12_kobs30',
   'V_rollrng_F_NDVI_kobs30',
   'aspect',
   'latitude',
   'lia_std_asc_deg',
   's2_b8',
   'slope',
   'A_grad_LST_modis_kobs14',
   'V_rollmax_E_SAR_ratio_kobs7',
   'A_d_LST_modis_kobs14',
   'J_clay_wfrac_b100',
   'V_ema_G_API_kobs30',
   'V_rollmin_G_API_kobs14',
   'V_rollrng_LST_modis_kobs30',
   'V_rollrng_G_API_kobs30',
   'A_d_SMAP_sm_interp_kobs5',
   'C_lag_F_NDMI_kobs30',
   'V_rollrng_E_SAR_ratio_kobs30',
   'J_bio_bio02',
   'SMAP_sm_pm_interp_rollmean30',
   'V_rollmax_E_SAR_ratio_kobs30',
   'V_rollmax_G_API_kobs30',
   's2_b11',
   'V_rollrng_F_NDVI_kobs14',
   'V_ema_SMAP_sm_interp_kobs30',
   'V_rollmin_G_API_kobs30',
   'elev',
   'V_rollmax_F_NDVI_kobs30',
   'D_sin_DOY',
   'V_rollmean_LST_modis_kobs30',
   'G_rain_sum_3d',
   'D_cos_DOY',
   'C_lag_G_API_kobs1',
   'precip_mm',
   'G_API',
   'API_x_year',
   'V_rollmax_LST_modis_kobs30',
   'C_lag_LST_modis_kobs30',
   'V_rollmin_LST_modis_kobs30',
   'longitude',
   'DOY',
   'V_ema_G_API_kobs14',
   'V_rollmean_G_API_kobs30',
   'V_rollmean_E_SAR_diff_kobs30',
   'V_ema_G_API_kobs7',
   'V_rollmean_G_API_kobs14',
   'G_rain_sum_7d',
   'V_rollmax_G_API_kobs14',
   'SMAP_sm_interp_rollstd30',
   'lia_mean_asc_deg',
   'V_rollmin_SMAP_sm_interp_kobs7',
   'V_rollmin_F_NDVI_kobs7',
   'V_rollmin_E_SAR_diff_kobs30'],
  '1': ['A_d_E_SAR_diff_kobs30',
   'A_d_LST_modis_kobs30',
   'A_d_SMAP_sm_interp_kobs30',
   'A_d_s2_b11_kobs30',
   'A_grad_E_SAR_diff_kobs30',
   'A_grad_LST_modis_kobs30',
   'A_grad_SMAP_sm_interp_kobs30',
   'A_grad_s2_b11_kobs30',
   'C_lag_F_NDVI_kobs30',
   'D_sa_F_NDMI',
   'D_sa_LST_modis',
   'D_z_E_SAR_ratio',
   'E_SAR_ratio',
   'F_MSI',
   'J_aspect_deg',
   'J_bio_bio15',
   'K_aspect_cos',
   'K_aspect_sin',
   'SMAP_sm_pm_interp_lag30',
   'SMAP_sm_pm_interp_rollrange30',
   'SMAP_x_year',
   'V_ema_F_NDVI_kobs30',
   'V_ema_LST_modis_kobs30',
   'V_rollmax_G_API_kobs7',
   'V_rollmean_F_NDMI_kobs30',
   'V_rollmin_s2_b12_kobs30',
   'V_rollrng_F_NDVI_kobs30',
   'aspect',
   'latitude',
   'lia_std_asc_deg',
   's2_b8',
   'slope',
   'A_grad_LST_modis_kobs14',
   'V_rollmax_E_SAR_ratio_kobs7',
   'A_d_LST_modis_kobs14',
   'J_clay_wfrac_b100',
   'V_ema_G_API_kobs30',
   'V_rollmin_G_API_kobs14',
   'V_rollrng_LST_modis_kobs30',
   'V_rollrng_G_API_kobs30',
   'A_d_SMAP_sm_interp_kobs5',
   'C_lag_F_NDMI_kobs30',
   'V_rollrng_E_SAR_ratio_kobs30',
   'J_bio_bio02',
   'SMAP_sm_pm_interp_rollmean30',
   'V_rollmax_E_SAR_ratio_kobs30',
   'V_rollmax_G_API_kobs30',
   's2_b11',
   'V_rollrng_F_NDVI_kobs14',
   'V_ema_SMAP_sm_interp_kobs30',
   'V_rollmin_G_API_kobs30',
   'elev',
   'V_rollmax_F_NDVI_kobs30',
   'D_sin_DOY',
   'V_rollmean_LST_modis_kobs30',
   'G_rain_sum_3d',
   'D_cos_DOY',
   'C_lag_G_API_kobs1',
   'precip_mm',
   'G_API',
   'API_x_year',
   'V_rollmax_LST_modis_kobs30',
   'C_lag_LST_modis_kobs30',
   'V_rollmin_LST_modis_kobs30',
   'longitude',
   'DOY',
   'V_ema_G_API_kobs14',
   'V_rollmean_G_API_kobs30',
   'V_rollmean_E_SAR_diff_kobs30',
   'V_ema_G_API_kobs7',
   'V_rollmean_G_API_kobs14',
   'G_rain_sum_7d',
   'V_rollmax_G_API_kobs14',
   'SMAP_sm_interp_rollstd30',
   'lia_mean_asc_deg',
   'V_rollmin_SMAP_sm_interp_kobs7',
   'V_rollmin_F_NDVI_kobs7',
   'V_rollmin_E_SAR_diff_kobs30']},
 'router': {'columns': ['A_d_E_SAR_diff_kobs30',
   'A_d_LST_modis_kobs30',
   'A_d_SMAP_sm_interp_kobs30',
   'A_d_s2_b11_kobs30',
   'A_grad_E_SAR_diff_kobs30',
   'A_grad_LST_modis_kobs30',
   'A_grad_SMAP_sm_interp_kobs30',
   'A_grad_s2_b11_kobs30',
   'C_lag_F_NDVI_kobs30',
   'D_sa_F_NDMI',
   'D_sa_LST_modis',
   'D_z_E_SAR_ratio',
   'E_SAR_ratio',
   'F_MSI',
   'J_aspect_deg',
   'J_bio_bio15',
   'K_aspect_cos',
   'K_aspect_sin',
   'SMAP_sm_pm_interp_lag30',
   'SMAP_sm_pm_interp_rollrange30',
   'SMAP_x_year',
   'V_ema_F_NDVI_kobs30',
   'V_ema_LST_modis_kobs30',
   'V_rollmax_G_API_kobs7',
   'V_rollmean_F_NDMI_kobs30',
   'V_rollmin_s2_b12_kobs30',
   'V_rollrng_F_NDVI_kobs30',
   'aspect',
   'latitude',
   'lia_std_asc_deg',
   's2_b8',
   'slope',
   'A_grad_LST_modis_kobs14',
   'V_rollmax_E_SAR_ratio_kobs7',
   'A_d_LST_modis_kobs14',
   'J_clay_wfrac_b100',
   'V_ema_G_API_kobs30',
   'V_rollmin_G_API_kobs14',
   'V_rollrng_LST_modis_kobs30',
   'V_rollrng_G_API_kobs30',
   'A_d_SMAP_sm_interp_kobs5',
   'C_lag_F_NDMI_kobs30',
   'V_rollrng_E_SAR_ratio_kobs30',
   'J_bio_bio02',
   'SMAP_sm_pm_interp_rollmean30',
   'V_rollmax_E_SAR_ratio_kobs30',
   'V_rollmax_G_API_kobs30',
   's2_b11',
   'V_rollrng_F_NDVI_kobs14',
   'V_ema_SMAP_sm_interp_kobs30'],
  'means': [-0.00018248930940231438,
   0.15419228483597952,
   -0.0014988967147509203,
   -0.0005363075608831018,
   -6.0829769800758365e-06,
   0.005139742827865985,
   -4.9963223825027884e-05,
   -1.787691869610004e-05,
   0.4327782066571924,
   -0.020280926293461024,
   0.43799397584445343,
   -0.0029030661485317986,
   4.8518905545369275,
   0.4929615193793608,
   175.52349703640982,
   53.29455969517358,
   -0.4478323872593073,
   0.0850348856763805,
   0.36779069720494495,
   0.0825370000637194,
   0.12428212764950408,
   0.43466369618383793,
   283.1795674755553,
   64.79710453116401,
   0.38449984318143104,
   0.060951872643912455,
   0.22971383968064094,
   173.90100229872033,
   47.72681330916596,
   3.931560552264885,
   0.27102358547903826,
   16.385718330115353,
   0.005198046199201094,
   4.960902726530496,
   0.07277264678881533,
   12.972163420829805,
   51.99983522715208,
   33.40146560055745,
   8.266119630267875,
   64.58661570646404,
   -0.00013676125268846748,
   0.38383389716063715,
   0.682870158329714,
   100.41754868755292,
   0.3672431209828674,
   5.202647143928865,
   89.72795362542004,
   0.12917148474025544,
   0.1366512357315656,
   0.34097625703117634],
  'scaler_mean': [-0.00018248930940231438,
   0.15419228483597952,
   -0.0014988967147509203,
   -0.0005363075608831018,
   -6.0829769800758365e-06,
   0.005139742827865985,
   -4.9963223825027884e-05,
   -1.787691869610004e-05,
   0.4327782066571924,
   -0.020280926293461024,
   0.43799397584445343,
   -0.0029030661485317986,
   4.8518905545369275,
   0.4929615193793608,
   175.52349703640982,
   53.29455969517358,
   -0.4478323872593073,
   0.0850348856763805,
   0.36779069720494495,
   0.0825370000637194,
   0.12428212764950408,
   0.43466369618383793,
   283.1795674755553,
   64.79710453116401,
   0.38449984318143104,
   0.060951872643912455,
   0.22971383968064094,
   173.90100229872033,
   47.72681330916596,
   3.931560552264885,
   0.27102358547903826,
   16.385718330115353,
   0.005198046199201094,
   4.960902726530496,
   0.07277264678881533,
   12.972163420829805,
   51.99983522715208,
   33.40146560055745,
   8.266119630267875,
   64.58661570646404,
   -0.00013676125268846748,
   0.38383389716063715,
   0.682870158329714,
   100.41754868755292,
   0.3672431209828674,
   5.202647143928865,
   89.72795362542004,
   0.12917148474025544,
   0.1366512357315656,
   0.34097625703117634],
  'scaler_scale': [0.02326885482560617,
   7.612871097049953,
   0.0746910772324952,
   0.07993598323137772,
   0.0007756284941868418,
   0.25376236990166506,
   0.002489702574416469,
   0.0026645327743792303,
   0.26758890945990405,
   0.21616564845371156,
   6.18655069427177,
   0.9900042320891802,
   0.8409431807624563,
   0.28377410206463055,
   68.10601107901591,
   9.7227399610699,
   0.5169747891279646,
   0.7245359034637314,
   0.15233097563658013,
   0.05606075538120559,
   0.12017978899835953,
   0.23969130077317644,
   11.12775688241287,
   62.78097155799741,
   0.23137382117273192,
   0.04433126407451016,
   0.18248007815367456,
   24.73172495841127,
   0.9367782284191121,
   1.4043744614301124,
   0.10331528227878137,
   6.504043206564494,
   0.40190437690025854,
   0.8803897132985115,
   5.6266612766036195,
   6.768674413894038,
   46.348758688085404,
   36.39677927643194,
   4.456090332775121,
   54.38564025852636,
   0.03006739593766508,
   0.2425750655212014,
   0.5936985833441236,
   16.321293066713803,
   0.1487378260261108,
   0.9431741299059468,
   75.56767926115242,
   0.08336788872167789,
   0.1499741364330467,
   0.13726708016595943],
  'centers': [[-0.0023417964792601526,
    0.005080089709733793,
    -0.000881222909100088,
    -0.0024303230871274293,
    -0.002341796479260094,
    0.005080089709733668,
    -0.0008812229090997728,
    -0.0024303230871267453,
    0.114313611772123,
    0.362206525247381,
    -0.2640393709563047,
    -0.3284221943311996,
    -0.29562702627956117,
    -0.3829267624816452,
    0.08929682153188581,
    0.4806295347774083,
    0.21918938228259768,
    -0.13719373488939157,
    0.30919518846446614,
    0.11713662643623672,
    0.13834362541273443,
    0.13178910044503034,
    -0.17339388754852728,
    0.17262552170191978,
    0.3545485147064265,
    -0.41760734859615445,
    0.07101310088475007,
    2.391545448799532e-05,
    0.27009345643974325,
    -0.13196730260742107,
    0.0022969768997798553,
    0.15060153986476352,
    0.003227981169321892,
    -0.29921973090497117,
    0.0032279811693218833,
    -0.38504555043833205,
    0.1879099624547378,
    0.1572023920701047,
    -0.030562730410208322,
    0.19412403930711786,
    -2.966665873500408e-05,
    0.33848827222293637,
    -0.10362675494395812,
    -0.42116002511511497,
    0.3167361989309293,
    -0.29356159881959165,
    0.19601903131615844,
    -0.2951687357926841,
    0.04797630116432606,
    0.298615096686899],
   [0.009010329296034892,
    -0.019546225106872005,
    0.0033906057441466775,
    0.009350945526099778,
    0.009010329296034708,
    -0.019546225106872112,
    0.0033906057441456137,
    0.009350945526097363,
    -0.4398346714618579,
    -1.3936309557876294,
    1.0159216227815875,
    1.2636418857309721,
    1.137458732719551,
    1.4733544339917064,
    -0.34357971506799884,
    -1.849277004256225,
    -0.8433561712351415,
    0.527868557175778,
    -1.1896637856824128,
    -0.4506965426605122,
    -0.5322928922370895,
    -0.5070736091520182,
    0.6671527771812972,
    -0.6641964018690025,
    -1.3641658859843495,
    1.606791948241445,
    -0.2732310125883755,
    -9.201744136203417e-05,
    -1.0392154078201556,
    0.5077592623155823,
    -0.008837880847333883,
    -0.5794566174684427,
    -0.012420026058873938,
    1.1512820739129548,
    -0.012420026058873945,
    1.4815067125382526,
    -0.723005032554173,
    -0.6048541498890289,
    0.11759359432845361,
    -0.7469144026495964,
    0.00011414585626152383,
    -1.3023722695740425,
    0.39871576979206624,
    1.620461276725452,
    -1.2186786843422408,
    1.1295117647758248,
    -0.7542056007387731,
    1.135695407752357,
    -0.18459429575745454,
    -1.148955674733223]],
  'label_mapping': {'0': 0, '1': 1},
  'n_init': 10,
  'random_state': 42,
  'target_free_alignment': True,
  'router_hash': '0c584ec1e4a79e3ba20c56f0d33f22ac3deb5ecd6c87ae2c0cca5e3e32fc725c'},
 'learner_seed': 42,
 'beta': 0.0,
 'corresponding_single_global': 'union_2_1_v0_single_global'}

## MoE promotion verdict

**Purpose.** Expose the final decision and its dependency on global feature-selection success.

**Method.** The cell reads the root promotion artifact produced by stage 12, including all significance and robustness guards.

**Result.** The verdict identifies either an eligible promoted MoE or the strongest single-global challenger, with diagnostic-only status when the global gate failed.

**Interpretation.** Hard routing cannot rescue a failed global gate, and no diagnostic MoE is eligible for a benchmark-SOTA claim.

In [4]:
show_json(EXP_DIR, "artifacts/development/moe_promotion_decision.json")

{'moe_promoted': False,
 'winner': 'v0_union_selected_k__forward_time__k40',
 'benchmark_sota_eligible': True,
 'reason': 'moe_development_gate_failed',
 'failure_reasons': ['paired_primary_upper_ci_not_below_zero',
  'forward_time_point_regression',
  'station_time_point_regression',
  'p90_month_guard_failed'],
 'comparison': {'candidate': 'moe_shared_plus_selected_deltas',
  'corresponding_single_global': 'union_2_1_v0_single_global',
  'candidate_beta': 0.0,
  'reference_beta': 0.0,
  'actual_count': 89,
  'list_form': 'shared_hard_experts',
  'path_source': 'forward_time',
  'combined_primary_rmse': 0.06235550027100914,
  'forward_time_rmse': 0.04995798132337426,
  'station_time_rmse': 0.07475301921864401,
  'selection_stability': 0.0,
  'coverage_matches_v0': True,
  'promotable': True,
  'bootstrap': {'candidate': 'moe_shared_plus_selected_deltas',
   'reference': 'union_2_1_v0_single_global',
   'beta': 0.0,
   'candidate_beta': 0.0,
   'reference_beta': 0.0,
   'replicates': 2000,
   'seed': 42,
   'comparisons': {'combined_primary_rmse': {'candidate': 0.062355500271009126,
     'reference': 0.0586644992916075,
     'delta': 0.003691000979401629,
     'ci_lower': -0.0004980082613434022,
     'ci_upper': 0.008924355614762822,
     'bootstrap_standard_error': 0.0023597860481122585},
    'forward_time_rmse': {'candidate': 0.04995798132337425,
     'reference': 0.04726964761531539,
     'delta': 0.0026883337080588626,
     'ci_lower': -0.0001890518313183769,
     'ci_upper': 0.005993376333063671,
     'bootstrap_standard_error': 0.00160369652485972},
    'station_time_rmse': {'candidate': 0.07475301921864401,
     'reference': 0.0700593509678996,
     'delta': 0.004693668250744409,
     'ci_lower': -0.0034664512370638765,
     'ci_upper': 0.015561837319344825,
     'bootstrap_standard_error': 0.004729429905875068},
    'p90_station_year_rmse': {'candidate': 0.09960320982858635,
     'reference': 0.0932286762703662,
     'delta': 0.006374533558220152,
     'ci_lower': -0.006760879234347733,
     'ci_upper': 0.03426114255803072,
     'bootstrap_standard_error': 0.010437775461758735},
    'worst_station_rmse': {'candidate': 0.09500566872138727,
     'reference': 0.08965699008002223,
     'delta': 0.00534867864136504,
     'ci_lower': -0.006537768637427641,
     'ci_upper': 0.0301465563399769,
     'bootstrap_standard_error': 0.008396166632732105},
    'p90_month_rmse': {'candidate': 0.08666798301311861,
     'reference': 0.08031910097411535,
     'delta': 0.006348882039003259,
     'ci_lower': -0.0009508858349165271,
     'ci_upper': 0.014238899137164316,
     'bootstrap_standard_error': 0.0039005123340810437}},
   'candidate_primary_bootstrap_standard_error': 0.005479813852419123},
  'eligible': False,
  'failure_reasons': ['paired_primary_upper_ci_not_below_zero',
   'forward_time_point_regression',
   'station_time_point_regression',
   'p90_month_guard_failed']},
 'strongest_single_global_comparator': 'union_2_1_v0_single_global',
 'best_moe_development_candidate': 'moe_shared_plus_selected_deltas',
 'candidate_comparisons': [{'candidate': 'v0_shared_hard_experts',
   'corresponding_single_global': 'v0_single_global',
   'candidate_beta': 0.0,
   'reference_beta': 0.0,
   'actual_count': 50,
   'list_form': 'shared_hard_experts',
   'path_source': 'forward_time',
   'combined_primary_rmse': 0.06457277034857989,
   'forward_time_rmse': 0.052723394024896106,
   'station_time_rmse': 0.07642214667226366,
   'selection_stability': 0.0,
   'coverage_matches_v0': True,
   'promotable': True,
   'bootstrap': {'candidate': 'v0_shared_hard_experts',
    'reference': 'v0_single_global',
    'beta': 0.0,
    'candidate_beta': 0.0,
    'reference_beta': 0.0,
    'replicates': 2000,
    'seed': 42,
    'comparisons': {'combined_primary_rmse': {'candidate': 0.06457277034857989,
      'reference': 0.06344368921538683,
      'delta': 0.0011290811331930578,
      'ci_lower': -0.003243010287281442,
      'ci_upper': 0.005803835931916532,
      'bootstrap_standard_error': 0.002245485644755387},
     'forward_time_rmse': {'candidate': 0.052723394024896106,
      'reference': 0.051871424826916264,
      'delta': 0.0008519691979798419,
      'ci_lower': -0.001601608115203672,
      'ci_upper': 0.0035587874774413316,
      'bootstrap_standard_error': 0.0012819357539252075},
     'station_time_rmse': {'candidate': 0.07642214667226366,
      'reference': 0.07501595360385739,
      'delta': 0.0014061930684062668,
      'ci_lower': -0.006252303642465614,
      'ci_upper': 0.009511667875070873,
      'bootstrap_standard_error': 0.0040219079836548415},
     'p90_station_year_rmse': {'candidate': 0.11076447141151198,
      'reference': 0.09762904677386733,
      'delta': 0.013135424637644652,
      'ci_lower': -0.007868303461347759,
      'ci_upper': 0.01987120028309472,
      'bootstrap_standard_error': 0.008149599552772354},
     'worst_station_rmse': {'candidate': 0.10019523232076272,
      'reference': 0.09738141208841535,
      'delta': 0.002813820232347372,
      'ci_lower': -0.00347748965612156,
      'ci_upper': 0.014703122665052429,
      'bootstrap_standard_error': 0.004299481052041125},
     'p90_month_rmse': {'candidate': 0.09114356738770367,
      'reference': 0.09033922933903622,
      'delta': 0.0008043380486674467,
      'ci_lower': -0.004606148173106178,
      'ci_upper': 0.0066913392905922145,
      'bootstrap_standard_error': 0.0029033132587012005}},
    'candidate_primary_bootstrap_standard_error': 0.005539251191572791},
   'eligible': False,
   'failure_reasons': ['paired_primary_upper_ci_not_below_zero',
    'forward_time_point_regression',
    'station_time_point_regression',
    'p90_station_year_guard_failed']},
  {'candidate': 'selected_2_1_shared_hard_experts',
   'corresponding_single_global': 'selected_2_1_single_global',
   'candidate_beta': 0.0,
   'reference_beta': 0.0,
   'actual_count': 40,
   'list_form': 'shared_hard_experts',
   'path_source': 'forward_time',
   'combined_primary_rmse': 0.06787488632982684,
   'forward_time_rmse': 0.04999033685648059,
   'station_time_rmse': 0.08575943580317309,
   'selection_stability': 0.0,
   'coverage_matches_v0': True,
   'promotable': True,
   'bootstrap': {'candidate': 'selected_2_1_shared_hard_experts',
    'reference': 'selected_2_1_single_global',
    'beta': 0.0,
    'candidate_beta': 0.0,
    'reference_beta': 0.0,
    'replicates': 2000,
    'seed': 42,
    'comparisons': {'combined_primary_rmse': {'candidate': 0.06787488632982684,
      'reference': 0.06597379849832147,
      'delta': 0.0019010878315053742,
      'ci_lower': -0.003354626188932433,
      'ci_upper': 0.007255990885805998,
      'bootstrap_standard_error': 0.00274064319143655},
     'forward_time_rmse': {'candidate': 0.049990336856480584,
      'reference': 0.04631240025237514,
      'delta': 0.003677936604105446,
      'ci_lower': 0.0009175569237300178,
      'ci_upper': 0.0066986442711667125,
      'bootstrap_standard_error': 0.001433548651449868},
     'station_time_rmse': {'candidate': 0.08575943580317309,
      'reference': 0.0856351967442678,
      'delta': 0.00012423905890529552,
      'ci_lower': -0.00982375695865064,
      'ci_upper': 0.011365733082982877,
      'bootstrap_standard_error': 0.005402649354347574},
     'p90_station_year_rmse': {'candidate': 0.11354122000692872,
      'reference': 0.114458763483529,
      'delta': -0.0009175434766002799,
      'ci_lower': -0.026447814279653897,
      'ci_upper': 0.022506184772128,
      'bootstrap_standard_error': 0.013300358209833529},
     'worst_station_rmse': {'candidate': 0.10461523128405424,
      'reference': 0.09521493791159487,
      'delta': 0.009400293372459373,
      'ci_lower': -0.012593605809076633,
      'ci_upper': 0.019817364475099075,
      'bootstrap_standard_error': 0.009521269000087334},
     'p90_month_rmse': {'candidate': 0.09562945991532334,
      'reference': 0.0934882342562351,
      'delta': 0.002141225659088239,
      'ci_lower': -0.007227175538575871,
      'ci_upper': 0.009560875873710264,
      'bootstrap_standard_error': 0.0041889489817095605}},
    'candidate_primary_bootstrap_standard_error': 0.005424451778775185},
   'eligible': False,
   'failure_reasons': ['paired_primary_upper_ci_not_below_zero',
    'forward_time_point_regression',
    'station_time_point_regression']},
  {'candidate': 'union_2_1_v0_shared_hard_experts',
   'corresponding_single_global': 'union_2_1_v0_single_global',
   'candidate_beta': 0.0,
   'reference_beta': 0.0,
   'actual_count': 89,
   'list_form': 'shared_hard_experts',
   'path_source': 'forward_time',
   'combined_primary_rmse': 0.06235550027100914,
   'forward_time_rmse': 0.04995798132337426,
   'station_time_rmse': 0.07475301921864401,
   'selection_stability': 0.0,
   'coverage_matches_v0': True,
   'promotable': True,
   'bootstrap': {'candidate': 'union_2_1_v0_shared_hard_experts',
    'reference': 'union_2_1_v0_single_global',
    'beta': 0.0,
    'candidate_beta': 0.0,
    'reference_beta': 0.0,
    'replicates': 2000,
    'seed': 42,
    'comparisons': {'combined_primary_rmse': {'candidate': 0.062355500271009126,
      'reference': 0.0586644992916075,
      'delta': 0.003691000979401629,
      'ci_lower': -0.0004980082613434022,
      'ci_upper': 0.008924355614762822,
      'bootstrap_standard_error': 0.0023597860481122585},
     'forward_time_rmse': {'candidate': 0.04995798132337425,
      'reference': 0.04726964761531539,
      'delta': 0.0026883337080588626,
      'ci_lower': -0.0001890518313183769,
      'ci_upper': 0.005993376333063671,
      'bootstrap_standard_error': 0.00160369652485972},
     'station_time_rmse': {'candidate': 0.07475301921864401,
      'reference': 0.0700593509678996,
      'delta': 0.004693668250744409,
      'ci_lower': -0.0034664512370638765,
      'ci_upper': 0.015561837319344825,
      'bootstrap_standard_error': 0.004729429905875068},
     'p90_station_year_rmse': {'candidate': 0.09960320982858635,
      'reference': 0.0932286762703662,
      'delta': 0.006374533558220152,
      'ci_lower': -0.006760879234347733,
      'ci_upper': 0.03426114255803072,
      'bootstrap_standard_error': 0.010437775461758735},
     'worst_station_rmse': {'candidate': 0.09500566872138727,
      'reference': 0.08965699008002223,
      'delta': 0.00534867864136504,
      'ci_lower': -0.006537768637427641,
      'ci_upper': 0.0301465563399769,
      'bootstrap_standard_error': 0.008396166632732105},
     'p90_month_rmse': {'candidate': 0.08666798301311861,
      'reference': 0.08031910097411535,
      'delta': 0.006348882039003259,
      'ci_lower': -0.0009508858349165271,
      'ci_upper': 0.014238899137164316,
      'bootstrap_standard_error': 0.0039005123340810437}},
    'candidate_primary_bootstrap_standard_error': 0.005479813852419123},
   'eligible': False,
   'failure_reasons': ['paired_primary_upper_ci_not_below_zero',
    'forward_time_point_regression',
    'station_time_point_regression',
    'p90_month_guard_failed']},
  {'candidate': 'moe_shared_plus_selected_deltas',
   'corresponding_single_global': 'union_2_1_v0_single_global',
   'candidate_beta': 0.0,
   'reference_beta': 0.0,
   'actual_count': 89,
   'list_form': 'shared_hard_experts',
   'path_source': 'forward_time',
   'combined_primary_rmse': 0.06235550027100914,
   'forward_time_rmse': 0.04995798132337426,
   'station_time_rmse': 0.07475301921864401,
   'selection_stability': 0.0,
   'coverage_matches_v0': True,
   'promotable': True,
   'bootstrap': {'candidate': 'moe_shared_plus_selected_deltas',
    'reference': 'union_2_1_v0_single_global',
    'beta': 0.0,
    'candidate_beta': 0.0,
    'reference_beta': 0.0,
    'replicates': 2000,
    'seed': 42,
    'comparisons': {'combined_primary_rmse': {'candidate': 0.062355500271009126,
      'reference': 0.0586644992916075,
      'delta': 0.003691000979401629,
      'ci_lower': -0.0004980082613434022,
      'ci_upper': 0.008924355614762822,
      'bootstrap_standard_error': 0.0023597860481122585},
     'forward_time_rmse': {'candidate': 0.04995798132337425,
      'reference': 0.04726964761531539,
      'delta': 0.0026883337080588626,
      'ci_lower': -0.0001890518313183769,
      'ci_upper': 0.005993376333063671,
      'bootstrap_standard_error': 0.00160369652485972},
     'station_time_rmse': {'candidate': 0.07475301921864401,
      'reference': 0.0700593509678996,
      'delta': 0.004693668250744409,
      'ci_lower': -0.0034664512370638765,
      'ci_upper': 0.015561837319344825,
      'bootstrap_standard_error': 0.004729429905875068},
     'p90_station_year_rmse': {'candidate': 0.09960320982858635,
      'reference': 0.0932286762703662,
      'delta': 0.006374533558220152,
      'ci_lower': -0.006760879234347733,
      'ci_upper': 0.03426114255803072,
      'bootstrap_standard_error': 0.010437775461758735},
     'worst_station_rmse': {'candidate': 0.09500566872138727,
      'reference': 0.08965699008002223,
      'delta': 0.00534867864136504,
      'ci_lower': -0.006537768637427641,
      'ci_upper': 0.0301465563399769,
      'bootstrap_standard_error': 0.008396166632732105},
     'p90_month_rmse': {'candidate': 0.08666798301311861,
      'reference': 0.08031910097411535,
      'delta': 0.006348882039003259,
      'ci_lower': -0.0009508858349165271,
      'ci_upper': 0.014238899137164316,
      'bootstrap_standard_error': 0.0039005123340810437}},
    'candidate_primary_bootstrap_standard_error': 0.005479813852419123},
   'eligible': False,
   'failure_reasons': ['paired_primary_upper_ci_not_below_zero',
    'forward_time_point_regression',
    'station_time_point_regression',
    'p90_month_guard_failed']}]}