# Execute the complete derived 8.3 feature-selection 2.0 pipeline

This notebook is the single reproduction entry point for the derived 8.3 rerun of the unchanged feature-selection 2.2 methodology. It invokes the resumable master runner without importing artifacts from the source experiment.

## Configure the full resumable run

The run uses four CUDA workers with one internal XGBoost worker per fit. Rerunning the notebook after an interruption resumes the first incomplete stage, while rerunning after all 13 stages complete starts a clean experiment-local rebuild.

In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().resolve()
for candidate in [PROJECT_ROOT, *PROJECT_ROOT.parents]:
    if (candidate / "data" / "splits").is_dir():
        PROJECT_ROOT = candidate
        break
EXP_DIR = PROJECT_ROOT / "notebooks/experiment/derived_8.3-feature-selection-2.0"
RUNNER = EXP_DIR / "run_all.py"
assert RUNNER.exists(), RUNNER
command = [sys.executable, str(RUNNER), "--device", "cuda", "--workers", "4"]
print("Full run: long-running; rerun this notebook to resume after a VM timeout.")
print("Command:", " ".join(command))

Full run: long-running; rerun this notebook to resume after a VM timeout.
Command: /scratch/user/u.rp352032/MDR-Project/notebooks/.venv/bin/python3 /scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/run_all.py --device cuda --workers 4

## Run all stages and display generated results

The master runner owns cleanup, checkpointing, stage ordering, and resume. After all 13 stages finish, this cell loads the generated validation, retrospective, candidate-diagnostic, and MoE tables and lists every persisted CSV artifact.

In [2]:
import subprocess

subprocess.run(command, cwd=PROJECT_ROOT, check=True)

sys.path.insert(0, str(EXP_DIR))
from generate_results import (
    build_candidate_ceiling_table,
    build_moe_table,
    build_retrospective_table,
    build_validation_table,
)

tables = {
    "Validation": build_validation_table(),
    "Retrospective": build_retrospective_table(),
    "Candidate diagnostics": build_candidate_ceiling_table(),
    "MoE ablation": build_moe_table(),
}
for title, table in tables.items():
    print()
    print(title)
    display(table)
print("Artifacts:")
for path in sorted((EXP_DIR / "artifacts").rglob("*.csv")):
    print(path)

coerce_numeric: replaced 1143 inf values with NaN

coerce_numeric: replaced 2317 inf values with NaN

[
  {
    "dataset": "derived_8.0",
    "global_n_features": 40,
    "global_stopping_reason": "minimum_grouped_oof_upper_confidence_bound",
    "regimes": {}
  },
  {
    "dataset": "derived_8.3",
    "global_n_features": 40,
    "global_stopping_reason": "minimum_grouped_oof_upper_confidence_bound",
    "regimes": {
      "0": {
        "n_features": 40,
        "n_delta": 0,
        "stopping_reason": "no_regime_delta_with_positive_paired_lcb"
      },
      "1": {
        "n_features": 40,
        "n_delta": 0,
        "stopping_reason": "no_regime_delta_with_positive_paired_lcb"
      }
    },
    "router": {
      "kind": "clustering_v0_full_k2",
      "feature_source": "data/splits/derived_8.3/dataset_metadata.py::OVERALL_SELECTED_FEATURES_V0",
      "feature_count": 50,
      "fit_scope": "combined_development_pool",
      "frozen_for_evaluation": false
    }
  }
]

derived_8.0: completed evaluation task 1/4
derived_8.0: completed evaluation task 2/4
derived_8.0: completed evaluation task 3/4
derived_8.0: completed evaluation task 4/4

derived_8.3: completed evaluation task 1/6
derived_8.3: completed evaluation task 2/6

derived_8.3: completed evaluation task 3/6
derived_8.3: completed evaluation task 4/6

derived_8.3: completed evaluation task 5/6

derived_8.3: completed evaluation task 6/6
    dataset                                       model  beta       R2     RMSE   ubRMSE      Bias      MAE  Med|Err|  Pearson
derived_8.0                                  2.0_global   0.0 0.819465 0.044646 0.041695  0.015963 0.033560  0.024610 0.918766
derived_8.0                                hand_mdr_v25   0.0 0.881504 0.036170 0.034839  0.009723 0.028257  0.023839 0.950580
derived_8.0                                  2.0_global   0.2 0.819797 0.044605 0.041782  0.015615 0.033445  0.024609 0.918210
derived_8.0                                hand_mdr_v25   0.2 0.886868 0.035342 0.034190  0.008949 0.027476  0.022655 0.951739
derived_8.3                                          V0   0.0 0.729328 0.058697 0.058552 -0.004115 0.038586  0.025229 0.854875
derived_8.3 2.0_clustering_v0_full_k2_shared_plus_delta   0.0 0.762534 0.054978 0.054825  0.004107 0.035541  0.022534 0.874130
derived_8.3                                  2.0_global   0.0 0.808574 0.049362 0.049261  0.003157 0.032991  0.022940 0.899987
derived_8.3                                          V0   0.2 0.719149 0.059790 0.059599 -0.004780 0.039072  0.025066 0.849087
derived_8.3 2.0_clustering_v0_full_k2_shared_plus_delta   0.2 0.768047 0.054337 0.054198  0.003881 0.035206  0.023220 0.877126
derived_8.3                                  2.0_global   0.2 0.811504 0.048983 0.048928  0.002311 0.032198  0.021813 0.901437

derived_8.0: completed evaluation task 1/4
derived_8.0: completed evaluation task 2/4
derived_8.0: completed evaluation task 3/4
derived_8.0: completed evaluation task 4/4

derived_8.3: completed evaluation task 1/6
derived_8.3: completed evaluation task 2/6

derived_8.3: completed evaluation task 3/6
derived_8.3: completed evaluation task 4/6

derived_8.3: completed evaluation task 5/6

derived_8.3: completed evaluation task 6/6
    dataset                                       model  beta       R2     RMSE   ubRMSE      Bias      MAE  Med|Err|  Pearson
derived_8.0                                  2.0_global   0.0 0.786632 0.043496 0.043494  0.000413 0.032618  0.025319 0.887589
derived_8.0                                hand_mdr_v25   0.0 0.822222 0.039703 0.039634 -0.002333 0.028600  0.020840 0.907106
derived_8.0                                  2.0_global   0.2 0.779641 0.044203 0.044202 -0.000317 0.033256  0.025342 0.884209
derived_8.0                                hand_mdr_v25   0.2 0.825348 0.039352 0.039256 -0.002752 0.028132  0.020375 0.909041
derived_8.3 2.0_clustering_v0_full_k2_shared_plus_delta   0.0 0.588945 0.066626 0.062767 -0.022347 0.048302  0.035612 0.803665
derived_8.3                                  2.0_global   0.0 0.590815 0.066475 0.062582 -0.022413 0.047916  0.034527 0.806179
derived_8.3                                          V0   0.0 0.645478 0.061875 0.060073 -0.014826 0.045292  0.033612 0.817091
derived_8.3 2.0_clustering_v0_full_k2_shared_plus_delta   0.2 0.588185 0.066688 0.063067 -0.021674 0.048237  0.035363 0.802431
derived_8.3                                  2.0_global   0.2 0.597789 0.065906 0.062126 -0.021999 0.047576  0.034366 0.809230
derived_8.3                                          V0   0.2 0.635567 0.062734 0.060911 -0.015015 0.045671  0.033376 0.811979

coerce_numeric: replaced 726 inf values with NaN
coerce_numeric: replaced 417 inf values with NaN

coerce_numeric: replaced 1475 inf values with NaN
coerce_numeric: replaced 842 inf values with NaN

[
  {
    "dataset": "derived_8.0",
    "global_n_features": 40,
    "outer_stopping_reason": "minimum_outer_upper_confidence_bound",
    "regimes": {}
  },
  {
    "dataset": "derived_8.3",
    "global_n_features": 125,
    "outer_stopping_reason": "minimum_outer_upper_confidence_bound",
    "regimes": {
      "0": {
        "n_features": 125,
        "n_delta": 0,
        "outer_stopping_reason": "no_outer_delta_with_positive_paired_lcb"
      },
      "1": {
        "n_features": 125,
        "n_delta": 0,
        "outer_stopping_reason": "no_outer_delta_with_positive_paired_lcb"
      }
    },
    "router": {
      "kind": "clustering_v0_full_k2",
      "feature_source": "data/splits/derived_8.3/dataset_metadata.py::OVERALL_SELECTED_FEATURES_V0",
      "feature_count": 50,
      "fit_scope": "inner_training_split",
      "frozen_for_evaluation": true
    }
  }
]

coerce_numeric: replaced 726 inf values with NaN
coerce_numeric: replaced 417 inf values with NaN

{
  "dataset": "derived_8.0",
  "n_features": 40,
  "outer_stopping_reason": "minimum_outer_upper_confidence_bound",
  "source_inner_selection": "notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/nested/derived_8.0/global/inner_selection.json"
}

coerce_numeric: replaced 1475 inf values with NaN
coerce_numeric: replaced 842 inf values with NaN

{
  "dataset": "derived_8.3",
  "n_features": 125,
  "outer_stopping_reason": "minimum_outer_upper_confidence_bound",
  "source_inner_selection": "notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/nested/derived_8.3/global/inner_selection.json"
}

coerce_numeric: replaced 726 inf values with NaN
coerce_numeric: replaced 417 inf values with NaN

Saved forward-time inner result for derived_8.0

{
  "dataset": "derived_8.0",
  "n_features": 40,
  "selected_sources": [
    "station_time"
  ],
  "n_unique_candidates": 14
}

coerce_numeric: replaced 1475 inf values with NaN
coerce_numeric: replaced 842 inf values with NaN

Saved forward-time inner result for derived_8.3

{
  "dataset": "derived_8.3",
  "n_features": 65,
  "selected_sources": [
    "forward_time"
  ],
  "n_unique_candidates": 14
}

coerce_numeric: replaced 726 inf values with NaN
coerce_numeric: replaced 417 inf values with NaN

Saved forward-time inner result for derived_8.0

{
  "dataset": "derived_8.0",
  "n_features": 80,
  "selected_sources": [
    "forward_time"
  ],
  "n_unique_candidates": 14
}

    dataset  candidate_index  n_features  beta  outer_R2  outer_RMSE  outer_MAE  outer_Bias  retrospective_test_R2  retrospective_test_RMSE  retrospective_test_MAE  retrospective_test_Bias
derived_8.0                6          40   0.0  0.814845    0.045213   0.035248    0.017178               0.763959                 0.045749                0.033964                 0.005843
derived_8.0                5          50   0.0  0.824928    0.043965   0.034189    0.017370               0.769349                 0.045223                0.033785                 0.004731
derived_8.0                4          65   0.0  0.837193    0.042397   0.032928    0.018106               0.770186                 0.045141                0.033310                 0.005274
derived_8.0                3          80   0.0  0.834629    0.042730   0.033181    0.017766               0.769338                 0.045224                0.033281                 0.004726
derived_8.0                2         100   0.0  0.826132    0.043814   0.034263    0.019434               0.767461                 0.045408                0.033368                 0.005161
derived_8.0                1         125   0.0  0.829861    0.043341   0.033716    0.018658               0.767299                 0.045424                0.033371                 0.004925
derived_8.0                0         150   0.0  0.828883    0.043466   0.033719    0.017943               0.776693                 0.044497                0.032742                 0.005534
derived_8.0                6          40   0.2  0.816226    0.045045   0.035004    0.017227               0.767958                 0.045359                0.033795                 0.005742
derived_8.0                5          50   0.2  0.825641    0.043875   0.033945    0.017500               0.776206                 0.044546                0.033221                 0.005110
derived_8.0                4          65   0.2  0.835438    0.042625   0.032700    0.017005               0.779664                 0.044200                0.032726                 0.005266
derived_8.0                3          80   0.2  0.833098    0.042927   0.032843    0.017517               0.777415                 0.044425                0.032863                 0.004466
derived_8.0                2         100   0.2  0.822617    0.044254   0.034035    0.018999               0.776372                 0.044529                0.032778                 0.005150
derived_8.0                1         125   0.2  0.827898    0.043591   0.033707    0.018976               0.779678                 0.044199                0.032440                 0.005217
derived_8.0                0         150   0.2  0.830590    0.043248   0.033014    0.017109               0.783099                 0.043855                0.032287                 0.004555
derived_8.3                6          40   0.0  0.769327    0.054186   0.036440    0.005068               0.560449                 0.068897                0.050481                -0.013972
derived_8.3                5          50   0.0  0.773107    0.053741   0.036199    0.005223               0.558914                 0.069017                0.050641                -0.013761
derived_8.3                4          65   0.0  0.764487    0.054752   0.036853    0.005517               0.563457                 0.068661                0.049982                -0.013720
derived_8.3                3          80   0.0  0.776934    0.053285   0.035977    0.005378               0.549964                 0.069714                0.050724                -0.013645
derived_8.3                2         100   0.0  0.777177    0.053256   0.036124    0.005750               0.542999                 0.070251                0.051072                -0.014550
derived_8.3                1         125   0.0  0.775916    0.053407   0.036246    0.005894               0.554386                 0.069371                0.050092                -0.014162
derived_8.3                0         150   0.0  0.770200    0.054084   0.036646    0.005152               0.549186                 0.069774                0.050553                -0.013468
derived_8.3                6          40   0.2  0.771174    0.053969   0.035936    0.004715               0.559879                 0.068942                0.050429                -0.013747
derived_8.3                5          50   0.2  0.774457    0.053580   0.035805    0.004944               0.557693                 0.069113                0.050348                -0.013950
derived_8.3                4          65   0.2  0.766459    0.054522   0.036119    0.004739               0.566062                 0.068456                0.049852                -0.013513
derived_8.3                3          80   0.2  0.776109    0.053384   0.035660    0.005115               0.551745                 0.069576                0.050493                -0.013562
derived_8.3                2         100   0.2  0.774667    0.053556   0.036034    0.005005               0.547897                 0.069874                0.050434                -0.013975
derived_8.3                1         125   0.2  0.773319    0.053715   0.035975    0.005311               0.560234                 0.068914                0.049972                -0.014727
derived_8.3                0         150   0.2  0.771007    0.053989   0.036258    0.005057               0.556241                 0.069226                0.050214                -0.014131

    dataset  candidate_index  n_features  beta  outer_R2  outer_RMSE  outer_MAE  outer_Bias  retrospective_test_R2  retrospective_test_RMSE  retrospective_test_MAE  retrospective_test_Bias
derived_8.0                6          40   0.0  0.814845    0.045213   0.035248    0.017178               0.763959                 0.045749                0.033964                 0.005843
derived_8.0               13          40   0.0  0.831181    0.043173   0.033720    0.014298               0.800203                 0.042090                0.031422                -0.003236
derived_8.0                5          50   0.0  0.824928    0.043965   0.034189    0.017370               0.769349                 0.045223                0.033785                 0.004731
derived_8.0               12          50   0.0  0.817167    0.044929   0.034776    0.014123               0.798124                 0.042308                0.031601                -0.003311
derived_8.0                4          65   0.0  0.837193    0.042397   0.032928    0.018106               0.770186                 0.045141                0.033310                 0.005274
derived_8.0               11          65   0.0  0.819391    0.044655   0.034812    0.013162               0.793400                 0.042801                0.032205                -0.003606
derived_8.0                3          80   0.0  0.834629    0.042730   0.033181    0.017766               0.769338                 0.045224                0.033281                 0.004726
derived_8.0               10          80   0.0  0.823805    0.044106   0.034266    0.013318               0.793656                 0.042774                0.032166                -0.003568
derived_8.0                2         100   0.0  0.826132    0.043814   0.034263    0.019434               0.767461                 0.045408                0.033368                 0.005161
derived_8.0                9         100   0.0  0.821330    0.044415   0.034765    0.013932               0.795841                 0.042547                0.032002                -0.003175
derived_8.0                1         125   0.0  0.829861    0.043341   0.033716    0.018658               0.767299                 0.045424                0.033371                 0.004925
derived_8.0                8         125   0.0  0.832643    0.042985   0.033640    0.014068               0.794479                 0.042689                0.031703                -0.001548
derived_8.0                0         150   0.0  0.828883    0.043466   0.033719    0.017943               0.776693                 0.044497                0.032742                 0.005534
derived_8.0                7         150   0.0  0.840743    0.041932   0.032659    0.013953               0.797157                 0.042410                0.031461                -0.000768
derived_8.0                6          40   0.2  0.816226    0.045045   0.035004    0.017227               0.767958                 0.045359                0.033795                 0.005742
derived_8.0               13          40   0.2  0.828114    0.043563   0.033806    0.014412               0.795450                 0.042588                0.032056                -0.002803
derived_8.0                5          50   0.2  0.825641    0.043875   0.033945    0.017500               0.776206                 0.044546                0.033221                 0.005110
derived_8.0               12          50   0.2  0.821502    0.044393   0.034480    0.014686               0.795759                 0.042555                0.031913                -0.002834
derived_8.0                4          65   0.2  0.835438    0.042625   0.032700    0.017005               0.779664                 0.044200                0.032726                 0.005266
derived_8.0               11          65   0.2  0.818550    0.044759   0.034963    0.013322               0.788401                 0.043315                0.032701                -0.003049
derived_8.0                3          80   0.2  0.833098    0.042927   0.032843    0.017517               0.777415                 0.044425                0.032863                 0.004466
derived_8.0               10          80   0.2  0.822767    0.044236   0.034602    0.013223               0.789496                 0.043203                0.032510                -0.003387
derived_8.0                2         100   0.2  0.822617    0.044254   0.034035    0.018999               0.776372                 0.044529                0.032778                 0.005150
derived_8.0                9         100   0.2  0.821246    0.044425   0.034678    0.014483               0.790307                 0.043120                0.032293                -0.002805
derived_8.0                1         125   0.2  0.827898    0.043591   0.033707    0.018976               0.779678                 0.044199                0.032440                 0.005217
derived_8.0                8         125   0.2  0.831808    0.043093   0.033616    0.014231               0.792615                 0.042882                0.032046                -0.001840
derived_8.0                0         150   0.2  0.830590    0.043248   0.033014    0.017109               0.783099                 0.043855                0.032287                 0.004555
derived_8.0                7         150   0.2  0.834131    0.042794   0.033069    0.014046               0.794314                 0.042706                0.031747                -0.000762
derived_8.3                6          40   0.0  0.769327    0.054186   0.036440    0.005068               0.560449                 0.068897                0.050481                -0.013972
derived_8.3               13          40   0.0  0.789885    0.051715   0.035162   -0.000823               0.581700                 0.067211                0.049157                -0.026432
derived_8.3                5          50   0.0  0.773107    0.053741   0.036199    0.005223               0.558914                 0.069017                0.050641                -0.013761
derived_8.3               12          50   0.0  0.786639    0.052113   0.035390   -0.001163               0.584719                 0.066968                0.048790                -0.026299
derived_8.3                4          65   0.0  0.764487    0.054752   0.036853    0.005517               0.563457                 0.068661                0.049982                -0.013720
derived_8.3               11          65   0.0  0.793509    0.051268   0.035227   -0.000795               0.579734                 0.067369                0.049054                -0.026677
derived_8.3                3          80   0.0  0.776934    0.053285   0.035977    0.005378               0.549964                 0.069714                0.050724                -0.013645
derived_8.3               10          80   0.0  0.799020    0.050579   0.034676    0.000005               0.586301                 0.066840                0.048213                -0.023897
derived_8.3                2         100   0.0  0.777177    0.053256   0.036124    0.005750               0.542999                 0.070251                0.051072                -0.014550
derived_8.3                9         100   0.0  0.794318    0.051167   0.035076    0.000592               0.585573                 0.066899                0.048216                -0.024125
derived_8.3                1         125   0.0  0.775916    0.053407   0.036246    0.005894               0.554386                 0.069371                0.050092                -0.014162
derived_8.3                8         125   0.0  0.792562    0.051385   0.035179    0.000917               0.593405                 0.066264                0.047695                -0.023718
derived_8.3                0         150   0.0  0.770200    0.054084   0.036646    0.005152               0.549186                 0.069774                0.050553                -0.013468
derived_8.3                7         150   0.0  0.791000    0.051578   0.034980    0.001271               0.596011                 0.066051                0.047401                -0.021975
derived_8.3                6          40   0.2  0.771174    0.053969   0.035936    0.004715               0.559879                 0.068942                0.050429                -0.013747
derived_8.3               13          40   0.2  0.788852    0.051842   0.035511   -0.001259               0.571217                 0.068048                0.049397                -0.028116
derived_8.3                5          50   0.2  0.774457    0.053580   0.035805    0.004944               0.557693                 0.069113                0.050348                -0.013950
derived_8.3               12          50   0.2  0.788521    0.051883   0.035493   -0.001116               0.564904                 0.068547                0.049498                -0.028089
derived_8.3                4          65   0.2  0.766459    0.054522   0.036119    0.004739               0.566062                 0.068456                0.049852                -0.013513
derived_8.3               11          65   0.2  0.792814    0.051354   0.035251   -0.000998               0.563915                 0.068625                0.049570                -0.027562
derived_8.3                3          80   0.2  0.776109    0.053384   0.035660    0.005115               0.551745                 0.069576                0.050493                -0.013562
derived_8.3               10          80   0.2  0.796729    0.050866   0.034843   -0.000465               0.585887                 0.066874                0.047987                -0.024676
derived_8.3                2         100   0.2  0.774667    0.053556   0.036034    0.005005               0.547897                 0.069874                0.050434                -0.013975
derived_8.3                9         100   0.2  0.790374    0.051655   0.035358   -0.000510               0.582565                 0.067141                0.048060                -0.024547
derived_8.3                1         125   0.2  0.773319    0.053715   0.035975    0.005311               0.560234                 0.068914                0.049972                -0.014727
derived_8.3                8         125   0.2  0.787849    0.051965   0.035330    0.000137               0.585965                 0.066867                0.047762                -0.024675
derived_8.3                0         150   0.2  0.771007    0.053989   0.036258    0.005057               0.556241                 0.069226                0.050214                -0.014131
derived_8.3                7         150   0.2  0.785998    0.052192   0.035382    0.000935               0.586502                 0.066824                0.047616                -0.023179

    dataset  candidate_index  n_features  beta  outer_R2  outer_RMSE  outer_MAE  outer_Bias  retrospective_test_R2  retrospective_test_RMSE  retrospective_test_MAE  retrospective_test_Bias
derived_8.0                6          40   0.0  0.814845    0.045213   0.035248    0.017178               0.763959                 0.045749                0.033964                 0.005843
derived_8.0               13          40   0.0  0.813651    0.045359   0.034567    0.011325               0.799662                 0.042147                0.031199                -0.003311
derived_8.0                5          50   0.0  0.824928    0.043965   0.034189    0.017370               0.769349                 0.045223                0.033785                 0.004731
derived_8.0               12          50   0.0  0.821430    0.044402   0.034001    0.011750               0.800026                 0.042109                0.031234                -0.002769
derived_8.0                4          65   0.0  0.837193    0.042397   0.032928    0.018106               0.770186                 0.045141                0.033310                 0.005274
derived_8.0               11          65   0.0  0.820646    0.044500   0.034047    0.011795               0.799331                 0.042182                0.031271                -0.003427
derived_8.0                3          80   0.0  0.834629    0.042730   0.033181    0.017766               0.769338                 0.045224                0.033281                 0.004726
derived_8.0               10          80   0.0  0.840849    0.041918   0.031525    0.008144               0.820916                 0.039849                0.028273                -0.001614
derived_8.0                2         100   0.0  0.826132    0.043814   0.034263    0.019434               0.767461                 0.045408                0.033368                 0.005161
derived_8.0                9         100   0.0  0.842463    0.041705   0.031500    0.008895               0.818642                 0.040101                0.028406                -0.001580
derived_8.0                1         125   0.0  0.829861    0.043341   0.033716    0.018658               0.767299                 0.045424                0.033371                 0.004925
derived_8.0                8         125   0.0  0.842407    0.041713   0.031639    0.008834               0.817758                 0.040198                0.028450                -0.001269
derived_8.0                0         150   0.0  0.828883    0.043466   0.033719    0.017943               0.776693                 0.044497                0.032742                 0.005534
derived_8.0                7         150   0.0  0.841389    0.041847   0.031995    0.008625               0.817168                 0.040263                0.028724                -0.001458
derived_8.0                6          40   0.2  0.816226    0.045045   0.035004    0.017227               0.767958                 0.045359                0.033795                 0.005742
derived_8.0               13          40   0.2  0.816746    0.044981   0.034475    0.011791               0.794457                 0.042691                0.031758                -0.003758
derived_8.0                5          50   0.2  0.825641    0.043875   0.033945    0.017500               0.776206                 0.044546                0.033221                 0.005110
derived_8.0               12          50   0.2  0.820901    0.044468   0.034067    0.012026               0.796984                 0.042428                0.031555                -0.003314
derived_8.0                4          65   0.2  0.835438    0.042625   0.032700    0.017005               0.779664                 0.044200                0.032726                 0.005266
derived_8.0               11          65   0.2  0.827183    0.043681   0.033587    0.011862               0.795328                 0.042600                0.031822                -0.003260
derived_8.0                3          80   0.2  0.833098    0.042927   0.032843    0.017517               0.777415                 0.044425                0.032863                 0.004466
derived_8.0               10          80   0.2  0.845779    0.041264   0.031263    0.008655               0.816292                 0.040360                0.028783                -0.001538
derived_8.0                2         100   0.2  0.822617    0.044254   0.034035    0.018999               0.776372                 0.044529                0.032778                 0.005150
derived_8.0                9         100   0.2  0.848553    0.040891   0.031056    0.009151               0.814635                 0.040541                0.029065                -0.001897
derived_8.0                1         125   0.2  0.827898    0.043591   0.033707    0.018976               0.779678                 0.044199                0.032440                 0.005217
derived_8.0                8         125   0.2  0.843003    0.041634   0.031533    0.008961               0.817117                 0.040269                0.028731                -0.001208
derived_8.0                0         150   0.2  0.830590    0.043248   0.033014    0.017109               0.783099                 0.043855                0.032287                 0.004555
derived_8.0                7         150   0.2  0.840245    0.041998   0.031961    0.008897               0.815081                 0.040492                0.028927                -0.001271

derived_8.0: completed evaluation task 1/4

derived_8.0: completed evaluation task 2/4

derived_8.0: completed evaluation task 3/4

derived_8.0: completed evaluation task 4/4

derived_8.3: completed evaluation task 1/10

derived_8.3: completed evaluation task 2/10

derived_8.3: completed evaluation task 3/10

derived_8.3: completed evaluation task 4/10

derived_8.3: completed evaluation task 5/10

derived_8.3: completed evaluation task 6/10

derived_8.3: completed evaluation task 7/10

derived_8.3: completed evaluation task 8/10

derived_8.3: completed evaluation task 9/10

derived_8.3: completed evaluation task 10/10
    dataset                                             model  beta       R2     RMSE   ubRMSE      Bias      MAE  Med|Err|  Pearson
derived_8.0                                        2.0_global   0.0 0.763959 0.045749 0.045374  0.005843 0.033964  0.025753 0.878243
derived_8.0                                      hand_mdr_v25   0.0 0.822222 0.039703 0.039634 -0.002333 0.028600  0.020840 0.907106
derived_8.0                                        2.0_global   0.2 0.767958 0.045359 0.044994  0.005742 0.033795  0.025936 0.881195
derived_8.0                                      hand_mdr_v25   0.2 0.825348 0.039352 0.039256 -0.002752 0.028132  0.020375 0.909041
derived_8.3                                        2.0_global   0.0 0.554386 0.069371 0.067910 -0.014162 0.050092  0.037195 0.767698
derived_8.3       2.0_clustering_v0_full_k2_shared_plus_delta   0.0 0.555561 0.069279 0.067872 -0.013890 0.050073  0.036506 0.767890
derived_8.3      2.0_clustering_v0_full_k2_frozen_shared_only   0.0 0.555561 0.069279 0.067872 -0.013890 0.050073  0.036506 0.767890
derived_8.3 2.0_clustering_v0_full_k2_refit_shared_plus_delta   0.0 0.555561 0.069279 0.067872 -0.013890 0.050073  0.036506 0.767890
derived_8.3                                                V0   0.0 0.645478 0.061875 0.060073 -0.014826 0.045292  0.033612 0.817091
derived_8.3                                        2.0_global   0.2 0.560234 0.068914 0.067322 -0.014727 0.049972  0.037151 0.771957
derived_8.3       2.0_clustering_v0_full_k2_shared_plus_delta   0.2 0.564717 0.068562 0.067182 -0.013684 0.049475  0.035977 0.773147
derived_8.3      2.0_clustering_v0_full_k2_frozen_shared_only   0.2 0.564717 0.068562 0.067182 -0.013684 0.049475  0.035977 0.773147
derived_8.3 2.0_clustering_v0_full_k2_refit_shared_plus_delta   0.2 0.564717 0.068562 0.067182 -0.013684 0.049475  0.035977 0.773147
derived_8.3                                                V0   0.2 0.635567 0.062734 0.060911 -0.015015 0.045671  0.033376 0.811979

derived_8.0: completed evaluation task 1/4

derived_8.0: completed evaluation task 2/4

derived_8.0: completed evaluation task 3/4

derived_8.0: completed evaluation task 4/4

derived_8.3: completed evaluation task 1/4

derived_8.3: completed evaluation task 2/4

derived_8.3: completed evaluation task 3/4

derived_8.3: completed evaluation task 4/4
    dataset        model  beta       R2     RMSE   ubRMSE      Bias      MAE  Med|Err|  Pearson
derived_8.0   2.0_global   0.0 0.763959 0.045749 0.045374  0.005843 0.033964  0.025753 0.878243
derived_8.0 hand_mdr_v25   0.0 0.822222 0.039703 0.039634 -0.002333 0.028600  0.020840 0.907106
derived_8.0   2.0_global   0.2 0.767958 0.045359 0.044994  0.005742 0.033795  0.025936 0.881195
derived_8.0 hand_mdr_v25   0.2 0.825348 0.039352 0.039256 -0.002752 0.028132  0.020375 0.909041
derived_8.3   2.0_global   0.0 0.579734 0.067369 0.061862 -0.026677 0.049054  0.035942 0.807337
derived_8.3           V0   0.0 0.645478 0.061875 0.060073 -0.014826 0.045292  0.033612 0.817091
derived_8.3   2.0_global   0.2 0.563915 0.068625 0.062847 -0.027562 0.049570  0.035293 0.801867
derived_8.3           V0   0.2 0.635567 0.062734 0.060911 -0.015015 0.045671  0.033376 0.811979

Validation

,dataset,model,beta,R2,RMSE,ubRMSE,Bias,MAE,Med|Err|,Pearson
0,derived_8.0,2.0_global,0.0,0.819465,0.044646,0.041695,0.015963,0.033560,0.024610,0.918766
2,derived_8.0,2.0_global,0.2,0.819797,0.044605,0.041782,0.015615,0.033445,0.024609,0.918210
1,derived_8.0,hand_mdr_v25,0.0,0.881504,0.036170,0.034839,0.009723,0.028257,0.023839,0.950580
3,derived_8.0,hand_mdr_v25,0.2,0.886868,0.035342,0.034190,0.008949,0.027476,0.022655,0.951739
6,derived_8.3,2.0_clustering_v0_full_k2_shared_plus_delta,0.0,0.762534,0.054978,0.054825,0.004107,0.035541,0.022534,0.874130
9,derived_8.3,2.0_clustering_v0_full_k2_shared_plus_delta,0.2,0.768047,0.054337,0.054198,0.003881,0.035206,0.023220,0.877126
4,derived_8.3,2.0_global,0.0,0.808574,0.049362,0.049261,0.003157,0.032991,0.022940,0.899987
7,derived_8.3,2.0_global,0.2,0.811504,0.048983,0.048928,0.002311,0.032198,0.021813,0.901437
5,derived_8.3,V0,0.0,0.729328,0.058697,0.058552,-0.004115,0.038586,0.025229,0.854875
8,derived_8.3,V0,0.2,0.719149,0.059790,0.059599,-0.004780,0.039072,0.025066,0.849087

Retrospective

,artifact_set,dataset,model,beta,R2,RMSE,ubRMSE,Bias,MAE,Med|Err|,Pearson
0,final,derived_8.0,2.0_global,0.0,0.786632,0.043496,0.043494,0.000413,0.032618,0.025319,0.887589
1,final,derived_8.0,hand_mdr_v25,0.0,0.822222,0.039703,0.039634,-0.002333,0.028600,0.020840,0.907106
2,final,derived_8.0,2.0_global,0.2,0.779641,0.044203,0.044202,-0.000317,0.033256,0.025342,0.884209
3,final,derived_8.0,hand_mdr_v25,0.2,0.825348,0.039352,0.039256,-0.002752,0.028132,0.020375,0.909041
4,final,derived_8.3,2.0_global,0.0,0.590815,0.066475,0.062582,-0.022413,0.047916,0.034527,0.806179
5,final,derived_8.3,V0,0.0,0.645478,0.061875,0.060073,-0.014826,0.045292,0.033612,0.817091
6,final,derived_8.3,2.0_clustering_v0_full_k2_shared_plus_delta,0.0,0.588945,0.066626,0.062767,-0.022347,0.048302,0.035612,0.803665
7,final,derived_8.3,2.0_global,0.2,0.597789,0.065906,0.062126,-0.021999,0.047576,0.034366,0.809230
8,final,derived_8.3,V0,0.2,0.635567,0.062734,0.060911,-0.015015,0.045671,0.033376,0.811979
9,final,derived_8.3,2.0_clustering_v0_full_k2_shared_plus_delta,0.2,0.588185,0.066688,0.063067,-0.021674,0.048237,0.035363,0.802431
10,nested,derived_8.0,2.0_global,0.0,0.763959,0.045749,0.045374,0.005843,0.033964,0.025753,0.878243
11,nested,derived_8.0,hand_mdr_v25,0.0,0.822222,0.039703,0.039634,-0.002333,0.028600,0.020840,0.907106
12,nested,derived_8.0,2.0_global,0.2,0.767958,0.045359,0.044994,0.005742,0.033795,0.025936,0.881195
13,nested,derived_8.0,hand_mdr_v25,0.2,0.825348,0.039352,0.039256,-0.002752,0.028132,0.020375,0.909041
14,nested,derived_8.3,2.0_global,0.0,0.554386,0.069371,0.067910,-0.014162,0.050092,0.037195,0.767698
15,nested,derived_8.3,V0,0.0,0.645478,0.061875,0.060073,-0.014826,0.045292,0.033612,0.817091
16,nested,derived_8.3,2.0_clustering_v0_full_k2_shared_plus_delta,0.0,0.555561,0.069279,0.067872,-0.013890,0.050073,0.036506,0.767890
17,nested,derived_8.3,2.0_clustering_v0_full_k2_frozen_shared_only,0.0,0.555561,0.069279,0.067872,-0.013890,0.050073,0.036506,0.767890
18,nested,derived_8.3,2.0_clustering_v0_full_k2_refit_shared_plus_delta,0.0,0.555561,0.069279,0.067872,-0.013890,0.050073,0.036506,0.767890
19,nested,derived_8.3,2.0_global,0.2,0.560234,0.068914,0.067322,-0.014727,0.049972,0.037151,0.771957
20,nested,derived_8.3,V0,0.2,0.635567,0.062734,0.060911,-0.015015,0.045671,0.033376,0.811979
21,nested,derived_8.3,2.0_clustering_v0_full_k2_shared_plus_delta,0.2,0.564717,0.068562,0.067182,-0.013684,0.049475,0.035977,0.773147
22,nested,derived_8.3,2.0_clustering_v0_full_k2_frozen_shared_only,0.2,0.564717,0.068562,0.067182,-0.013684,0.049475,0.035977,0.773147
23,nested,derived_8.3,2.0_clustering_v0_full_k2_refit_shared_plus_delta,0.2,0.564717,0.068562,0.067182,-0.013684,0.049475,0.035977,0.773147
24,crossed,derived_8.0,2.0_global,0.0,0.763959,0.045749,0.045374,0.005843,0.033964,0.025753,0.878243
25,crossed,derived_8.0,hand_mdr_v25,0.0,0.822222,0.039703,0.039634,-0.002333,0.028600,0.020840,0.907106
26,crossed,derived_8.0,2.0_global,0.2,0.767958,0.045359,0.044994,0.005742,0.033795,0.025936,0.881195
27,crossed,derived_8.0,hand_mdr_v25,0.2,0.825348,0.039352,0.039256,-0.002752,0.028132,0.020375,0.909041
28,crossed,derived_8.3,2.0_global,0.0,0.579734,0.067369,0.061862,-0.026677,0.049054,0.035942,0.807337
29,crossed,derived_8.3,V0,0.0,0.645478,0.061875,0.060073,-0.014826,0.045292,0.033612,0.817091
30,crossed,derived_8.3,2.0_global,0.2,0.563915,0.068625,0.062847,-0.027562,0.049570,0.035293,0.801867
31,crossed,derived_8.3,V0,0.2,0.635567,0.062734,0.060911,-0.015015,0.045671,0.033376,0.811979

Candidate diagnostics

,artifact_set,dataset,full_train_diagnostic_n_features,full_train_diagnostic_retrospective_R2,retrospective_ceiling_n_features,retrospective_ceiling_R2
0,crossed_candidates_locked_outer,derived_8.0,150,0.797157,40,0.800203
1,crossed_candidates_locked_outer,derived_8.3,80,0.586301,150,0.596011
2,nested,derived_8.0,65,0.770186,150,0.776693
3,nested,derived_8.3,100,0.542999,65,0.563457
4,progressive_crossed_locked_outer,derived_8.0,100,0.818642,80,0.820916

MoE ablation

,artifact_set,dataset,model,beta,R2,RMSE,ubRMSE,Bias,MAE,Med|Err|,Pearson
17,nested,derived_8.3,2.0_clustering_v0_full_k2_frozen_shared_only,0.0,0.555561,0.069279,0.067872,-0.013890,0.050073,0.036506,0.767890
18,nested,derived_8.3,2.0_clustering_v0_full_k2_refit_shared_plus_delta,0.0,0.555561,0.069279,0.067872,-0.013890,0.050073,0.036506,0.767890
16,nested,derived_8.3,2.0_clustering_v0_full_k2_shared_plus_delta,0.0,0.555561,0.069279,0.067872,-0.013890,0.050073,0.036506,0.767890
14,nested,derived_8.3,2.0_global,0.0,0.554386,0.069371,0.067910,-0.014162,0.050092,0.037195,0.767698

Artifacts:
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/crossed_candidates_locked_outer/candidate_diagnostics/global_candidates.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/crossed_candidates_locked_outer/derived_8.0/global/outer_fold_metrics.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/crossed_candidates_locked_outer/derived_8.3/global/outer_fold_metrics.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/crossed_candidates_locked_outer/retrospective_test_eval/metrics_by_station.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/crossed_candidates_locked_outer/retrospective_test_eval/metrics_by_year.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/crossed_candidates_locked_outer/retrospective_test_eval/metrics_summary.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/final/derived_8.0/global/fold_metrics.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/final/derived_8.3/global/fold_metrics.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/final/derived_8.3/regime_0/fold_metrics.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/final/derived_8.3/regime_1/fold_metrics.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/final/retrospective_test_eval/metrics_by_station.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/final/retrospective_test_eval/metrics_by_year.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/final/retrospective_test_eval/metrics_summary.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/final/validation_eval/metrics_by_station.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/final/validation_eval/metrics_by_year.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/final/validation_eval/metrics_summary.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/nested/candidate_diagnostics/global_candidates.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/nested/derived_8.0/global/outer_fold_metrics.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/nested/derived_8.3/global/outer_fold_metrics.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/nested/derived_8.3/regime_0/outer_fold_metrics.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/nested/derived_8.3/regime_1/outer_fold_metrics.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/nested/retrospective_test_eval/metrics_by_station.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/nested/retrospective_test_eval/metrics_by_year.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/nested/retrospective_test_eval/metrics_summary.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/nested_locked_outer/derived_8.0/global/outer_fold_metrics.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/nested_locked_outer/derived_8.3/global/outer_fold_metrics.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/progressive_crossed_locked_outer/candidate_diagnostics/global_candidates.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/progressive_crossed_locked_outer/derived_8.0/global/outer_fold_metrics.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/report/beta_effects.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/report/candidate_alignment_summary.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/report/candidate_ceiling.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/report/candidate_rank_summary.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/report/candidate_transfer.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/report/candidate_winner_alignment.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/report/feature_stability.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/report/importance_lcb_counts.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/report/locked_outer_equivalence.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/report/model_year_errors.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/report/moe_errors.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/report/moe_population_summary.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/report/moe_regime_selection.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/report/outer_fold_coverage.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/report/progressive_path_overlap.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/report/pruning_path_sensitivity.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/report/router_feature_coverage.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/report/router_feature_summary.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/report/selected_arm_errors.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/report/station_coverage.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/report/station_diagnostic_selection.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/report/station_errors.csv
/scratch/user/u.rp352032/MDR-Project/notebooks/experiment/derived_8.3-feature-selection-2.0/artifacts/report/target_shift.csv